# Generated by Claude Code
"""Text retrieval service with caching."""

from .cache import SefariaCache
from .sefaria_client import SefariaClient

__all__ = ["SefariaClient", "SefariaCache", "CachedSefariaClient"]


class CachedSefariaClient:
    """Sefaria client with file-based caching.

    Combines SefariaClient and SefariaCache to minimize API calls.
    """

    def __init__(self) -> None:
        """Initialize cached client."""
        self.client = SefariaClient()
        self.cache = SefariaCache()

    def get_verse(self, book: str, chapter: int, verse: int) -> str:
        """Get single verse text with caching.

        Args:
            book: Book name (e.g., "Deuteronomy")
            chapter: Chapter number (1-indexed)
            verse: Verse number (1-indexed)

        Returns:
            Hebrew text with vowels and cantillation marks

        Raises:
            HebrewTextUnavailableError: When API fails
            InvalidReferenceError: When reference is invalid
        """
        # Check cache first
        cached_response = self.cache.get(book, chapter, verse)
        if cached_response:
            hebrew_text = cached_response["he"]
            if isinstance(hebrew_text, list):
                hebrew_text = hebrew_text[0] if hebrew_text else ""
            return hebrew_text

        # Cache miss - fetch from API
        hebrew_text = self.client.get_verse(book, chapter, verse)

        # Cache the full response for future use
        # (We need to reconstruct a minimal response structure)
        response = {
            "ref": f"{book} {chapter}:{verse}",
            "he": [hebrew_text],
        }
        self.cache.set(book, chapter, verse, response)

        return hebrew_text

    def get_range(
        self,
        book: str,
        chapter_start: int,
        verse_start: int,
        chapter_end: int,
        verse_end: int,
    ) -> list[tuple[str, str]]:
        """Get range of verses with caching.

        Args:
            book: Book name
            chapter_start: Starting chapter
            verse_start: Starting verse
            chapter_end: Ending chapter
            verse_end: Ending verse

        Returns:
            List of (reference, hebrew_text) tuples

        Raises:
            HebrewTextUnavailableError: When API fails
            InvalidReferenceError: When reference is invalid
        """
        # For ranges, we fetch directly (could optimize with per-verse caching later)
        return self.client.get_range(book, chapter_start, verse_start, chapter_end, verse_end)
