# Generated by Claude Code
"""File-based caching for Sefaria API responses."""

import json
from pathlib import Path
from typing import Any

from src.lib.config import get_cache_dir
from src.lib.logging import get_logger

logger = get_logger(__name__)


class SefariaCache:
    """File-based cache for Sefaria API responses.

    Biblical text never changes, so cache entries never expire.
    Cache key format: {book}_{chapter}_{verse}.json
    """

    def __init__(self, cache_dir: Path | None = None) -> None:
        """Initialize cache.

        Args:
            cache_dir: Cache directory path (default from config)
        """
        self.cache_dir = cache_dir or get_cache_dir() / "sefaria"
        self.cache_dir.mkdir(parents=True, exist_ok=True)

        logger.debug(f"Initialized SefariaCache", cache_dir=str(self.cache_dir))

    def get(self, book: str, chapter: int, verse: int) -> dict[str, Any] | None:
        """Retrieve cached response for a verse.

        Args:
            book: Book name
            chapter: Chapter number
            verse: Verse number

        Returns:
            Cached response dictionary, or None if not cached
        """
        cache_key = self._make_cache_key(book, chapter, verse)
        cache_file = self.cache_dir / cache_key

        if not cache_file.exists():
            logger.debug(f"Cache miss: {cache_key}")
            return None

        try:
            with cache_file.open("r", encoding="utf-8") as f:
                data = json.load(f)
            logger.debug(f"Cache hit: {cache_key}")
            return data
        except Exception as e:
            logger.warning(f"Failed to read cache file {cache_file}: {e}")
            return None

    def set(self, book: str, chapter: int, verse: int, response: dict[str, Any]) -> None:
        """Store API response in cache.

        Args:
            book: Book name
            chapter: Chapter number
            verse: Verse number
            response: Sefaria API response to cache
        """
        cache_key = self._make_cache_key(book, chapter, verse)
        cache_file = self.cache_dir / cache_key

        try:
            with cache_file.open("w", encoding="utf-8") as f:
                json.dump(response, f, ensure_ascii=False, indent=2)
            logger.debug(f"Cached response: {cache_key}")
        except Exception as e:
            logger.warning(f"Failed to write cache file {cache_file}: {e}")

    def _make_cache_key(self, book: str, chapter: int, verse: int) -> str:
        """Generate cache key filename.

        Args:
            book: Book name
            chapter: Chapter number
            verse: Verse number

        Returns:
            Cache key (e.g., "Deuteronomy_32_1.json")
        """
        # Sanitize book name for filesystem
        safe_book = book.replace(" ", "_").replace("/", "_")
        return f"{safe_book}_{chapter}_{verse}.json"
