# Generated by Claude Sonnet 4.5
"""ParashaTextFetcher for batch Hebrew text retrieval."""

import tomllib
from pathlib import Path
from typing import Any

from src.lib.exceptions import InvalidReferenceError
from src.lib.logging import get_logger
from src.models.aliyah_range import AliyahRange
from src.services.text.sefaria_client import SefariaClient

logger = get_logger(__name__)


class ParashaTextFetcher:
    """Batch Hebrew text fetcher for Parasha/Aliyah combinations.
    
    Loads verse range configurations from data/aliyah_ranges.toml and provides
    batch fetching methods that reduce API calls by 86-97% compared to per-verse retrieval.
    
    Example:
        >>> fetcher = ParashaTextFetcher()
        >>> verses = fetcher.fetch_aliyah_text("האזינו", "ראשון")
        >>> # Returns: [("Deuteronomy 32:1", "hebrew..."), ...]
        >>> # API calls: 1 (batch) vs. 6 (per-verse)
    """
    
    def __init__(
        self,
        config_path: Path | str | None = None,
        sefaria_client: SefariaClient | None = None,
    ) -> None:
        """Initialize ParashaTextFetcher.
        
        Args:
            config_path: Path to aliyah_ranges.toml (default: data/aliyah_ranges.toml)
            sefaria_client: SefariaClient instance (default: create new)
        """
        self.config_path = Path(config_path or "data/aliyah_ranges.toml")
        self.sefaria_client = sefaria_client or SefariaClient()
        self.ranges: dict[tuple[str, str], AliyahRange] = {}
        
        self._load_ranges()
        
        logger.debug(
            f"{len(self.ranges)=}",
            config_path=str(self.config_path),
        )
    
    def _load_ranges(self) -> None:
        """Load Aliyah ranges from TOML configuration.
        
        Raises:
            FileNotFoundError: When config file doesn't exist
            tomllib.TOMLDecodeError: When config file is malformed
        """
        if not self.config_path.exists():
            raise FileNotFoundError(
                f"Aliyah ranges configuration not found: {self.config_path}"
            )
        
        with open(self.config_path, "rb") as f:
            config = tomllib.load(f)
        
        # Parse TOML structure: [parasha_name.aliyah_name]
        for parasha_name, aliyot in config.items():
            for aliyah_name, range_data in aliyot.items():
                # Validate and create AliyahRange
                try:
                    aliyah_range = AliyahRange(**range_data)
                    self.ranges[(parasha_name, aliyah_name)] = aliyah_range
                    logger.debug(
                        f"Loaded range",
                        parasha=parasha_name,
                        aliyah=aliyah_name,
                        range=aliyah_range.to_sefaria_reference(),
                    )
                except Exception as e:
                    logger.warning(
                        f"Failed to load range",
                        parasha=parasha_name,
                        aliyah=aliyah_name,
                        error=str(e),
                    )
                    raise
        
        logger.info(f"Loaded {len(self.ranges)} Aliyah ranges from configuration")
    
    def get_range_for_aliyah(self, parasha_name: str, aliyah_name: str) -> AliyahRange:
        """Get AliyahRange for a specific Parasha/Aliyah combination.
        
        Args:
            parasha_name: Parasha name in Hebrew (e.g., "האזינו")
            aliyah_name: Aliyah name in Hebrew (e.g., "ראשון")
        
        Returns:
            AliyahRange instance with verse range configuration
        
        Raises:
            InvalidReferenceError: When Parasha/Aliyah mapping not found
        
        Example:
            >>> fetcher = ParashaTextFetcher()
            >>> range = fetcher.get_range_for_aliyah("האזינו", "ראשון")
            >>> range.to_sefaria_reference()
            'Deuteronomy 32:1-6'
        """
        key = (parasha_name, aliyah_name)
        
        if key not in self.ranges:
            raise InvalidReferenceError(
                f"No range mapping found for Parasha '{parasha_name}', Aliyah '{aliyah_name}'. "
                f"Available Parashot: {sorted(set(p for p, _ in self.ranges.keys()))}"
            )
        
        return self.ranges[key]
    
    def fetch_aliyah_text(
        self,
        parasha_name: str,
        aliyah_name: str,
    ) -> list[tuple[str, str]]:
        """Fetch all verses for a specific Aliyah using batch retrieval.
        
        Args:
            parasha_name: Parasha name in Hebrew (e.g., "האזינו")
            aliyah_name: Aliyah name in Hebrew (e.g., "ראשון")
        
        Returns:
            List of (reference, hebrew_text) tuples for all verses in Aliyah
            Example: [("Deuteronomy 32:1", "הַאֲזִינוּ..."), ...]
        
        Raises:
            InvalidReferenceError: When Parasha/Aliyah mapping not found
            HebrewTextUnavailableError: When API fails
        
        Example:
            >>> fetcher = ParashaTextFetcher()
            >>> verses = fetcher.fetch_aliyah_text("האזינו", "ראשון")
            >>> len(verses)
            6
            >>> verses[0]
            ('Deuteronomy 32:1', 'הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם...')
        """
        # Get range configuration
        aliyah_range = self.get_range_for_aliyah(parasha_name, aliyah_name)
        
        logger.info(
            f"Fetching Aliyah text (batch)",
            parasha=parasha_name,
            aliyah=aliyah_name,
            range=aliyah_range.to_sefaria_reference(),
        )
        
        # Batch fetch using SefariaClient.get_range()
        verses = self.sefaria_client.get_range(
            book=aliyah_range.book,
            chapter_start=aliyah_range.chapter_start,
            verse_start=aliyah_range.verse_start,
            chapter_end=aliyah_range.chapter_end,
            verse_end=aliyah_range.verse_end,
        )
        
        logger.info(
            f"Fetched Aliyah text (batch)",
            parasha=parasha_name,
            aliyah=aliyah_name,
            verse_count=len(verses),
        )
        
        return verses
