# Generated by Claude Code
"""SefariaClient for retrieving Hebrew text from Sefaria API."""

import time
from typing import Any

import httpx

from src.lib.config import settings
from src.lib.exceptions import HebrewTextUnavailableError, InvalidReferenceError
from src.lib.hebrew_validator import validate_sefaria_response
from src.lib.logging import get_logger

logger = get_logger(__name__)


class SefariaClient:
    """Client for retrieving Hebrew text from Sefaria API.

    Implements the HebrewTextSource protocol with retry logic,
    response validation, and error handling per FR-002a.
    """

    def __init__(
        self,
        base_url: str | None = None,
        retry_attempts: int | None = None,
        cache_dir: str | None = None,
    ) -> None:
        """Initialize Sefaria API client.

        Args:
            base_url: Sefaria API base URL (default from config)
            retry_attempts: Maximum retry attempts (default from config)
            cache_dir: Cache directory path (default from config)
        """
        self.base_url = (base_url or settings.get("sefaria.base_url")).rstrip("/")
        self.retry_attempts = retry_attempts or settings.get("sefaria.retry_attempts", 3)
        self.retry_backoff_base = settings.get("sefaria.retry_backoff_base", 2)
        self.retry_backoff_multiplier = settings.get("sefaria.retry_backoff_multiplier", 2)
        self.request_delay = settings.get("sefaria.request_delay", 0.1)

        self._last_request_time: float = 0.0

        logger.debug(
            f"Initialized SefariaClient",
            base_url=self.base_url,
            retry_attempts=self.retry_attempts,
        )

    def get_verse(self, book: str, chapter: int, verse: int) -> str:
        """Get single verse text.

        Args:
            book: Book name (e.g., "Deuteronomy")
            chapter: Chapter number (1-indexed)
            verse: Verse number (1-indexed)

        Returns:
            Hebrew text with vowels and cantillation marks

        Raises:
            HebrewTextUnavailableError: When API fails per FR-002a
            InvalidReferenceError: When reference is invalid
        """
        reference = f"{book}.{chapter}.{verse}"
        logger.debug(f"Fetching verse: {reference}")

        # Use API v3 endpoint which properly returns individual verses
        response = self._make_request(f"/v3/texts/{reference}")

        # V3 API returns versions array with text field
        if "versions" not in response or not response["versions"]:
            raise HebrewTextUnavailableError(
                f"No versions available for {reference}"
            )

        # Get the first version's text
        hebrew_text = response["versions"][0].get("text", "")

        # Validate response has Hebrew text with diacritics
        # Create a minimal v2-like response for validation
        validation_response = {"he": [hebrew_text] if hebrew_text else []}
        if not validate_sefaria_response(validation_response):
            raise HebrewTextUnavailableError(
                f"Hebrew text incomplete: Missing vowels or cantillation marks for {reference}"
            )

        # Clean HTML entities from text
        import html
        hebrew_text = html.unescape(hebrew_text)

        logger.info(f"Retrieved verse", reference=reference, text_length=len(hebrew_text))
        return hebrew_text

    def get_range(
        self,
        book: str,
        chapter_start: int,
        verse_start: int,
        chapter_end: int,
        verse_end: int,
    ) -> list[tuple[str, str]]:
        """Get range of verses.

        Args:
            book: Book name
            chapter_start: Starting chapter
            verse_start: Starting verse
            chapter_end: Ending chapter
            verse_end: Ending verse

        Returns:
            List of (reference, hebrew_text) tuples ordered by canonical order

        Raises:
            HebrewTextUnavailableError: When API fails
            InvalidReferenceError: When reference is invalid
        """
        reference = f"{book}.{chapter_start}.{verse_start}-{book}.{chapter_end}.{verse_end}"
        logger.debug(f"Fetching verse range: {reference}")

        response = self._make_request(f"/texts/{reference}")

        # Validate response
        if not validate_sefaria_response(response):
            raise HebrewTextUnavailableError(
                f"Hebrew text incomplete: Missing vowels or cantillation marks for range {reference}"
            )

        # Extract Hebrew texts
        hebrew_texts = response["he"]
        if not isinstance(hebrew_texts, list):
            hebrew_texts = [hebrew_texts]

        # Build list of (reference, text) tuples
        results = []
        current_chapter = chapter_start
        current_verse = verse_start

        for hebrew_text in hebrew_texts:
            verse_ref = f"{book} {current_chapter}:{current_verse}"
            results.append((verse_ref, hebrew_text))

            # Increment verse/chapter
            current_verse += 1
            # Note: This is simplified - real implementation would need chapter verse counts

        logger.info(f"Retrieved verse range", reference=reference, verse_count=len(results))
        return results

    def _make_request(self, endpoint: str) -> dict[str, Any]:
        """Make HTTP request to Sefaria API with retry logic.

        Args:
            endpoint: API endpoint (e.g., "/texts/Deuteronomy.32.1")

        Returns:
            Response JSON as dictionary

        Raises:
            HebrewTextUnavailableError: When all retries fail
            InvalidReferenceError: When reference is invalid (404)
        """
        url = f"{self.base_url}{endpoint}"

        # Rate limiting: ensure delay between requests
        self._enforce_rate_limit()

        for attempt in range(self.retry_attempts):
            try:
                logger.debug(f"Making request (attempt {attempt + 1}/{self.retry_attempts}): {url}")

                response = httpx.get(url, timeout=10.0)

                # Handle different status codes
                if response.status_code == 200:
                    return response.json()

                elif response.status_code == 404:
                    # Invalid reference - don't retry
                    error_msg = response.json().get("error", "Not found")
                    raise InvalidReferenceError(f"Invalid biblical reference: {error_msg}")

                elif response.status_code == 429:
                    # Rate limited - wait and retry
                    retry_after = int(response.headers.get("Retry-After", 5))
                    logger.warning(f"Rate limited, waiting {retry_after}s")
                    time.sleep(retry_after)
                    continue

                elif response.status_code >= 500:
                    # Server error - retry with backoff
                    if attempt < self.retry_attempts - 1:
                        delay = self._calculate_backoff_delay(attempt)
                        logger.warning(
                            f"Server error {response.status_code}, retrying in {delay}s"
                        )
                        time.sleep(delay)
                        continue
                    else:
                        raise HebrewTextUnavailableError(
                            f"Hebrew text source unavailable: Server error {response.status_code}"
                        )

                else:
                    # Other error
                    raise HebrewTextUnavailableError(
                        f"Hebrew text source unavailable: HTTP {response.status_code}"
                    )

            except httpx.TimeoutException as e:
                if attempt < self.retry_attempts - 1:
                    delay = self._calculate_backoff_delay(attempt)
                    logger.warning(f"Request timeout, retrying in {delay}s")
                    time.sleep(delay)
                    continue
                else:
                    raise HebrewTextUnavailableError(
                        "Hebrew text source unavailable: Connection timeout"
                    ) from e

            except httpx.ConnectError as e:
                if attempt < self.retry_attempts - 1:
                    delay = self._calculate_backoff_delay(attempt)
                    logger.warning(f"Connection error, retrying in {delay}s")
                    time.sleep(delay)
                    continue
                else:
                    raise HebrewTextUnavailableError(
                        "Hebrew text source unavailable: Connection failed"
                    ) from e

            except InvalidReferenceError:
                # Don't retry invalid references
                raise

            except Exception as e:
                raise HebrewTextUnavailableError(
                    f"Hebrew text source unavailable: {type(e).__name__}: {e}"
                ) from e

        # Should not reach here, but just in case
        raise HebrewTextUnavailableError("Hebrew text source unavailable: All retries exhausted")

    def _calculate_backoff_delay(self, attempt: int) -> float:
        """Calculate exponential backoff delay.

        Args:
            attempt: Attempt number (0-indexed)

        Returns:
            Delay in seconds (e.g., 2s, 4s, 8s)
        """
        return self.retry_backoff_base * (self.retry_backoff_multiplier**attempt)

    def _enforce_rate_limit(self) -> None:
        """Enforce rate limiting between requests."""
        now = time.time()
        elapsed = now - self._last_request_time

        if elapsed < self.request_delay:
            sleep_time = self.request_delay - elapsed
            logger.debug(f"Rate limiting: sleeping {sleep_time:.3f}s")
            time.sleep(sleep_time)

        self._last_request_time = time.time()
