# Generated by Claude Code
"""Configuration management using dynaconf."""

from pathlib import Path

from dynaconf import Dynaconf

# Project root directory
PROJECT_ROOT = Path(__file__).parent.parent.parent

# Load configuration with priority:
# 1. Environment variables (TORAH_SYNC_*)
# 2. .secrets.toml (gitignored)
# 3. settings.toml (committed)
# 4. Defaults
settings = Dynaconf(
    envvar_prefix="TORAH_SYNC",
    settings_files=["settings.toml", ".secrets.toml"],
    root_path=PROJECT_ROOT,
    load_dotenv=True,
    environments=True,
    env_switcher="TORAH_SYNC_ENV",
    merge_enabled=True,
)


def get_cache_dir() -> Path:
    """Get cache directory path, creating it if needed."""
    cache_dir = Path(settings.cache_dir)
    cache_dir.mkdir(parents=True, exist_ok=True)
    return cache_dir


def get_output_dir() -> Path:
    """Get output directory path, creating it if needed."""
    output_dir = Path(settings.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def get_log_dir() -> Path:
    """Get log directory path, creating it if needed."""
    log_dir = Path(settings.get("log_dir", "output/logs"))
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir


def get_timestamp_map_dir() -> Path:
    """Get timestamp map directory path, creating it if needed."""
    timestamp_dir = Path(settings.get("timestamp_map_dir", "data/timestamp_maps"))
    timestamp_dir.mkdir(parents=True, exist_ok=True)
    return timestamp_dir


def get_db_path() -> Path:
    """Get DuckDB database file path, creating parent dir if needed."""
    db_path = Path(settings.get("db_path", "data/torah_sync.duckdb"))
    db_path.parent.mkdir(parents=True, exist_ok=True)
    return db_path


def get_font_path() -> str:
    """Get Hebrew font name or path.

    Returns font name (for system fonts) or path to font file.
    MoviePy will search for system fonts automatically.
    """
    font_path = settings.font_path

    # If it's a path that exists, return it as absolute path
    path_obj = Path(font_path)
    if path_obj.exists():
        return str(path_obj.absolute())

    # Otherwise, assume it's a system font name (e.g., "Arial")
    # MoviePy will find it automatically
    return font_path
