# Generated by Claude Code
"""Configuration management using dynaconf."""

from pathlib import Path

from dynaconf import Dynaconf

# Project root directory
PROJECT_ROOT = Path(__file__).parent.parent.parent

# Load configuration with priority:
# 1. Environment variables (TORAH_SYNC_*)
# 2. .secrets.toml (gitignored)
# 3. settings.toml (committed)
# 4. Defaults
settings = Dynaconf(
    envvar_prefix="TORAH_SYNC",
    settings_files=["settings.toml", ".secrets.toml"],
    root_path=PROJECT_ROOT,
    load_dotenv=True,
    environments=True,
    env_switcher="TORAH_SYNC_ENV",
    merge_enabled=True,
)


def get_cache_dir() -> Path:
    """Get cache directory path, creating it if needed."""
    cache_dir = Path(settings.cache_dir)
    cache_dir.mkdir(parents=True, exist_ok=True)
    return cache_dir


def get_output_dir() -> Path:
    """Get output directory path, creating it if needed."""
    output_dir = Path(settings.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def get_log_dir() -> Path:
    """Get log directory path, creating it if needed."""
    log_dir = Path(settings.get("log_dir", "output/logs"))
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir


def get_font_path() -> Path:
    """Get Hebrew font file path."""
    font_path = Path(settings.font_path)
    if not font_path.exists():
        raise FileNotFoundError(
            f"Hebrew font not found at {font_path}. "
            "Download with: curl -L 'https://github.com/google/fonts/raw/main/ofl/frankruhl/FrankRuhl-Regular.ttf' "
            f"-o {font_path}"
        )
    return font_path
