# Generated by Claude Code
"""Custom exception classes for Torah Sync application."""


class TorahSyncError(Exception):
    """Base exception for all Torah Sync errors."""

    pass


class HebrewTextUnavailableError(TorahSyncError):
    """Raised when Hebrew text source (e.g., Sefaria API) is unavailable.

    This error is raised when:
    - Network connection fails
    - API returns 5xx errors after retries
    - Rate limit is exceeded and cannot be resolved

    Per FR-002a: Fail processing with clear error message when API unavailable.
    """

    pass


class InvalidReferenceError(TorahSyncError):
    """Raised when a biblical reference is invalid.

    This error is raised when:
    - Book name is not recognized
    - Chapter or verse number is out of range
    - Reference format is malformed
    """

    pass


class InvalidFilenameError(TorahSyncError):
    """Raised when audio filename doesn't match expected naming convention.

    Expected format: פרשת {Parasha} - {Aliyah} - נוסח אשכנז.{ext}
    Valid extensions: .mp3, .mp4, .wav
    """

    pass


class AlignmentError(TorahSyncError):
    """Raised when forced alignment fails or produces low-quality results.

    This error is raised when:
    - Alignment confidence is below threshold (<0.90)
    - Timestamp validation fails (overlaps, gaps, non-monotonic)
    - Audio format is incompatible
    """

    pass


class VideoRenderError(TorahSyncError):
    """Raised when video rendering fails.

    This error is raised when:
    - Font file cannot be loaded
    - Video encoding fails
    - Output validation fails (resolution, codec, duration mismatch)
    """

    pass


class ConfigurationError(TorahSyncError):
    """Raised when configuration is invalid or missing.

    This error is raised when:
    - Required configuration keys are missing
    - Configuration values are invalid
    - Font file path is incorrect
    """

    pass
