# Generated by Claude Code
"""Filename parser utility to extract Parasha and Aliyah from Hebrew audio filenames."""

import re
from pathlib import Path

from .exceptions import InvalidFilenameError

# Expected filename pattern: פרשת {Parasha} - {Aliyah} - נוסח אשכנז.{ext}
FILENAME_PATTERN = re.compile(
    r"^פרשת\s+(?P<parasha>.+?)\s+-\s+(?P<aliyah>.+?)\s+-\s+נוסח\s+אשכנז\.(?P<ext>mp3|mp4|wav)$"
)

# Valid Aliyah names in Hebrew
VALID_ALIYAH_NAMES = {
    "ראשון",  # Rishon (First)
    "שני",  # Sheni (Second)
    "שלישי",  # Shlishi (Third)
    "רביעי",  # Revi'i (Fourth)
    "חמישי",  # Chamishi (Fifth)
    "שישי",  # Shishi (Sixth)
    "שביעי",  # Shevi'i (Seventh)
    "מפטיר",  # Maftir
    "הפטרה",  # Haftara
}


def parse_audio_filename(file_path: Path) -> tuple[str, str, str]:
    """Parse audio filename to extract Parasha, Aliyah, and extension.

    Args:
        file_path: Path to audio file

    Returns:
        Tuple of (parasha_name, aliyah_name, extension)

    Raises:
        InvalidFilenameError: If filename doesn't match expected pattern

    Example:
        >>> parse_audio_filename(Path("פרשת האזינו - ראשון - נוסח אשכנז.mp4"))
        ('האזינו', 'ראשון', 'mp4')
    """
    filename = file_path.name
    match = FILENAME_PATTERN.match(filename)

    if not match:
        raise InvalidFilenameError(
            f"Invalid filename format: {filename}. "
            f"Expected: פרשת {{Parasha}} - {{Aliyah}} - נוסח אשכנז.{{ext}} "
            f"(valid extensions: mp3, mp4, wav)"
        )

    parasha_name = match.group("parasha").strip()
    aliyah_name = match.group("aliyah").strip()
    extension = match.group("ext")

    # Validate Aliyah name
    if aliyah_name not in VALID_ALIYAH_NAMES:
        raise InvalidFilenameError(
            f"Invalid Aliyah name: {aliyah_name}. "
            f"Must be one of: {', '.join(sorted(VALID_ALIYAH_NAMES))}"
        )

    return parasha_name, aliyah_name, extension


def validate_audio_file(file_path: Path) -> None:
    """Validate audio file exists and has valid filename.

    Args:
        file_path: Path to audio file

    Raises:
        FileNotFoundError: If file doesn't exist
        InvalidFilenameError: If filename format is invalid
    """
    if not file_path.exists():
        raise FileNotFoundError(f"Audio file not found: {file_path}")

    if not file_path.is_file():
        raise InvalidFilenameError(f"Path is not a file: {file_path}")

    # Parse filename to validate format
    parse_audio_filename(file_path)
