# Generated by Claude Code
"""Hebrew text validator to verify Unicode Nikkud and T'amim presence."""


def has_nikkud(text: str) -> bool:
    """Check if text contains Hebrew vowel points (Nikkud).

    Nikkud Unicode range: U+05B0–U+05BD

    Args:
        text: Hebrew text to check

    Returns:
        True if text contains at least one Nikkud character
    """
    return any("\u05B0" <= char <= "\u05BD" for char in text)


def has_teamim(text: str) -> bool:
    """Check if text contains Hebrew cantillation marks (T'amim).

    T'amim Unicode range: U+0591–U+05AF

    Args:
        text: Hebrew text to check

    Returns:
        True if text contains at least one T'amim character
    """
    return any("\u0591" <= char <= "\u05AF" for char in text)


def has_hebrew(text: str) -> bool:
    """Check if text contains Hebrew characters.

    Hebrew Unicode range: U+0590–U+05FF

    Args:
        text: Text to check

    Returns:
        True if text contains at least one Hebrew character
    """
    return any("\u0590" <= char <= "\u05FF" for char in text)


def validate_hebrew_text_complete(text: str) -> tuple[bool, list[str]]:
    """Validate Hebrew text has all required components.

    Required:
    - Hebrew characters (U+0590-U+05FF)
    - Nikkud (vowel points, U+05B0-U+05BD)
    - T'amim (cantillation marks, U+0591-U+05AF)

    Args:
        text: Hebrew text to validate

    Returns:
        Tuple of (is_valid, list of missing components)

    Example:
        >>> text = "הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם"
        >>> is_valid, missing = validate_hebrew_text_complete(text)
        >>> is_valid
        True
        >>> missing
        []
    """
    missing = []

    if not has_hebrew(text):
        missing.append("Hebrew characters (U+0590-U+05FF)")

    if not has_nikkud(text):
        missing.append("Nikkud/vowel points (U+05B0-U+05BD)")

    if not has_teamim(text):
        missing.append("T'amim/cantillation marks (U+0591-U+05AF)")

    return len(missing) == 0, missing


def validate_sefaria_response(response: dict) -> bool:
    """Validate Sefaria API response has required Hebrew text with diacritics.

    Args:
        response: Sefaria API response dictionary

    Returns:
        True if response contains valid Hebrew text with Nikkud and T'amim

    Example:
        >>> response = {"he": ["הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם"]}
        >>> validate_sefaria_response(response)
        True
    """
    if "he" not in response or not response["he"]:
        return False

    hebrew_text = response["he"][0] if isinstance(response["he"], list) else response["he"]

    if not isinstance(hebrew_text, str):
        return False

    is_valid, _ = validate_hebrew_text_complete(hebrew_text)
    return is_valid
