# Generated by Claude Opus 4.6
"""Tests for PlaylistRepository."""

import pytest

from src.models.playlist import Playlist
from src.repositories.playlist_repo import PlaylistRepository


@pytest.fixture
def repo(duckdb_conn):
    return PlaylistRepository()


def test_insert_and_get_by_id(repo):
    """Insert a playlist and retrieve it by id."""
    p = Playlist(name="האזינו", book="Deuteronomy", chapter_start=32, verse_start=1, chapter_end=32, verse_end=52)
    inserted = repo.insert(p)

    assert inserted.id is not None
    fetched = repo.get_by_id(inserted.id)
    assert fetched is not None
    assert fetched.name == "האזינו"
    assert fetched.book == "Deuteronomy"


def test_get_by_name(repo):
    """Retrieve a playlist by parasha name."""
    repo.insert(Playlist(name="בראשית", book="Genesis", chapter_start=1, verse_start=1, chapter_end=6, verse_end=8))

    fetched = repo.get_by_name("בראשית")
    assert fetched is not None
    assert fetched.book == "Genesis"


def test_get_by_name_returns_none_for_missing(repo):
    """Return None when playlist name not found."""
    assert repo.get_by_name("nonexistent") is None


def test_unique_name_constraint(repo):
    """Inserting duplicate name raises an error."""
    repo.insert(Playlist(name="האזינו", book="Deuteronomy", chapter_start=32, verse_start=1, chapter_end=32, verse_end=52))

    with pytest.raises(Exception, match="Constraint"):
        repo.insert(Playlist(name="האזינו", book="Deuteronomy", chapter_start=32, verse_start=1, chapter_end=32, verse_end=52))


def test_list_all(repo):
    """List all playlists."""
    repo.insert(Playlist(name="האזינו", book="Deuteronomy", chapter_start=32, verse_start=1, chapter_end=32, verse_end=52))
    repo.insert(Playlist(name="בראשית", book="Genesis", chapter_start=1, verse_start=1, chapter_end=6, verse_end=8))

    playlists = repo.list_all()
    assert len(playlists) == 2
