# Generated by Claude Code
# Edited by Claude Opus 4.6 (refactored to AeneasAligner implementing Protocol)
"""AeneasAligner — DTW-based forced alignment using the aeneas library."""

from datetime import datetime
from pathlib import Path
from typing import Any

from src.lib.config import settings
from src.lib.exceptions import AlignmentError
from src.lib.logging import get_logger
from src.models.alignment_run import AlignmentRun
from src.models.pasuk_alignment import PasukAlignment

logger = get_logger(__name__)

# NOTE: aeneas requires manual installation:
# uv pip install numpy && uv pip install aeneas
try:
    from aeneas.executetask import ExecuteTask
    from aeneas.task import Task
    from aeneas.textfile import TextFile
    from aeneas.textfile import TextFileFormat

    AENEAS_AVAILABLE = True
except ImportError:
    AENEAS_AVAILABLE = False
    logger.warning(
        "aeneas not available - install with: uv pip install numpy && uv pip install aeneas"
    )


class AeneasAligner:
    """DTW-based forced alignment using the aeneas library.

    Implements the AlignmentEngine protocol.
    """

    MODEL_VERSION = "aeneas-dtw-1.0"

    def __init__(self, min_confidence_threshold: float | None = None) -> None:
        self.min_confidence_threshold = min_confidence_threshold or settings.get(
            "alignment.min_confidence_threshold", 0.90
        )

        if not AENEAS_AVAILABLE:
            logger.error("aeneas library is not installed - alignment will fail")

        logger.debug(
            f"Initialized AeneasAligner",
            min_confidence_threshold=self.min_confidence_threshold,
            aeneas_available=AENEAS_AVAILABLE,
        )

    def get_model_version(self) -> str:
        return self.MODEL_VERSION

    def align(
        self,
        audio_file: Path,
        verses: list[tuple[str, str]],
        alya_audio_id: int,
    ) -> tuple[AlignmentRun, list[PasukAlignment]]:
        """Perform forced alignment on audio and verses.

        Args:
            audio_file: Path to audio file (WAV format preferred)
            verses: List of (reference, hebrew_text) tuples
            alya_audio_id: FK to alya_audio.id

        Returns:
            Tuple of (AlignmentRun, list of PasukAlignment)

        Raises:
            AlignmentError: If alignment fails or confidence too low
        """
        if not AENEAS_AVAILABLE:
            raise AlignmentError(
                "aeneas library not installed. Install with: uv pip install numpy && uv pip install aeneas"
            )

        logger.info(
            f"Starting forced alignment",
            audio_file=str(audio_file),
            verse_count=len(verses),
        )

        # Prepare text for alignment
        sync_map_text = self._prepare_text_for_alignment(verses)

        # Run alignment
        alignment_data = self._run_alignment(audio_file, sync_map_text)

        # Calculate quality score
        confidence = self._calculate_confidence(alignment_data)
        logger.info(f"Alignment complete {confidence=}")

        # Parse and validate
        pasuk_alignments = self._parse_alignment_results(alignment_data, verses, confidence)
        self._validate_pasuk_alignments(pasuk_alignments)

        # Create alignment run
        alignment_run = AlignmentRun(
            alya_audio_id=alya_audio_id,
            alignment_quality=confidence,
            verse_count=len(pasuk_alignments),
            generated_at=datetime.now(),
        )

        logger.info(
            f"AlignmentRun created successfully",
            verse_count=len(pasuk_alignments),
        )

        return alignment_run, pasuk_alignments

    def _prepare_text_for_alignment(self, verses: list[tuple[str, str]]) -> str:
        """Format verses for aeneas input.

        Args:
            verses: List of (reference, hebrew_text) tuples

        Returns:
            Formatted text string for aeneas
        """
        # aeneas expects plain text with one fragment per line
        lines = []
        for ref, hebrew_text in verses:
            # Clean text (remove extra whitespace)
            cleaned = " ".join(hebrew_text.split())
            lines.append(cleaned)

        return "\n".join(lines)

    def _run_alignment(self, audio_file: Path, sync_map_text: str) -> list[dict[str, Any]]:
        """Run aeneas forced alignment.

        Args:
            audio_file: Path to audio file
            sync_map_text: Formatted text for alignment

        Returns:
            Alignment results as list of fragments

        Raises:
            AlignmentError: If alignment fails
        """
        try:
            # Create temporary text file for aeneas
            import tempfile

            # Create temp file and keep it until after alignment
            text_file = tempfile.NamedTemporaryFile(
                mode="w", suffix=".txt", delete=False, encoding="utf-8"
            )
            text_file.write(sync_map_text)
            text_file.flush()  # Ensure content is written to disk
            text_file_path = text_file.name
            text_file.close()  # Close but don't delete yet

            try:
                # Verify temp file exists and has content
                temp_path = Path(text_file_path)
                if not temp_path.exists():
                    raise AlignmentError(f"Temp text file does not exist: {text_file_path}")

                file_size = temp_path.stat().st_size
                logger.debug(f"{text_file_path=}, {file_size=} bytes")

                # Configure aeneas task
                # NOTE: espeak doesn't support Hebrew voices, so we use English as fallback
                # The alignment still works because DTW compares audio features, not phonemes
                # The TTS is only used to generate reference MFCC features
                config_string = "task_language=eng|is_text_type=plain|os_task_file_format=json|tts=espeak"

                task = Task(config_string=config_string)
                task.audio_file_path_absolute = str(audio_file)
                task.text_file_path_absolute = str(text_file_path)

                # Create TextFile object explicitly
                # Use English for TTS even though text is Hebrew (alignment will still work)
                text_file_obj = TextFile(
                    file_path=str(text_file_path),
                    file_format=TextFileFormat.PLAIN
                )
                text_file_obj.set_language("eng")
                task.text_file = text_file_obj

                # Set sync map output path
                task.sync_map_file_path_absolute = str(text_file_path).replace('.txt', '_syncmap.json')

                # Execute alignment
                logger.debug(f"{audio_file=}")
                logger.debug(f"{task.text_file_path_absolute=}")
                logger.debug(f"{task.audio_file_path_absolute=}")
                ExecuteTask(task).execute()

                # Get sync map
                sync_map = task.sync_map
            finally:
                # Clean up temp file
                Path(text_file_path).unlink(missing_ok=True)

            # Convert sync map to list of dicts
            fragments = []
            for fragment in sync_map.fragments:
                fragments.append(
                    {
                        "text": fragment.text,
                        "begin": float(fragment.begin),
                        "end": float(fragment.end),
                    }
                )

            logger.debug(f"Alignment produced {len(fragments)} fragments")
            return fragments

        except Exception as e:
            import traceback
            logger.error(f"Alignment exception details: {traceback.format_exc()}")
            raise AlignmentError(f"Forced alignment failed: {e}") from e

    def _calculate_confidence(self, alignment_data: list[dict[str, Any]]) -> float:
        """Calculate alignment quality score.

        Args:
            alignment_data: Alignment results from aeneas

        Returns:
            Confidence score (0.0-1.0)
        """
        # Simple heuristic: check for reasonable durations and no gaps
        if not alignment_data:
            return 0.0

        total_duration = 0.0
        gap_count = 0
        max_gap = 0.0

        for i, fragment in enumerate(alignment_data):
            duration = fragment["end"] - fragment["begin"]
            total_duration += duration

            # Check for gaps
            if i > 0:
                gap = fragment["begin"] - alignment_data[i - 1]["end"]
                if gap > 0.5:  # Gap > 0.5 seconds
                    gap_count += 1
                    max_gap = max(max_gap, gap)

        # Calculate confidence based on gaps
        if gap_count == 0:
            confidence = 1.0
        elif max_gap > 5.0:
            confidence = 0.8
        else:
            confidence = max(0.85, 1.0 - (gap_count * 0.02))

        return confidence

    def _parse_alignment_results(
        self,
        alignment_data: list[dict[str, Any]],
        verses: list[tuple[str, str]],
        confidence: float,
    ) -> list[PasukAlignment]:
        """Parse aeneas results into PasukAlignment objects.

        Args:
            alignment_data: Alignment results
            verses: Original verse list
            confidence: Overall confidence score

        Returns:
            List of PasukAlignment objects
        """
        # Edited by Claude Opus 4.6
        pasuk_alignments = []
        prev_end_time = 0.0

        logger.info(
            f"Alignment fragment analysis: {len(alignment_data)} fragments for {len(verses)} text entries"
        )

        for i, fragment in enumerate(alignment_data):
            if i >= len(verses):
                logger.warning(f"More fragments ({len(alignment_data)}) than text entries ({len(verses)}) - truncating")
                break

            reference, hebrew_text = verses[i]

            start_time = fragment["begin"]
            end_time = fragment["end"]

            # Ensure monotonic ordering
            if start_time < prev_end_time:
                logger.warning(
                    f"Non-monotonic timestamp for {reference}: {start_time}s < {prev_end_time}s, "
                    f"adjusting to {prev_end_time}s"
                )
                start_time = prev_end_time

            # Ensure end_time > start_time
            if end_time <= start_time:
                logger.warning(
                    f"Degenerate timestamp for {reference}: {start_time}s-{end_time}s, "
                    f"adding minimum duration"
                )
                end_time = start_time + 0.1

            pasuk_alignments.append(
                PasukAlignment(
                    alignment_run_id=0,  # set after DB insert
                    reference=reference,
                    hebrew_text=hebrew_text,
                    verse_order=i + 1,
                    start_time=start_time,
                    end_time=end_time,
                    confidence=confidence,
                )
            )

            prev_end_time = end_time

        return pasuk_alignments

    def _validate_pasuk_alignments(self, alignments: list[PasukAlignment]) -> None:
        """Validate alignment quality.

        Raises:
            AlignmentError: If validation fails
        """
        if not alignments:
            raise AlignmentError("No timestamps generated")

        for i in range(len(alignments) - 1):
            current = alignments[i]
            next_verse = alignments[i + 1]

            if current.start_time >= next_verse.start_time:
                raise AlignmentError(
                    f"Timestamps not monotonically increasing: "
                    f"{current.reference} ({current.start_time}) >= "
                    f"{next_verse.reference} ({next_verse.start_time})"
                )

            if current.end_time > next_verse.start_time:
                raise AlignmentError(
                    f"Timestamp overlap: "
                    f"{current.reference} end ({current.end_time}) > "
                    f"{next_verse.reference} start ({next_verse.start_time})"
                )

    def _get_audio_duration(self, audio_file: Path) -> float:
        """Get audio file duration.

        Args:
            audio_file: Path to audio file

        Returns:
            Duration in seconds
        """
        from pydub import AudioSegment

        audio = AudioSegment.from_file(audio_file)
        return len(audio) / 1000.0  # pydub uses milliseconds

