# Generated by Claude Opus 4.6
"""Alignment quality evaluator using ground truth from manual corrections."""

from dataclasses import dataclass, field

from src.lib.logging import get_logger
from src.models.pasuk_alignment import PasukAlignment
from src.repositories.pasuk_alignment_repo import PasukAlignmentRepository

logger = get_logger(__name__)


@dataclass
class AlignmentMetrics:
    """Evaluation metrics comparing predicted vs corrected timestamps."""

    total_verses: int = 0
    mae_start: float = 0.0
    mae_end: float = 0.0
    mean_bias_start: float = 0.0
    mean_bias_end: float = 0.0
    max_error_start: float = 0.0
    max_error_end: float = 0.0
    within_200ms: float = 0.0
    within_500ms: float = 0.0
    within_1s: float = 0.0
    worst_verse_ref: str = ""
    per_position_mae: dict[int, float] = field(default_factory=dict)
    per_run_mae: dict[int, float] = field(default_factory=dict)


def evaluate_alignment(
    corrected: list[PasukAlignment] | None = None,
) -> AlignmentMetrics:
    """Evaluate alignment accuracy using manually corrected ground truth.

    Args:
        corrected: Pre-fetched corrected alignments; if None, queries DuckDB.

    Returns:
        AlignmentMetrics with computed accuracy statistics.
    """
    if corrected is None:
        corrected = PasukAlignmentRepository().list_corrected()

    if not corrected:
        logger.warning("No corrected alignments found for evaluation")
        return AlignmentMetrics()

    start_deltas: list[float] = []
    end_deltas: list[float] = []
    abs_errors: list[float] = []
    position_errors: dict[int, list[float]] = {}
    run_errors: dict[int, list[float]] = {}
    worst_error = 0.0
    worst_ref = ""

    for pa in corrected:
        s_delta = pa.start_time - pa.original_start_time
        e_delta = pa.end_time - pa.original_end_time

        start_deltas.append(s_delta)
        end_deltas.append(e_delta)

        # Max absolute error across both boundaries for this verse
        verse_max = max(abs(s_delta), abs(e_delta))
        abs_errors.append(verse_max)

        if verse_max > worst_error:
            worst_error = verse_max
            worst_ref = pa.reference

        # Per-position tracking
        position_errors.setdefault(pa.verse_order, []).append(verse_max)

        # Per-run tracking
        run_errors.setdefault(pa.alignment_run_id, []).append(verse_max)

    n = len(corrected)
    mae_start = sum(abs(d) for d in start_deltas) / n
    mae_end = sum(abs(d) for d in end_deltas) / n
    mean_bias_start = sum(start_deltas) / n
    mean_bias_end = sum(end_deltas) / n

    within_200ms = sum(1 for e in abs_errors if e <= 0.2) / n
    within_500ms = sum(1 for e in abs_errors if e <= 0.5) / n
    within_1s = sum(1 for e in abs_errors if e <= 1.0) / n

    per_position_mae = {
        pos: sum(errs) / len(errs) for pos, errs in sorted(position_errors.items())
    }
    per_run_mae = {
        run_id: sum(errs) / len(errs) for run_id, errs in sorted(run_errors.items())
    }

    metrics = AlignmentMetrics(
        total_verses=n,
        mae_start=mae_start,
        mae_end=mae_end,
        mean_bias_start=mean_bias_start,
        mean_bias_end=mean_bias_end,
        max_error_start=max(abs(d) for d in start_deltas),
        max_error_end=max(abs(d) for d in end_deltas),
        within_200ms=within_200ms,
        within_500ms=within_500ms,
        within_1s=within_1s,
        worst_verse_ref=worst_ref,
        per_position_mae=per_position_mae,
        per_run_mae=per_run_mae,
    )

    logger.info(
        f"Evaluation complete: {n=}, {mae_start=:.3f}s, {mae_end=:.3f}s, "
        f"{within_500ms=:.1%}"
    )
    return metrics


def format_metrics_report(metrics: AlignmentMetrics) -> str:
    """Format metrics as a human-readable report string."""
    if metrics.total_verses == 0:
        return "No corrected alignments found. Run manual correction first."

    lines = [
        "Alignment Evaluation Report",
        "=" * 40,
        f"Total corrected verses: {metrics.total_verses}",
        "",
        "Overall Accuracy:",
        f"  MAE start_time:  {metrics.mae_start:.3f}s",
        f"  MAE end_time:    {metrics.mae_end:.3f}s",
        f"  Max error start: {metrics.max_error_start:.3f}s",
        f"  Max error end:   {metrics.max_error_end:.3f}s",
        f"  Worst verse:     {metrics.worst_verse_ref}",
        "",
        "Bias (positive = predicted too late):",
        f"  Mean bias start: {metrics.mean_bias_start:+.3f}s",
        f"  Mean bias end:   {metrics.mean_bias_end:+.3f}s",
        "",
        "Tolerance:",
        f"  Within 200ms: {metrics.within_200ms:.1%}",
        f"  Within 500ms: {metrics.within_500ms:.1%}",
        f"  Within 1.0s:  {metrics.within_1s:.1%}",
    ]

    if metrics.per_position_mae:
        lines.append("")
        lines.append("MAE by verse position:")
        for pos, mae in metrics.per_position_mae.items():
            lines.append(f"  Position {pos:2d}: {mae:.3f}s")

    if metrics.per_run_mae:
        lines.append("")
        lines.append("MAE by alignment run:")
        for run_id, mae in metrics.per_run_mae.items():
            lines.append(f"  Run {run_id}: {mae:.3f}s")

    return "\n".join(lines)
