# Generated by Claude Opus 4.6
"""AlignmentEngine protocol for pluggable alignment backends."""

from pathlib import Path
from typing import Protocol

from src.models.alignment_run import AlignmentRun
from src.models.pasuk_alignment import PasukAlignment


class AlignmentEngine(Protocol):
    """Protocol for forced alignment engines.

    Implementations: AeneasAligner, WhisperXAligner (future), CustomAligner (future).
    """

    def align(
        self,
        audio_file: Path,
        verses: list[tuple[str, str]],
        alya_audio_id: int,
    ) -> tuple[AlignmentRun, list[PasukAlignment]]:
        """Perform forced alignment on audio and verses.

        Args:
            audio_file: Path to audio file (WAV format preferred)
            verses: List of (reference, hebrew_text) tuples
            alya_audio_id: FK to alya_audio.id

        Returns:
            Tuple of (AlignmentRun metadata, per-verse PasukAlignments)
        """
        ...

    def get_model_version(self) -> str:
        """Return the model/engine version string."""
        ...
