# Generated by Claude Opus 4.6
"""Phase 1 pipeline: audio + text alignment -> DuckDB.

Decoupled from video rendering. Produces alignment data only.
"""

from pathlib import Path

from pydub import AudioSegment

from src.lib.exceptions import InvalidReferenceError, TorahSyncError
from src.lib.filename_parser import parse_audio_filename
from src.lib.logging import get_logger
from src.models.alya import Alya, AlyaState
from src.models.alignment_run import AlignmentRun
from src.models.pasuk_alignment import PasukAlignment
from src.models.playlist import Playlist
from src.repositories.alignment_repo import AlignmentRunRepository
from src.repositories.alya_audio_repo import AlyaAudioRepository
from src.repositories.alya_repo import AlyaRepository
from src.repositories.pasuk_alignment_repo import PasukAlignmentRepository
from src.repositories.playlist_repo import PlaylistRepository
from src.services.alignment.aeneas_aligner import AeneasAligner
from src.services.alignment.protocol import AlignmentEngine
from src.services.audio.converter import AudioConverter
from src.services.audio.reader import AudioFileReader
from src.services.text import CachedSefariaClient
from src.services.text.parasha_fetcher import ParashaTextFetcher

logger = get_logger(__name__)


class AlignmentPipeline:
    """Phase 1: align audio + text, persist to DuckDB.

    Stages:
    1. Parse filename -> find/create playlist + alya in DuckDB
    2. Read audio metadata -> alya_audio row
    3. Fetch Hebrew text from Sefaria
    4. Convert audio to 16kHz WAV
    5. Run alignment engine
    6. Write pasuk_alignments + alignment_run to DuckDB
    """

    def __init__(
        self,
        aligner: AlignmentEngine | None = None,
    ) -> None:
        self.audio_reader = AudioFileReader()
        self.text_client = CachedSefariaClient()
        self.parasha_fetcher = ParashaTextFetcher()
        self.aligner = aligner or AeneasAligner()

        self.playlist_repo = PlaylistRepository()
        self.alya_repo = AlyaRepository()
        self.alya_audio_repo = AlyaAudioRepository()
        self.alignment_run_repo = AlignmentRunRepository()
        self.pasuk_alignment_repo = PasukAlignmentRepository()

        logger.debug("Initialized AlignmentPipeline")

    def align(self, audio_file: Path) -> tuple[AlignmentRun, list[PasukAlignment]]:
        """Run full alignment pipeline on an audio file.

        Args:
            audio_file: Path to audio file (e.g. "פרשת האזינו - ראשון - נוסח אשכנז.mp4")

        Returns:
            Tuple of (AlignmentRun, list of PasukAlignment) persisted to DuckDB
        """
        logger.info(f"Starting alignment pipeline for {audio_file.name}")

        try:
            # Stage 1: Parse filename -> ensure playlist + alya exist
            parasha_name, aliyah_name, ext = parse_audio_filename(audio_file)
            logger.info(f"Parsed filename {parasha_name=}, {aliyah_name=}")

            playlist = self._ensure_playlist(parasha_name)
            alya = self._ensure_alya(playlist, aliyah_name)

            # Stage 2: Read audio metadata -> alya_audio
            alya_audio = self._ensure_alya_audio(alya, audio_file)
            self.alya_repo.update_state(alya.id, AlyaState.ALIGNING)

            # Stage 3: Fetch Hebrew text
            verses = self._fetch_verses(parasha_name, aliyah_name)

            # Stage 4: Convert audio + run alignment
            with AudioConverter() as converter:
                audio_segment = AudioSegment.from_file(audio_file)
                wav_path = converter.convert_to_alignment_format(audio_segment)
                logger.info(f"Audio converted {wav_path=}")

                alignment_run, pasuk_alignments = self.aligner.align(
                    wav_path, verses, alya_audio.id
                )

            # Stage 5: Persist to DuckDB
            alignment_run = self.alignment_run_repo.insert(alignment_run)

            for pa in pasuk_alignments:
                pa.alignment_run_id = alignment_run.id
            pasuk_alignments = self.pasuk_alignment_repo.insert_batch(pasuk_alignments)

            self.alya_repo.update_state(alya.id, AlyaState.ALIGNED)

            logger.info(
                f"Alignment pipeline complete",
                alignment_run_id=alignment_run.id,
                verse_count=len(pasuk_alignments),
                quality=alignment_run.alignment_quality,
            )

            return alignment_run, pasuk_alignments

        except Exception as e:
            logger.error(f"Alignment pipeline failed: {e}", exc_info=True)
            raise TorahSyncError(f"Alignment failed: {e}") from e

    # Edited by Claude Opus 4.6 — align by alya_id for megillot support
    def align_by_alya(self, alya_id: int) -> tuple[AlignmentRun, list[PasukAlignment]]:
        """Run alignment on an already-ingested alya (playlist, audio, ranges in DB).

        Args:
            alya_id: ID of the alya to align.

        Returns:
            Tuple of (AlignmentRun, list of PasukAlignment) persisted to DuckDB.
        """
        alya = self.alya_repo.get_by_id(alya_id)
        if alya is None:
            raise TorahSyncError(f"Alya {alya_id=} not found")

        playlist = self.playlist_repo.get_by_id(alya.playlist_id)
        alya_audio = self.alya_audio_repo.get_by_alya(alya.id)
        if alya_audio is None:
            raise TorahSyncError(f"No audio found for {alya_id=}")

        audio_file = Path(alya_audio.file_path)
        if not audio_file.exists():
            raise TorahSyncError(f"Audio file not found: {audio_file}")

        logger.info(f"Aligning by alya {alya_id=}, {playlist.name=}, {alya.name=}")
        self.alya_repo.update_state(alya.id, AlyaState.ALIGNING)

        # Fetch Hebrew text using playlist name + alya name as keys
        verses = self._fetch_verses(playlist.name, alya.name)

        # Convert audio + run alignment
        with AudioConverter() as converter:
            audio_segment = AudioSegment.from_file(audio_file)
            wav_path = converter.convert_to_alignment_format(audio_segment)
            logger.info(f"Audio converted {wav_path=}")

            alignment_run, pasuk_alignments = self.aligner.align(
                wav_path, verses, alya_audio.id
            )

        # Persist to DuckDB
        alignment_run = self.alignment_run_repo.insert(alignment_run)
        for pa in pasuk_alignments:
            pa.alignment_run_id = alignment_run.id
        pasuk_alignments = self.pasuk_alignment_repo.insert_batch(pasuk_alignments)
        self.alya_repo.update_state(alya.id, AlyaState.ALIGNED)

        logger.info(
            f"Alignment complete",
            alignment_run_id=alignment_run.id,
            verse_count=len(pasuk_alignments),
            quality=alignment_run.alignment_quality,
        )
        return alignment_run, pasuk_alignments

    # Edited by Claude Opus 4.6 — align entire playlist
    def align_playlist(
        self, playlist_name: str,
    ) -> list[tuple[AlignmentRun, list[PasukAlignment]]]:
        """Align all alyot of a playlist (parasha or megillah).

        Args:
            playlist_name: Hebrew name of the playlist (e.g., "שיר השירים").

        Returns:
            List of (AlignmentRun, list[PasukAlignment]) per alya.
        """
        playlist = self.playlist_repo.get_by_name(playlist_name)
        if playlist is None:
            raise TorahSyncError(f"Playlist '{playlist_name}' not found")

        alyot = self.alya_repo.list_by_playlist(playlist.id)
        if not alyot:
            raise TorahSyncError(f"No alyot found for '{playlist_name}'")

        results = []
        for alya in alyot:
            audio = self.alya_audio_repo.get_by_alya(alya.id)
            if audio is None:
                logger.warning(f"Skipping {alya.name}: no audio")
                continue
            result = self.align_by_alya(alya.id)
            results.append(result)

        return results

    def _ensure_playlist(self, parasha_name: str) -> Playlist:
        """Find or create a playlist for this parasha."""
        existing = self.playlist_repo.get_by_name(parasha_name)
        if existing:
            return existing

        playlist = Playlist(
            name=parasha_name, book="Unknown",
            chapter_start=1, verse_start=1, chapter_end=1, verse_end=1,
        )
        return self.playlist_repo.insert(playlist)

    def _ensure_alya(self, playlist: Playlist, aliyah_name: str) -> Alya:
        """Find or create an alya for this playlist/aliyah combo."""
        # Edited by Claude Opus 4.6
        from src.models.alya import VALID_ALYA_NAMES

        alyot = self.alya_repo.list_by_playlist(playlist.id)
        for a in alyot:
            if a.name == aliyah_name:
                return a

        # Determine order_num from the name
        ordered_names = ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שביעי", "מפטיר", "הפטרה"]
        order_num = ordered_names.index(aliyah_name) + 1 if aliyah_name in ordered_names else 1

        alya = Alya(playlist_id=playlist.id, name=aliyah_name, order_num=order_num)
        return self.alya_repo.insert(alya)

    def _ensure_alya_audio(self, alya: Alya, audio_file: Path):
        # Edited by Claude Opus 4.6 (update file_path if stale)
        """Find or create alya_audio for this alya."""
        existing = self.alya_audio_repo.get_by_alya(alya.id)
        if existing:
            resolved = str(audio_file.resolve())
            if existing.file_path != resolved:
                logger.info(f"Updating stale audio path {existing.file_path=} -> {resolved=}")
                existing.file_path = resolved
                self.alya_audio_repo.update(existing)
            return existing

        alya_audio = self.audio_reader.read(audio_file, alya.id)
        return self.alya_audio_repo.insert(alya_audio)

    def _fetch_verses(self, parasha_name: str, aliyah_name: str) -> list[tuple[str, str]]:
        """Fetch Hebrew text with intro placeholder."""
        try:
            fetched = self.parasha_fetcher.fetch_aliyah_text(parasha_name, aliyah_name)
            verses = [
                (f"{parasha_name} - {aliyah_name} (Intro)", f"פרשת {parasha_name} - {aliyah_name}")
            ]
            verses.extend(fetched)
            logger.info(f"Fetched verses {len(fetched)=}, total_with_intro={len(verses)}")
            return verses

        except InvalidReferenceError as e:
            logger.warning(f"Aliyah not in config, using placeholder: {e}")
            return [
                (f"{parasha_name} - {aliyah_name} (Intro)", f"פרשת {parasha_name} - {aliyah_name}"),
                ("Placeholder", "טקסט עברי לדוגמה"),
            ]
