# Generated by Claude Code
"""ProcessingPipeline for orchestrating the complete audio-visual synchronization workflow."""

from pathlib import Path

from pydub import AudioSegment

from src.lib.config import get_cache_dir, get_output_dir
from src.lib.exceptions import TorahSyncError
from src.lib.filename_parser import parse_audio_filename
from src.lib.logging import get_logger
from src.models.aliyah import AliyahState
from src.models.video import SynchronizedVideo
from src.services.alignment.engine import AlignmentEngine
from src.services.audio.converter import AudioConverter
from src.services.audio.reader import AudioFileReader
from src.services.text import CachedSefariaClient
from src.services.video.renderer import VideoRenderer

logger = get_logger(__name__)


class ProcessingPipeline:
    """Pipeline orchestrator for Torah audio-visual synchronization.

    Coordinates all processing stages:
    1. Parse filename → extract Parasha/Aliyah
    2. Load and convert audio
    3. Retrieve Hebrew text from Sefaria
    4. Perform forced alignment
    5. Render synchronized video
    """

    def __init__(self) -> None:
        """Initialize processing pipeline with all service components."""
        self.audio_reader = AudioFileReader()
        self.text_client = CachedSefariaClient()
        self.alignment_engine = AlignmentEngine()
        self.video_renderer = VideoRenderer()

        logger.debug("Initialized ProcessingPipeline")

    def process_single_aliyah(
        self,
        audio_file: Path,
        output_dir: Path | None = None,
    ) -> SynchronizedVideo:
        """Process a single Aliyah audio file to generate synchronized video.

        Args:
            audio_file: Path to audio file
            output_dir: Optional output directory (default from config)

        Returns:
            SynchronizedVideo model with output path and metadata

        Raises:
            TorahSyncError: If any processing stage fails

        Example:
            >>> pipeline = ProcessingPipeline()
            >>> video = pipeline.process_single_aliyah(Path("פרשת האזינו - ראשון - נוסח אשכנז.mp4"))
            >>> logger.info(f"Video created: {video.file_path}")
        """
        logger.info(f"Starting pipeline for {audio_file.name}")

        current_state = AliyahState.PENDING

        try:
            # Stage 1: Parse filename
            logger.info("Stage 1: Parsing filename")
            parasha_name, aliyah_name, _ = parse_audio_filename(audio_file)
            logger.info(f"Parsed filename", parasha_name=parasha_name, aliyah_name=aliyah_name)

            # Stage 2: Load audio and extract metadata
            logger.info("Stage 2: Loading audio")
            audio_source = self.audio_reader.read(audio_file, parasha_name, aliyah_name)
            logger.info(
                f"Audio loaded",
                duration_seconds=audio_source.duration_seconds,
                sample_rate=audio_source.sample_rate,
            )

            # Stage 3: Convert audio to alignment format
            logger.info("Stage 3: Converting audio to alignment format")
            with AudioConverter() as converter:
                audio_segment = AudioSegment.from_file(audio_file)
                wav_path = converter.convert_to_alignment_format(audio_segment)
                logger.info(f"Audio converted", wav_path=str(wav_path))

                # Stage 4: Retrieve Hebrew text
                # Note: This is simplified - real implementation would need book/chapter/verse info
                # For demo, we'll use placeholder
                logger.info("Stage 4: Retrieving Hebrew text")
                current_state = AliyahState.ALIGNING

                # TODO: Implement proper verse retrieval based on Parasha/Aliyah mapping
                # For now, use example from Haazinu
                verses = [
                    ("Deuteronomy 32:1", "הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם וַאֲדַבֵּ֑רָה וְתִשְׁמַ֥ע הָאָ֖רֶץ אִמְרֵי־פִֽי׃"),
                    # Add more verses...
                ]

                # Determine verse range based on aliyah
                verse_range = None
                if parasha_name == "האזינו":
                    if aliyah_name == "ראשון":
                        verse_range = (1, 7)  # Verses 1-6
                    elif aliyah_name == "שני":
                        verse_range = (7, 13)  # Verses 7-12
                    elif aliyah_name == "שלישי":
                        verse_range = (13, 19)  # Verses 13-18
                    elif aliyah_name == "רביעי":
                        verse_range = (19, 29)  # Verses 19-28
                    elif aliyah_name == "חמישי":
                        verse_range = (29, 40)  # Verses 29-39
                    elif aliyah_name == "שישי":
                        verse_range = (40, 44)  # Verses 40-43
                    elif aliyah_name == "שביעי":
                        verse_range = (44, 53)  # Verses 44-52

                if verse_range:
                    # Fetch verses from Sefaria
                    try:
                        verses = []
                        # Add intro placeholder - aeneas often detects an intro before first verse
                        verses.append((f"{parasha_name} - {aliyah_name} (Intro)", f"פרשת {parasha_name} - {aliyah_name}"))

                        for verse_num in range(verse_range[0], verse_range[1]):
                            hebrew_text = self.text_client.get_verse("Deuteronomy", 32, verse_num)
                            ref = f"Deuteronomy 32:{verse_num}"
                            verses.append((ref, hebrew_text))
                        logger.info(f"Retrieved {len(verses)} verses from Sefaria (+ intro)")
                    except Exception as e:
                        logger.warning(f"Failed to fetch verses, using placeholder: {e}")
                        # Use placeholder if API fails
                        pass

                # Stage 5: Perform forced alignment
                logger.info("Stage 5: Performing forced alignment")
                timestamp_map = self.alignment_engine.align(
                    wav_path, verses, parasha_name, aliyah_name
                )
                # Log detailed aliyah information
                logger.info(
                    f"Alignment complete",
                    quality=timestamp_map.alignment_quality,
                    verse_count=timestamp_map.verse_count,
                )
                logger.info(
                    f"Aliyah Details",
                    parasha=parasha_name,
                    aliyah=aliyah_name,
                    audio_duration=audio_source.duration_seconds,
                    verse_count=len(verses),
                    first_verse=verses[0][0] if verses else None,
                    last_verse=verses[-1][0] if verses else None,
                )
                for i, verse_ts in enumerate(timestamp_map.verse_timestamps, 1):
                    logger.info(
                        f"Verse {i}",
                        reference=verse_ts.reference,
                        start=f"{verse_ts.start_time:.2f}s",
                        end=f"{verse_ts.end_time:.2f}s",
                        duration=f"{verse_ts.duration:.2f}s",
                    )

                # Save timestamp map
                timestamp_dir = get_cache_dir() / "timestamp_maps"
                timestamp_dir.mkdir(parents=True, exist_ok=True)
                timestamp_file = timestamp_dir / f"{parasha_name}_{aliyah_name}.json"
                self.alignment_engine.save_timestamp_map(timestamp_map, timestamp_file)

                current_state = AliyahState.ALIGNED

                # Stage 6: Render video
                logger.info("Stage 6: Rendering video")
                current_state = AliyahState.RENDERING

                output_dir = output_dir or get_output_dir()
                output_path = output_dir / f"{parasha_name}_{aliyah_name}_sync.mp4"

                video = self.video_renderer.render(
                    audio_file, timestamp_map, output_path, verses=verses
                )

                current_state = AliyahState.COMPLETED
                logger.info(
                    f"Pipeline complete",
                    output_path=str(video.file_path),
                    file_size_mb=video.file_size_mb,
                )

                return video

        except Exception as e:
            current_state = AliyahState.FAILED
            logger.error(
                f"Pipeline failed",
                audio_file=str(audio_file),
                state=current_state.value,
                error=str(e),
                exc_info=True,
            )
            raise TorahSyncError(f"Processing failed at stage {current_state.value}: {e}") from e
