# Generated by Claude Opus 4.6
"""Phase 3 pipeline: DuckDB alignment data -> rendered video."""

from pathlib import Path

from src.lib.config import get_output_dir
from src.lib.exceptions import TorahSyncError
from src.lib.logging import get_logger
from src.models.alya_video import AlyaVideo
from src.repositories.alignment_repo import AlignmentRunRepository
from src.repositories.alya_audio_repo import AlyaAudioRepository
from src.repositories.alya_repo import AlyaRepository
from src.repositories.alya_video_repo import AlyaVideoRepository
from src.repositories.pasuk_alignment_repo import PasukAlignmentRepository
from src.repositories.playlist_repo import PlaylistRepository
from src.services.local_thumbnail_service import LocalThumbnailService
from src.services.video.renderer import VideoRenderer

logger = get_logger(__name__)


class RenderPipeline:
    """Phase 3: read alignment from DuckDB, render video.

    Reads finalized pasuk_alignments and produces an MP4 video.
    """

    def __init__(self) -> None:
        self.playlist_repo = PlaylistRepository()
        self.alya_repo = AlyaRepository()
        self.alya_audio_repo = AlyaAudioRepository()
        self.alignment_run_repo = AlignmentRunRepository()
        self.pasuk_alignment_repo = PasukAlignmentRepository()
        self.alya_video_repo = AlyaVideoRepository()
        self.video_renderer = VideoRenderer()
        self.thumbnail_service = LocalThumbnailService()

        logger.debug("Initialized RenderPipeline")

    def render(self, alya_id: int, output_dir: Path | None = None) -> AlyaVideo:
        """Render video for an alya using its latest alignment data.

        Args:
            alya_id: ID of the alya to render
            output_dir: Output directory (default from config)

        Returns:
            AlyaVideo model persisted to DuckDB
        """
        logger.info(f"Starting render pipeline {alya_id=}")

        try:
            # Load alya + audio
            alya = self.alya_repo.get_by_id(alya_id)
            if not alya:
                raise TorahSyncError(f"Alya not found: {alya_id=}")

            alya_audio = self.alya_audio_repo.get_by_alya(alya_id)
            if not alya_audio:
                raise TorahSyncError(f"No audio found for {alya_id=}")

            # Find latest alignment run
            alignment_run = self.alignment_run_repo.get_latest_by_audio(alya_audio.id)
            if not alignment_run:
                raise TorahSyncError(f"No alignment run found for audio {alya_audio.id=}")

            pasuk_alignments = self.pasuk_alignment_repo.list_by_alignment_run(alignment_run.id)
            if not pasuk_alignments:
                raise TorahSyncError(f"No pasuk alignments for run {alignment_run.id=}")

            # Build output path
            playlist = self.playlist_repo.get_by_id(alya.playlist_id)
            output_dir = output_dir or get_output_dir()
            output_dir.mkdir(parents=True, exist_ok=True)
            parasha_name = playlist.name if playlist else "unknown"
            output_path = output_dir / f"{parasha_name}_{alya.name}_sync.mp4"

            # Edited by Claude Sonnet 4.5
            # Find thumbnail for megillot (before rendering)
            thumbnail_path = self.thumbnail_service.find_thumbnail(playlist, alya)

            # Render
            audio_file = Path(alya_audio.file_path)
            verses = [(pa.reference, pa.hebrew_text) for pa in pasuk_alignments]

            video = self.video_renderer.render(
                audio_file=audio_file,
                alignment_run=alignment_run,
                output_path=output_path,
                verses=verses,
                pasuk_alignments=pasuk_alignments,
                alya_id=alya_id,
                thumbnail_path=thumbnail_path,  # Pass thumbnail to renderer for embedding
            )

            # Store thumbnail path in database for YouTube upload
            if thumbnail_path:
                video.thumbnail_path = str(thumbnail_path)
                logger.info(f"Associated thumbnail: {thumbnail_path.name}")

            # Edited by Claude Opus 4.6
            # Persist video metadata (upsert: update if re-rendering)
            existing_videos = self.alya_video_repo.list_by_alya(alya_id)
            if existing_videos:
                video.id = existing_videos[0].id
                self.alya_video_repo.update(video)
            else:
                self.alya_video_repo.insert(video)

            logger.info(f"Render pipeline complete {output_path=}")
            return video

        except Exception as e:
            logger.error(f"Render pipeline failed: {e}", exc_info=True)
            raise TorahSyncError(f"Render failed: {e}") from e
