# Generated by Claude Code
"""AudioConverter for converting audio files to alignment-ready format."""

import tempfile
from pathlib import Path

from pydub import AudioSegment

from src.lib.config import settings
from src.lib.exceptions import TorahSyncError
from src.lib.logging import get_logger

logger = get_logger(__name__)


class AudioConversionError(TorahSyncError):
    """Raised when audio conversion fails."""

    pass


class AudioConverter:
    """Converter for audio files to alignment-ready format.

    Converts audio to 16kHz mono WAV format optimized for forced alignment
    with aeneas. Manages temporary files and cleanup.
    """

    def __init__(
        self,
        target_sample_rate: int | None = None,
        target_channels: int = 1,
    ) -> None:
        """Initialize the AudioConverter.

        Args:
            target_sample_rate: Target sample rate in Hz (default from config)
            target_channels: Target channel count (1 for mono, 2 for stereo)
        """
        self.target_sample_rate = target_sample_rate or settings.get(
            "alignment.audio_sample_rate", 16000
        )
        self.target_channels = target_channels
        self._temp_files: list[Path] = []

    def convert_to_alignment_format(
        self, audio_segment: AudioSegment, output_path: Path | None = None
    ) -> Path:
        """Convert audio to alignment-ready format (16kHz mono WAV).

        Args:
            audio_segment: Loaded audio segment from pydub
            output_path: Optional output path (temp file created if not provided)

        Returns:
            Path to converted WAV file

        Raises:
            AudioConversionError: If conversion fails

        Example:
            >>> converter = AudioConverter()
            >>> audio = AudioSegment.from_file("audio.mp4")
            >>> wav_path = converter.convert_to_alignment_format(audio)
            >>> logger.info(f"Converted to: {wav_path}")
        """
        logger.debug(
            f"Converting audio to alignment format",
            target_sample_rate=self.target_sample_rate,
            target_channels=self.target_channels,
        )

        try:
            # Convert to mono if needed
            if audio_segment.channels != self.target_channels:
                if self.target_channels == 1:
                    logger.debug("Converting to mono")
                    audio_segment = audio_segment.set_channels(1)
                else:
                    logger.debug(f"Converting to {self.target_channels} channels")
                    audio_segment = audio_segment.set_channels(self.target_channels)

            # Resample if needed
            if audio_segment.frame_rate != self.target_sample_rate:
                logger.debug(
                    f"Resampling from {audio_segment.frame_rate}Hz to {self.target_sample_rate}Hz"
                )
                audio_segment = audio_segment.set_frame_rate(self.target_sample_rate)

            # Create output path if not provided
            if output_path is None:
                output_path = self._create_temp_file(suffix=".wav")

            # Export as WAV
            logger.debug(f"Exporting to WAV: {output_path}")
            audio_segment.export(output_path, format="wav")

            logger.info(
                f"Audio converted successfully",
                output_path=str(output_path),
                sample_rate=self.target_sample_rate,
                channels=self.target_channels,
                file_size_mb=output_path.stat().st_size / (1024 * 1024),
            )

            return output_path

        except Exception as e:
            raise AudioConversionError(f"Failed to convert audio: {e}") from e

    def _create_temp_file(self, suffix: str = ".wav") -> Path:
        """Create a temporary file for converted audio.

        Args:
            suffix: File extension (default: .wav)

        Returns:
            Path to temporary file
        """
        # Create temp file and track it for cleanup
        temp_fd, temp_path_str = tempfile.mkstemp(suffix=suffix, prefix="torah_sync_")
        import os

        os.close(temp_fd)  # Close file descriptor, we just need the path

        temp_path = Path(temp_path_str)
        self._temp_files.append(temp_path)

        logger.debug(f"Created temporary file: {temp_path}")
        return temp_path

    def cleanup(self) -> None:
        """Clean up all temporary files created by this converter.

        Example:
            >>> converter = AudioConverter()
            >>> wav_path = converter.convert_to_alignment_format(audio)
            >>> # ... use wav_path ...
            >>> converter.cleanup()  # Remove temp files
        """
        if not self._temp_files:
            return

        logger.debug(f"Cleaning up {len(self._temp_files)} temporary files")

        for temp_file in self._temp_files:
            try:
                if temp_file.exists():
                    temp_file.unlink()
                    logger.debug(f"Deleted temporary file: {temp_file}")
            except Exception as e:
                logger.warning(f"Failed to delete temporary file {temp_file}: {e}")

        self._temp_files.clear()

    def __enter__(self):
        """Context manager entry."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit - cleanup temporary files."""
        self.cleanup()
        return False
