# Generated by Claude Code
"""AudioFileReader for loading and extracting metadata from audio files."""

from pathlib import Path

from pydub import AudioSegment
from pydub.exceptions import CouldntDecodeError

from src.lib.exceptions import TorahSyncError
from src.lib.logging import get_logger
from src.models.audio_source import AudioSource

logger = get_logger(__name__)


class AudioReadError(TorahSyncError):
    """Raised when audio file cannot be read or decoded."""

    pass


class AudioFileReader:
    """Reader for audio files supporting MP3, MP4, and WAV formats.

    This class handles loading audio files and extracting metadata such as
    duration, sample rate, and channel count.
    """

    SUPPORTED_FORMATS = {"mp3", "mp4", "wav"}

    def __init__(self) -> None:
        """Initialize the AudioFileReader."""
        pass

    def read(self, file_path: Path, parasha_name: str, aliyah_name: str) -> AudioSource:
        """Load audio file and extract metadata.

        Args:
            file_path: Path to audio file
            parasha_name: Parasha name (for AudioSource model)
            aliyah_name: Aliyah name (for AudioSource model)

        Returns:
            AudioSource model with metadata

        Raises:
            FileNotFoundError: If file doesn't exist
            AudioReadError: If file cannot be read or format is unsupported

        Example:
            >>> reader = AudioFileReader()
            >>> audio = reader.read(Path("audio.mp4"), "האזינו", "ראשון")
            >>> logger.info(f"{audio.duration_seconds=}, {audio.sample_rate=}")
        """
        logger.debug(f"Reading audio file: {file_path=}")

        # Validate file exists
        if not file_path.exists():
            raise FileNotFoundError(f"Audio file not found: {file_path}")

        if not file_path.is_file():
            raise AudioReadError(f"Path is not a file: {file_path}")

        # Detect format
        file_format = self._detect_format(file_path)
        logger.debug(f"Detected format: {file_format=}")

        # Load audio file
        try:
            audio_segment = self._load_audio(file_path, file_format)
        except CouldntDecodeError as e:
            raise AudioReadError(f"Failed to decode audio file {file_path}: {e}") from e
        except Exception as e:
            raise AudioReadError(f"Unexpected error reading {file_path}: {e}") from e

        # Extract metadata
        duration_seconds = len(audio_segment) / 1000.0  # pydub uses milliseconds
        sample_rate = audio_segment.frame_rate
        channels = audio_segment.channels

        logger.info(
            f"Audio loaded successfully",
            file_path=str(file_path),
            duration_seconds=duration_seconds,
            sample_rate=sample_rate,
            channels=channels,
        )

        return AudioSource(
            file_path=file_path,
            format=file_format,
            duration_seconds=duration_seconds,
            sample_rate=sample_rate,
            channels=channels,
            attribution="",  # Can be populated later
            parasha_name=parasha_name,
            aliyah_name=aliyah_name,
        )

    def _detect_format(self, file_path: Path) -> str:
        """Detect audio format from file extension.

        Args:
            file_path: Path to audio file

        Returns:
            Format string (mp3, mp4, wav)

        Raises:
            AudioReadError: If format is unsupported
        """
        suffix = file_path.suffix.lower().lstrip(".")

        if suffix not in self.SUPPORTED_FORMATS:
            raise AudioReadError(
                f"Unsupported audio format: {suffix}. "
                f"Supported formats: {', '.join(sorted(self.SUPPORTED_FORMATS))}"
            )

        return suffix

    def _load_audio(self, file_path: Path, file_format: str) -> AudioSegment:
        """Load audio file using pydub.

        Args:
            file_path: Path to audio file
            file_format: Audio format (mp3, mp4, wav)

        Returns:
            Loaded AudioSegment

        Raises:
            CouldntDecodeError: If pydub cannot decode the file
        """
        # pydub uses 'mp4' format for .mp4 files (AAC codec)
        if file_format == "mp4":
            return AudioSegment.from_file(file_path, format="mp4")
        elif file_format == "mp3":
            return AudioSegment.from_mp3(file_path)
        elif file_format == "wav":
            return AudioSegment.from_wav(file_path)
        else:
            # Fallback to auto-detection
            return AudioSegment.from_file(file_path)
