# Generated by Claude Opus 4.6
"""Tests for PasukAlignment model validation."""

import pytest

from src.models.pasuk_alignment import PasukAlignment


def test_valid_pasuk_alignment():
    """Create a valid PasukAlignment."""
    pa = PasukAlignment(
        alignment_run_id=1, reference="Deuteronomy 32:1",
        hebrew_text="הַאֲזִ֥ינוּ", verse_order=1,
        start_time=0.0, end_time=5.0, confidence=0.95,
    )
    assert pa.start_time == 0.0
    assert pa.end_time == 5.0


def test_end_must_be_after_start():
    """end_time must be > start_time."""
    with pytest.raises(ValueError, match="end_time.*must be greater than start_time"):
        PasukAlignment(
            alignment_run_id=1, reference="Deut 32:1",
            hebrew_text="טקסט", verse_order=1,
            start_time=5.0, end_time=5.0, confidence=0.9,
        )


def test_confidence_bounds():
    """Confidence must be between 0 and 1."""
    with pytest.raises(ValueError):
        PasukAlignment(
            alignment_run_id=1, reference="Deut 32:1",
            hebrew_text="טקסט", verse_order=1,
            start_time=0.0, end_time=5.0, confidence=1.5,
        )


def test_correction_fields_default_none():
    """Original timestamps are None by default."""
    pa = PasukAlignment(
        alignment_run_id=1, reference="Deut 32:1",
        hebrew_text="טקסט", verse_order=1,
        start_time=0.0, end_time=5.0, confidence=0.9,
    )
    assert pa.original_start_time is None
    assert pa.original_end_time is None
    assert pa.manually_corrected is False
