# Generated by Claude Opus 4.6
"""Tests for megillot support in Playlist and Alya models."""

import pytest

from src.models.alya import Alya, VALID_ALYA_NAMES_MEGILLAH, VALID_ALYA_NAMES_TORAH
from src.models.playlist import Playlist, PlaylistType


class TestPlaylistType:
    """Tests for Playlist with playlist_type field."""

    def test_default_playlist_type_is_parasha(self):
        p = Playlist(name="האזינו", book="Deuteronomy", chapter_start=32, verse_start=1, chapter_end=32, verse_end=52)
        assert p.playlist_type == PlaylistType.PARASHA

    def test_megillah_playlist_type(self):
        p = Playlist(
            name="שיר השירים",
            book="Song of Songs",
            playlist_type=PlaylistType.MEGILLAH,
            chapter_start=1,
            verse_start=1,
            chapter_end=8,
            verse_end=14,
        )
        assert p.playlist_type == PlaylistType.MEGILLAH
        assert p.book == "Song of Songs"

    def test_playlist_type_from_string(self):
        p = Playlist(
            name="רות",
            book="Ruth",
            playlist_type="megillah",
            chapter_start=1,
            verse_start=1,
            chapter_end=4,
            verse_end=22,
        )
        assert p.playlist_type == PlaylistType.MEGILLAH


class TestAlyaMegillah:
    """Tests for Alya with megillah chapter names."""

    def test_chapter_name_valid(self):
        a = Alya(playlist_id=1, name="פרק א", order_num=1)
        assert a.name == "פרק א"

    def test_chapter_names_in_valid_set(self):
        for name in VALID_ALYA_NAMES_MEGILLAH:
            a = Alya(playlist_id=1, name=name, order_num=1)
            assert a.name == name

    def test_torah_names_still_valid(self):
        for name in VALID_ALYA_NAMES_TORAH:
            a = Alya(playlist_id=1, name=name, order_num=1)
            assert a.name == name

    def test_order_num_up_to_12(self):
        a = Alya(playlist_id=1, name="פרק יב", order_num=12)
        assert a.order_num == 12

    def test_order_num_up_to_30(self):
        a = Alya(playlist_id=1, name="פרק א", order_num=30)
        assert a.order_num == 30

    def test_invalid_name_rejected(self):
        with pytest.raises(ValueError, match="Invalid Alya name"):
            Alya(playlist_id=1, name="invalid", order_num=1)
