# Generated by Claude Sonnet 4.5
"""Unit tests for YouTube models."""

from datetime import datetime
from pathlib import Path

import pytest

from src.models.youtube_metadata import YouTubeMetadata
from src.models.youtube_playlist import YouTubePlaylist
from src.models.youtube_thumbnail import YouTubeThumbnail
from src.models.youtube_upload import YouTubeUpload
from src.models.youtube_video import YouTubeVideo
from src.models.video_mapping import VideoMapping


# YouTubeVideo tests

def test_create_youtube_video():
    """Test creating a YouTubeVideo instance."""
    video = YouTubeVideo(
        video_id="abc123",
        title="Test Video",
        thumbnail_url="https://example.com/thumb.jpg",
    )
    assert video.video_id == "abc123"
    assert video.title == "Test Video"
    assert video.view_count == 0


def test_has_cached_thumbnail_missing_path():
    """Test has_cached_thumbnail with no local path."""
    video = YouTubeVideo(
        video_id="abc123",
        title="Test",
        thumbnail_url="https://example.com/thumb.jpg",
    )
    assert not video.has_cached_thumbnail()


def test_has_cached_thumbnail_exists(tmp_path):
    """Test has_cached_thumbnail with existing file."""
    thumb_path = tmp_path / "thumb.jpg"
    thumb_path.write_text("fake")

    video = YouTubeVideo(
        video_id="abc123",
        title="Test",
        thumbnail_url="https://example.com/thumb.jpg",
        thumbnail_local_path=thumb_path,
    )
    assert video.has_cached_thumbnail()


# VideoMapping tests

def test_create_video_mapping(tmp_path):
    """Test creating VideoMapping."""
    video_path = tmp_path / "video.mp4"
    video_path.write_text("fake")

    mapping = VideoMapping(
        youtube_video_id="abc123",
        new_video_path=video_path,
        alya_id=1,
    )
    assert mapping.youtube_video_id == "abc123"
    assert mapping.preserve_thumbnail is True


def test_validate_new_video_exists(tmp_path):
    """Test video file validation."""
    video_path = tmp_path / "video.mp4"
    video_path.write_text("fake")

    mapping = VideoMapping(
        youtube_video_id="abc123",
        new_video_path=video_path,
        alya_id=1,
    )
    assert mapping.validate_new_video_exists()


def test_validate_new_video_missing(tmp_path):
    """Test video file validation when missing."""
    mapping = VideoMapping(
        youtube_video_id="abc123",
        new_video_path=tmp_path / "missing.mp4",
        alya_id=1,
    )
    assert not mapping.validate_new_video_exists()


# YouTubeMetadata tests

def test_create_youtube_metadata():
    """Test creating YouTubeMetadata."""
    metadata = YouTubeMetadata(
        title="Test Video",
        description="Test description",
        tags=["torah", "hebrew"],
    )
    assert metadata.title == "Test Video"
    assert len(metadata.tags) == 2
    assert metadata.category_id == "27"


def test_metadata_title_too_long():
    """Test title length validation."""
    with pytest.raises(ValueError):
        YouTubeMetadata(
            title="x" * 101,
            description="Test",
        )


def test_metadata_tags_too_long():
    """Test tags total length validation."""
    with pytest.raises(ValueError, match="exceeds 500 chars"):
        YouTubeMetadata(
            title="Test",
            description="Test",
            tags=["x" * 501],
        )


def test_metadata_privacy_status_invalid():
    """Test invalid privacy status."""
    with pytest.raises(ValueError, match="Invalid privacy status"):
        YouTubeMetadata(
            title="Test",
            description="Test",
            privacy_status="invalid",
        )


def test_metadata_privacy_status_valid():
    """Test valid privacy statuses."""
    for status in ["private", "unlisted", "public"]:
        metadata = YouTubeMetadata(
            title="Test",
            description="Test",
            privacy_status=status,
        )
        assert metadata.privacy_status == status


# YouTubePlaylist tests

def test_create_youtube_playlist():
    """Test creating YouTubePlaylist."""
    playlist = YouTubePlaylist(
        playlist_id=1,
        youtube_playlist_id="PLxyz123",
        title="פרשת בראשית",
    )
    assert playlist.playlist_id == 1
    assert playlist.aliyah_count == 7


def test_playlist_is_complete_false():
    """Test is_complete when incomplete."""
    playlist = YouTubePlaylist(
        playlist_id=1,
        youtube_playlist_id="PLxyz123",
        title="Test",
        video_ids=["vid1", "vid2"],
    )
    assert not playlist.is_complete()


def test_playlist_is_complete_true():
    """Test is_complete when all videos present."""
    playlist = YouTubePlaylist(
        playlist_id=1,
        youtube_playlist_id="PLxyz123",
        title="Test",
        video_ids=[f"vid{i}" for i in range(7)],
    )
    assert playlist.is_complete()


def test_playlist_get_aliyah_position():
    """Test aliyah position mapping."""
    playlist = YouTubePlaylist(
        playlist_id=1,
        youtube_playlist_id="PLxyz123",
        title="Test",
    )

    assert playlist.get_aliyah_position("ראשון") == 0
    assert playlist.get_aliyah_position("שני") == 1
    assert playlist.get_aliyah_position("שלישי") == 2
    assert playlist.get_aliyah_position("unknown") == 0


# YouTubeThumbnail tests

def test_create_youtube_thumbnail(tmp_path):
    """Test creating YouTubeThumbnail."""
    thumb_path = tmp_path / "thumb.jpg"
    thumb_path.write_text("fake")

    thumbnail = YouTubeThumbnail(
        id=1,
        video_id="abc123",
        original_url="https://example.com/thumb.jpg",
        cached_path=thumb_path,
        downloaded_at=datetime.utcnow(),
    )
    assert thumbnail.exists()


def test_thumbnail_exists_false(tmp_path):
    """Test exists() when file missing."""
    thumbnail = YouTubeThumbnail(
        id=1,
        video_id="abc123",
        original_url="https://example.com/thumb.jpg",
        cached_path=tmp_path / "missing.jpg",
        downloaded_at=datetime.utcnow(),
    )
    assert not thumbnail.exists()


# YouTubeUpload tests

def test_create_youtube_upload():
    """Test creating YouTubeUpload."""
    upload = YouTubeUpload(
        id=1,
        alya_video_id=1,
        new_youtube_video_id="new123",
        uploaded_at=datetime.utcnow(),
    )
    assert upload.upload_status == "pending"


def test_upload_status_methods():
    """Test upload status helper methods."""
    pending = YouTubeUpload(
        id=1,
        alya_video_id=1,
        new_youtube_video_id="new123",
        upload_status="pending",
        uploaded_at=datetime.utcnow(),
    )
    assert pending.is_pending()
    assert not pending.is_completed()

    completed = YouTubeUpload(
        id=2,
        alya_video_id=1,
        new_youtube_video_id="new456",
        upload_status="completed",
        uploaded_at=datetime.utcnow(),
    )
    assert completed.is_completed()
    assert not pending.is_failed()

    failed = YouTubeUpload(
        id=3,
        alya_video_id=1,
        new_youtube_video_id="new789",
        upload_status="failed",
        error_message="Upload error",
        uploaded_at=datetime.utcnow(),
    )
    assert failed.is_failed()
