# Generated by Claude Opus 4.6
"""Tests for the megillot audio rename script."""

import pytest

from scripts.rename_megillot_audio import build_rename_mapping, find_jpg_pattern


@pytest.fixture
def megillah_folder(tmp_path):
    """Create a mock megillah folder with JPGs and MP3s."""
    for i in range(1, 4):
        (tmp_path / f"Megillat_Shir_Hashirim_{i}.jpg").touch()
    for name in ("VN550644.mp3", "VN550645.mp3", "VN550646.mp3"):
        (tmp_path / name).touch()
    return tmp_path


def test_find_jpg_pattern(megillah_folder):
    pattern, numbers = find_jpg_pattern(megillah_folder)
    assert pattern == "Megillat_Shir_Hashirim_"
    assert numbers == [1, 2, 3]


def test_build_rename_mapping(megillah_folder):
    mapping = build_rename_mapping(megillah_folder)
    assert len(mapping) == 3
    old_names = [old.name for old, _ in mapping]
    new_names = [new.name for _, new in mapping]
    assert old_names == ["VN550644.mp3", "VN550645.mp3", "VN550646.mp3"]
    assert new_names == [
        "Megillat_Shir_Hashirim_1.mp3",
        "Megillat_Shir_Hashirim_2.mp3",
        "Megillat_Shir_Hashirim_3.mp3",
    ]


def test_already_renamed_returns_empty(megillah_folder):
    """When MP3s already match the JPG pattern, return empty mapping."""
    for f in megillah_folder.glob("VN*.mp3"):
        f.unlink()
    for i in range(1, 4):
        (megillah_folder / f"Megillat_Shir_Hashirim_{i}.mp3").touch()

    mapping = build_rename_mapping(megillah_folder)
    assert mapping == []


def test_mismatch_count_raises(megillah_folder):
    """Raise ValueError when MP3 count doesn't match JPG count."""
    (megillah_folder / "VN550647.mp3").touch()
    with pytest.raises(ValueError, match="Mismatch"):
        build_rename_mapping(megillah_folder)


def test_no_jpgs_raises(tmp_path):
    (tmp_path / "VN550644.mp3").touch()
    with pytest.raises(FileNotFoundError, match="No JPG"):
        find_jpg_pattern(tmp_path)


def test_skips_non_matching_jpgs(tmp_path):
    """ContactSheet-001.jpg should be ignored when extracting pattern."""
    (tmp_path / "ContactSheet-001.jpg").touch()
    for i in range(1, 4):
        (tmp_path / f"Megillat_Kohelet_{i}.jpg").touch()
    for name in ("VN550592.mp3", "VN550593.mp3", "VN550594.mp3"):
        (tmp_path / name).touch()

    pattern, numbers = find_jpg_pattern(tmp_path)
    assert pattern == "Megillat_Kohelet_"
    assert numbers == [1, 2, 3]

    mapping = build_rename_mapping(tmp_path)
    new_names = [new.name for _, new in mapping]
    assert new_names == [
        "Megillat_Kohelet_1.mp3",
        "Megillat_Kohelet_2.mp3",
        "Megillat_Kohelet_3.mp3",
    ]


def test_no_matching_jpgs_raises(tmp_path):
    """Raise ValueError when no JPGs match the expected pattern."""
    (tmp_path / "ContactSheet-001.jpg").touch()
    (tmp_path / "random_photo.jpg").touch()
    with pytest.raises(ValueError, match="No JPG files match"):
        find_jpg_pattern(tmp_path)


def test_batch_all_subfolders(tmp_path):
    """Test processing multiple subfolders."""
    # Folder A: needs renaming
    folder_a = tmp_path / "folderA"
    folder_a.mkdir()
    for i in range(1, 3):
        (folder_a / f"megillat_test_{i}.jpg").touch()
    (folder_a / "VN001.mp3").touch()
    (folder_a / "VN002.mp3").touch()

    # Folder B: already renamed
    folder_b = tmp_path / "folderB"
    folder_b.mkdir()
    for i in range(1, 3):
        (folder_b / f"megillat_done_{i}.jpg").touch()
        (folder_b / f"megillat_done_{i}.mp3").touch()

    # Folder A should have a mapping
    mapping_a = build_rename_mapping(folder_a)
    assert len(mapping_a) == 2
    assert [n.name for _, n in mapping_a] == ["megillat_test_1.mp3", "megillat_test_2.mp3"]

    # Folder B should return empty (already matched)
    mapping_b = build_rename_mapping(folder_b)
    assert mapping_b == []
