# Generated by Claude Code
"""CLI entry point for Torah Sync application."""

import sys
from pathlib import Path

import click

from src.lib.config import settings
from src.lib.exceptions import TorahSyncError
from src.lib.filename_parser import validate_audio_file
from src.lib.logging import get_logger, setup_logging

# Setup logging before any other imports
setup_logging(
    log_level=settings.get("log_level", "INFO"),
    use_json=False,  # Human-readable for CLI
)

logger = get_logger(__name__)


@click.group()
@click.version_option(version="0.1.0", prog_name="torah-sync")
def cli():
    """Torah Sync - Automated Torah Reading Audio-Visual Synchronization.

    Generate synchronized videos from Torah reading audio files, where Hebrew
    text with vowels and cantillation marks highlights in real-time.
    """
    pass


@cli.command()
@click.argument("audio_file", type=click.Path(exists=True, path_type=Path))
@click.option(
    "--output",
    "-o",
    type=click.Path(path_type=Path),
    help="Output directory (default: output/videos/)",
)
@click.option(
    "--cache-dir",
    type=click.Path(path_type=Path),
    help="Cache directory for Sefaria API responses",
)
@click.option(
    "--font",
    type=click.Path(exists=True, path_type=Path),
    help="Path to Hebrew font file",
)
@click.option(
    "--log-level",
    type=click.Choice(["DEBUG", "INFO", "WARNING", "ERROR"], case_sensitive=False),
    default="INFO",
    help="Logging level",
)
def process(
    audio_file: Path,
    output: Path | None,
    cache_dir: Path | None,
    font: Path | None,
    log_level: str,
):
    """Process a single audio file and generate synchronized video.

    AUDIO_FILE should follow the naming convention:
    פרשת {Parasha} - {Aliyah} - נוסח אשכנז.{ext}

    Valid extensions: mp3, mp4, wav
    Valid Aliyah names: ראשון, שני, שלישי, רביעי, חמישי, שישי, שביעי, מפטיר, הפטרה

    Example:

        torah-sync process "data/audio/פרשת האזינו - ראשון - נוסח אשכנז.mp4"
    """
    # Update log level
    setup_logging(log_level=log_level, use_json=False)

    logger.info(f"Processing audio file", audio_file=str(audio_file))

    try:
        # Validate filename
        validate_audio_file(audio_file)

        # Import pipeline here to avoid circular imports
        from src.services.pipeline import ProcessingPipeline

        # Create pipeline and process
        pipeline = ProcessingPipeline()
        video = pipeline.process_single_aliyah(audio_file, output_dir=output)

        # Success
        click.echo(f"✓ Video created successfully: {video.file_path}")
        click.echo(f"  Duration: {video.duration_seconds:.1f}s")
        click.echo(f"  Resolution: {video.resolution[0]}x{video.resolution[1]}")
        click.echo(f"  File size: {video.file_size_mb:.1f}MB")

        sys.exit(0)

    except TorahSyncError as e:
        logger.error(f"Processing failed", error=str(e), exc_info=True)
        click.echo(f"✗ Error: {e}", err=True)
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error", error=str(e), exc_info=True)
        click.echo(f"✗ Unexpected error: {e}", err=True)
        sys.exit(2)


@cli.command()
@click.argument("audio_dir", type=click.Path(exists=True, path_type=Path))
@click.option(
    "--parallel",
    "-p",
    type=int,
    default=1,
    help="Number of parallel workers (default: 1)",
)
@click.option(
    "--output",
    "-o",
    type=click.Path(path_type=Path),
    help="Output directory (default: output/videos/)",
)
@click.option(
    "--log-level",
    type=click.Choice(["DEBUG", "INFO", "WARNING", "ERROR"], case_sensitive=False),
    default="INFO",
    help="Logging level",
)
def batch(
    audio_dir: Path,
    parallel: int,
    output: Path | None,
    log_level: str,
):
    """Batch process all audio files in a directory.

    AUDIO_DIR should contain audio files following the naming convention.

    Example:

        torah-sync batch data/audio/ --parallel 4
    """
    setup_logging(log_level=log_level, use_json=False)

    logger.info(f"Batch processing directory", audio_dir=str(audio_dir), parallel=parallel)

    try:
        # Find all audio files
        audio_files = []
        for ext in ["*.mp3", "*.mp4", "*.wav"]:
            audio_files.extend(audio_dir.glob(ext))

        if not audio_files:
            click.echo(f"✗ No audio files found in {audio_dir}", err=True)
            sys.exit(1)

        click.echo(f"Found {len(audio_files)} audio files")

        # Import batch processor
        # TODO: Implement BatchProcessor (Phase 5 - User Story 3)
        click.echo("✗ Batch processing not yet implemented", err=True)
        click.echo("  Use 'torah-sync process' for single files", err=True)
        sys.exit(3)

    except Exception as e:
        logger.error(f"Batch processing failed", error=str(e), exc_info=True)
        click.echo(f"✗ Error: {e}", err=True)
        sys.exit(2)


if __name__ == "__main__":
    cli()
