# Generated by Claude Sonnet 4.5
"""CLI commands for YouTube operations."""

import json
import logging
from pathlib import Path

import click

from src.lib.config import settings

logger = logging.getLogger(__name__)


@click.group()
def youtube():
    """YouTube video update and metadata management commands."""
    pass


@youtube.command()
@click.option(
    "--channel",
    default=None,
    help="YouTube channel handle (default: from settings.toml)"
)
def prepare_channel(channel: str | None):
    """Download and cache all thumbnails from source channel.

    This command:
    1. Authenticates with YouTube API (OAuth2)
    2. Resolves channel handle to channel ID
    3. Lists all videos from the channel
    4. Downloads all thumbnails to data/thumbnails/
    5. Saves metadata to DuckDB (youtube_thumbnails table)

    Args:
        channel: YouTube channel handle (e.g., "@קריאהבתורהמפייוסףבודנהיימר")
    """
    from src.services.youtube.auth import YouTubeAuth
    from src.services.youtube.channel_scanner import ChannelScanner
    from src.services.youtube.thumbnail_manager import ThumbnailManager

    # Get channel from settings if not provided
    if not channel:
        channel = settings.get("youtube.source_channel", "@קריאהבתורהמפייוסףבודנהיימר")

    click.echo(f"📺 Preparing channel: {channel}")
    click.echo()

    # Initialize services
    try:
        client_secrets_path = Path(settings.get("youtube.client_secrets_path"))
        if not client_secrets_path.exists():
            click.echo(f"❌ Client secrets not found: {client_secrets_path}", err=True)
            click.echo()
            click.echo("To set up YouTube API credentials:")
            click.echo("1. Go to https://console.cloud.google.com/")
            click.echo("2. Create a project and enable YouTube Data API v3")
            click.echo("3. Create OAuth2 credentials")
            click.echo(f"4. Download JSON and save to {client_secrets_path}")
            raise click.Abort()

        auth = YouTubeAuth(client_secrets_path=client_secrets_path)
        scanner = ChannelScanner(auth)
        thumbnail_manager = ThumbnailManager()

    except Exception as e:
        click.echo(f"❌ Initialization failed: {e}", err=True)
        logger.exception("Failed to initialize YouTube services")
        raise click.Abort()

    # Get channel ID
    click.echo("🔍 Resolving channel ID...")
    try:
        channel_id = scanner.get_channel_id_from_handle(channel)
        click.echo(f"   Channel ID: {channel_id}")
    except Exception as e:
        click.echo(f"❌ Failed to resolve channel: {e}", err=True)
        raise click.Abort()

    # List all videos
    click.echo()
    click.echo("📋 Listing videos...")
    try:
        videos = scanner.list_all_videos(channel_id)
        click.echo(f"   Found {len(videos)} videos")
    except Exception as e:
        click.echo(f"❌ Failed to list videos: {e}", err=True)
        raise click.Abort()

    if not videos:
        click.echo("⚠️  No videos found in channel")
        return

    # Download thumbnails
    click.echo()
    click.echo(f"⬇️  Downloading {len(videos)} thumbnails...")

    try:
        with click.progressbar(
            videos,
            label="Downloading",
            show_eta=True,
            show_percent=True
        ) as bar:
            results = {}
            for video in bar:
                try:
                    path = thumbnail_manager.download_thumbnail(video)
                    results[video.video_id] = path
                except Exception as e:
                    logger.warning(f"Failed to download {video.video_id}: {e}")
                    continue

        success_count = len(results)
        fail_count = len(videos) - success_count

        click.echo()
        click.echo(f"✅ Channel prepared!")
        click.echo(f"   Videos found: {len(videos)}")
        click.echo(f"   Thumbnails downloaded: {success_count}")
        if fail_count > 0:
            click.echo(f"   Failed: {fail_count}")
        click.echo(f"   Cache directory: data/thumbnails/")

    except Exception as e:
        click.echo(f"❌ Download failed: {e}", err=True)
        logger.exception("Thumbnail download failed")
        raise click.Abort()


@youtube.command()
@click.option(
    "--channel",
    default=None,
    help="YouTube channel handle (default: from settings.toml)"
)
@click.option(
    "--output",
    type=click.Path(),
    default="output/video_list.json",
    help="Output file path"
)
def list_videos(channel: str | None, output: str):
    """List all videos from a channel and export to JSON.

    Args:
        channel: YouTube channel handle
        output: Output JSON file path
    """
    from src.services.youtube.auth import YouTubeAuth
    from src.services.youtube.channel_scanner import ChannelScanner

    # Get channel from settings if not provided
    if not channel:
        channel = settings.get("youtube.source_channel", "@קריאהבתורהמפייוסףבודנהיימר")

    click.echo(f"📺 Listing videos from: {channel}")

    # Initialize services
    try:
        client_secrets_path = Path(settings.get("youtube.client_secrets_path"))
        if not client_secrets_path.exists():
            click.echo(f"❌ Client secrets not found: {client_secrets_path}", err=True)
            raise click.Abort()

        auth = YouTubeAuth(client_secrets_path=client_secrets_path)
        scanner = ChannelScanner(auth)

    except Exception as e:
        click.echo(f"❌ Initialization failed: {e}", err=True)
        raise click.Abort()

    # Get channel videos
    try:
        channel_id = scanner.get_channel_id_from_handle(channel)
        videos = scanner.list_all_videos(channel_id)
    except Exception as e:
        click.echo(f"❌ Failed to list videos: {e}", err=True)
        raise click.Abort()

    # Export to JSON
    videos_data = [
        {
            "video_id": v.video_id,
            "title": v.title,
            "published_at": str(v.published_at) if v.published_at else None,
            "thumbnail_url": v.thumbnail_url
        }
        for v in videos
    ]

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(videos_data, f, indent=2, ensure_ascii=False)

    click.echo()
    click.echo(f"✅ Video list exported!")
    click.echo(f"   Videos found: {len(videos)}")
    click.echo(f"   Output file: {output_path}")
