# Generated by Claude Sonnet 4.5
"""Unit tests for ParashaTextFetcher."""

import tempfile
from pathlib import Path
from unittest.mock import Mock

import pytest

from src.lib.exceptions import InvalidReferenceError
from src.models.aliyah_range import AliyahRange
from src.services.text.parasha_fetcher import ParashaTextFetcher


@pytest.fixture
def temp_config():
    """Create temporary TOML configuration for testing."""
    config_content = """
["האזינו"."ראשון"]
book = "Deuteronomy"
chapter_start = 32
verse_start = 1
chapter_end = 32
verse_end = 6

["האזינו"."שני"]
book = "Deuteronomy"
chapter_start = 32
verse_start = 7
chapter_end = 32
verse_end = 12
"""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".toml", delete=False, encoding="utf-8") as f:
        f.write(config_content)
        temp_path = Path(f.name)

    yield temp_path

    # Cleanup
    temp_path.unlink()


@pytest.fixture
def mock_sefaria_client():
    """Create mock SefariaClient for testing."""
    client = Mock()
    client.get_range.return_value = [
        ("Deuteronomy 32:1", "הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם"),
        ("Deuteronomy 32:2", "יַעֲרֹ֤ף כַּמָּטָר֙"),
        ("Deuteronomy 32:3", "כִּ֛י שֵׁ֥ם יְהֹוָ֖ה"),
        ("Deuteronomy 32:4", "הַצּוּר֙ תָּמִ֣ים"),
        ("Deuteronomy 32:5", "שִׁחֵ֥ת ל֛וֹ"),
        ("Deuteronomy 32:6", "הֲלֹא־הוּא֙"),
    ]
    return client


def test_init_loads_ranges(temp_config):
    """Test ParashaTextFetcher loads ranges from TOML on initialization."""
    fetcher = ParashaTextFetcher(config_path=temp_config)

    assert len(fetcher.ranges) == 2
    assert ("האזינו", "ראשון") in fetcher.ranges
    assert ("האזינו", "שני") in fetcher.ranges


def test_init_raises_when_config_missing():
    """Test ParashaTextFetcher raises FileNotFoundError when config missing."""
    with pytest.raises(FileNotFoundError, match="Aliyah ranges configuration not found"):
        ParashaTextFetcher(config_path="/nonexistent/path.toml")


def test_get_range_for_aliyah_success(temp_config):
    """Test get_range_for_aliyah() returns correct AliyahRange."""
    fetcher = ParashaTextFetcher(config_path=temp_config)

    range_obj = fetcher.get_range_for_aliyah("האזינו", "ראשון")

    assert isinstance(range_obj, AliyahRange)
    assert range_obj.book == "Deuteronomy"
    assert range_obj.chapter_start == 32
    assert range_obj.verse_start == 1
    assert range_obj.chapter_end == 32
    assert range_obj.verse_end == 6


def test_get_range_for_aliyah_raises_for_invalid_parasha(temp_config):
    """Test get_range_for_aliyah() raises InvalidReferenceError for unknown Parasha."""
    fetcher = ParashaTextFetcher(config_path=temp_config)
    
    with pytest.raises(InvalidReferenceError, match="No range mapping found"):
        fetcher.get_range_for_aliyah("בראשית", "ראשון")


def test_get_range_for_aliyah_raises_for_invalid_aliyah(temp_config):
    """Test get_range_for_aliyah() raises InvalidReferenceError for unknown Aliyah."""
    fetcher = ParashaTextFetcher(config_path=temp_config)

    with pytest.raises(InvalidReferenceError, match="No range mapping found"):
        fetcher.get_range_for_aliyah("האזינו", "שלישי")


def test_fetch_aliyah_text_calls_client_get_range(temp_config, mock_sefaria_client):
    """Test fetch_aliyah_text() calls SefariaClient.get_range() with correct parameters."""
    fetcher = ParashaTextFetcher(config_path=temp_config, sefaria_client=mock_sefaria_client)

    verses = fetcher.fetch_aliyah_text("האזינו", "ראשון")

    mock_sefaria_client.get_range.assert_called_once_with(
        book="Deuteronomy",
        chapter_start=32,
        verse_start=1,
        chapter_end=32,
        verse_end=6,
    )
    assert len(verses) == 6


def test_fetch_aliyah_text_returns_verse_tuples(temp_config, mock_sefaria_client):
    """Test fetch_aliyah_text() returns list of (reference, hebrew_text) tuples."""
    fetcher = ParashaTextFetcher(config_path=temp_config, sefaria_client=mock_sefaria_client)

    verses = fetcher.fetch_aliyah_text("האזינו", "ראשון")

    assert isinstance(verses, list)
    assert all(isinstance(v, tuple) and len(v) == 2 for v in verses)
    assert verses[0] == ("Deuteronomy 32:1", "הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם")


def test_fetch_aliyah_text_raises_for_invalid_parasha(temp_config, mock_sefaria_client):
    """Test fetch_aliyah_text() raises InvalidReferenceError for unknown Parasha."""
    fetcher = ParashaTextFetcher(config_path=temp_config, sefaria_client=mock_sefaria_client)
    
    with pytest.raises(InvalidReferenceError):
        fetcher.fetch_aliyah_text("invalid", "ראשון")
    
    # Should not have called the client
    mock_sefaria_client.get_range.assert_not_called()


def test_aliyah_range_to_sefaria_reference():
    """Test AliyahRange.to_sefaria_reference() generates correct format."""
    # Single chapter range
    range1 = AliyahRange(
        book="Deuteronomy",
        chapter_start=32,
        verse_start=1,
        chapter_end=32,
        verse_end=6,
    )
    assert range1.to_sefaria_reference() == "Deuteronomy 32:1-6"
    
    # Multi-chapter range
    range2 = AliyahRange(
        book="Deuteronomy",
        chapter_start=32,
        verse_start=40,
        chapter_end=33,
        verse_end=5,
    )
    assert range2.to_sefaria_reference() == "Deuteronomy 32:40-33:5"
