# Generated by Claude Opus 4.6
"""Integration tests for verse-level highlighting in video rendering."""

import tempfile
from pathlib import Path

import pytest
from PIL import Image

from src.models.alignment_run import AlignmentRun
from src.models.pasuk_alignment import PasukAlignment
from src.services.text.hebrew_renderer import render_verse_image, render_verses_tall_canvas
from src.services.video.renderer import VideoRenderer


def test_render_verse_image_creates_transparent_image():
    """Test that render_verse_image creates an RGBA image with transparency."""
    image = render_verse_image(
        verse_num=1,
        hebrew_text="הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם וַאֲדַבֵּ֑רָה",
        width=1280,
        height=720,
        font_path="/System/Library/Fonts/ArialHB.ttc",
        font_size=40,
        text_color="#FFFFFF",
        y_offset=20,
    )

    assert image.mode == "RGBA", "Image should be in RGBA mode for transparency"
    assert image.size == (1280, 720), "Image size should match requested dimensions"


def test_render_verse_image_with_different_colors():
    """Test that render_verse_image respects the text_color parameter."""
    white_image = render_verse_image(
        verse_num=1,
        hebrew_text="הַאֲזִ֥ינוּ",
        width=640,
        height=360,
        font_path="/System/Library/Fonts/ArialHB.ttc",
        font_size=20,
        text_color="#FFFFFF",
        y_offset=20,
    )

    gold_image = render_verse_image(
        verse_num=1,
        hebrew_text="הַאֲזִ֥ינוּ",
        width=640,
        height=360,
        font_path="/System/Library/Fonts/ArialHB.ttc",
        font_size=20,
        text_color="#FFD700",
        y_offset=20,
    )

    # Images should be different because they use different colors
    assert white_image.tobytes() != gold_image.tobytes(), (
        "White and gold images should have different pixel data"
    )


def test_render_verse_image_with_y_offset():
    """Test that y_offset positions verses at different vertical locations."""
    image1 = render_verse_image(
        verse_num=1,
        hebrew_text="הַאֲזִ֥ינוּ",
        width=640,
        height=360,
        font_path="/System/Library/Fonts/ArialHB.ttc",
        font_size=20,
        text_color="#FFFFFF",
        y_offset=20,
    )

    image2 = render_verse_image(
        verse_num=2,
        hebrew_text="הַאֲזִ֥ינוּ",
        width=640,
        height=360,
        font_path="/System/Library/Fonts/ArialHB.ttc",
        font_size=20,
        text_color="#FFFFFF",
        y_offset=80,
    )

    # Images should be different because text is at different vertical positions
    assert image1.tobytes() != image2.tobytes(), (
        "Images with different y_offset should have different pixel data"
    )


def test_video_renderer_creates_dual_layer_clips():
    """Test that VideoRenderer creates normal + highlight layers for each verse."""
    renderer = VideoRenderer(resolution=(640, 360), fps=30)

    # Create mock data
    verses = [
        ("Deuteronomy 32:1", "הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם וַאֲדַבֵּ֑רָה"),
        ("Deuteronomy 32:2", "יַעֲרֹ֤ף כַּמָּטָר֙ לִקְחִ֔י"),
    ]

    pasuk_alignments = [
        PasukAlignment(
            alignment_run_id=1,
            reference="Deuteronomy 32:1",
            hebrew_text="הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם וַאֲדַבֵּ֑רָה",
            verse_order=1,
            start_time=0.0,
            end_time=4.2,
            confidence=0.95,
        ),
        PasukAlignment(
            alignment_run_id=1,
            reference="Deuteronomy 32:2",
            hebrew_text="יַעֲרֹ֤ף כַּמָּטָר֙ לִקְחִ֔י",
            verse_order=2,
            start_time=4.2,
            end_time=7.8,
            confidence=0.92,
        ),
    ]

    alignment_run = AlignmentRun(
        alya_audio_id=1,
        alignment_quality=0.93,
        verse_count=2,
    )

    # Create clips
    clips = renderer._create_text_clips(
        alignment_run=alignment_run,
        verses=verses,
        audio_duration=10.0,
        pasuk_alignments=pasuk_alignments,
    )

    # Should have 2 verses × 2 layers = 4 clips
    assert len(clips) == 4, f"Expected 4 clips (2 verses × 2 layers), got {len(clips)}"

    # Check that highlight clips have correct timing
    # Clips are ordered: [normal1, highlight1, normal2, highlight2]
    highlight1 = clips[1]
    highlight2 = clips[3]

    assert highlight1.start == 0.0, "First highlight should start at 0.0s"
    assert highlight1.end == 4.2, "First highlight should end at 4.2s"
    assert highlight2.start == 4.2, "Second highlight should start at 4.2s"
    assert highlight2.end == 7.8, "Second highlight should end at 7.8s"


def test_video_renderer_handles_missing_pasuk_alignments():
    """Test that VideoRenderer gracefully handles missing pasuk_alignments."""
    renderer = VideoRenderer(resolution=(640, 360), fps=30)

    verses = [
        ("Deuteronomy 32:1", "הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם וַאֲדַבֵּ֑רָה"),
    ]

    alignment_run = AlignmentRun(
        alya_audio_id=1,
        alignment_quality=0.93,
        verse_count=1,
    )

    # Create clips without pasuk_alignments
    clips = renderer._create_text_clips(
        alignment_run=alignment_run,
        verses=verses,
        audio_duration=10.0,
        pasuk_alignments=None,
    )

    # Should only have normal layers (no highlight layers)
    assert len(clips) == 1, f"Expected 1 clip (normal layer only), got {len(clips)}"


def test_image_to_clip_helper():
    """Test the _image_to_clip helper method."""
    renderer = VideoRenderer(resolution=(640, 360), fps=30)

    # Create a simple test image
    image = Image.new("RGBA", (640, 360), color=(255, 255, 255, 0))

    # Convert to clip
    clip = renderer._image_to_clip(image, duration=5.0)

    assert clip.duration == 5.0, "Clip duration should match requested duration"
    assert clip.size == (640, 360), "Clip size should match image size"


def test_render_verse_image_with_long_text():
    """Test that long text wraps correctly."""
    long_text = "הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם וַאֲדַבֵּ֑רָה וְתִשְׁמַ֥ע הָאָ֖רֶץ אִמְרֵי־פִֽי" * 5

    image = render_verse_image(
        verse_num=1,
        hebrew_text=long_text,
        width=640,
        height=360,
        font_path="/System/Library/Fonts/ArialHB.ttc",
        font_size=20,
        text_color="#FFFFFF",
        y_offset=20,
    )

    # Should not crash and should produce an image
    assert image is not None
    assert image.mode == "RGBA"


def test_render_verse_image_with_zero_y_offset():
    """Test rendering at the very top of the image."""
    image = render_verse_image(
        verse_num=1,
        hebrew_text="הַאֲזִ֥ינוּ",
        width=640,
        height=360,
        font_path="/System/Library/Fonts/ArialHB.ttc",
        font_size=20,
        text_color="#FFFFFF",
        y_offset=0,
    )

    assert image is not None
    assert image.mode == "RGBA"


def test_video_renderer_with_empty_verses_list():
    """Test that renderer handles empty verses list gracefully."""
    renderer = VideoRenderer(resolution=(640, 360), fps=30)

    alignment_run = AlignmentRun(
        alya_audio_id=1,
        alignment_quality=0.9,
        verse_count=1,  # Model requires > 0, but we pass empty list to renderer
    )

    clips = renderer._create_text_clips(
        alignment_run=alignment_run,
        verses=[],
        audio_duration=10.0,
        pasuk_alignments=[],
    )

    assert clips == [], "Empty verses should return empty clip list"


def test_video_renderer_with_mismatched_alignment_count():
    """Test handling when pasuk_alignments count doesn't match verses count."""
    renderer = VideoRenderer(resolution=(640, 360), fps=30)

    verses = [
        ("Deuteronomy 32:1", "הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם וַאֲדַבֵּ֑רָה"),
        ("Deuteronomy 32:2", "יַעֲרֹ֤ף כַּמָּטָר֙ לִקְחִ֔י"),
        ("Deuteronomy 32:3", "כִּ֛י שֵׁ֥ם יְהוָ֖ה אֶקְרָ֑א"),
    ]

    # Only 2 alignments for 3 verses
    pasuk_alignments = [
        PasukAlignment(
            alignment_run_id=1,
            reference="Deuteronomy 32:1",
            hebrew_text="הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם וַאֲדַבֵּ֑רָה",
            verse_order=1,
            start_time=0.0,
            end_time=4.2,
            confidence=0.95,
        ),
        PasukAlignment(
            alignment_run_id=1,
            reference="Deuteronomy 32:2",
            hebrew_text="יַעֲרֹ֤ף כַּמָּטָר֙ לִקְחִ֔י",
            verse_order=2,
            start_time=4.2,
            end_time=7.8,
            confidence=0.92,
        ),
    ]

    alignment_run = AlignmentRun(
        alya_audio_id=1,
        alignment_quality=0.93,
        verse_count=2,
    )

    clips = renderer._create_text_clips(
        alignment_run=alignment_run,
        verses=verses,
        audio_duration=10.0,
        pasuk_alignments=pasuk_alignments,
    )

    # Should have 3 normal clips + 2 highlight clips = 5 total
    # Third verse won't have highlight since alignment is missing
    assert len(clips) == 5, f"Expected 5 clips (3 normal + 2 highlight), got {len(clips)}"


# Scrolling functionality tests


def test_render_verses_tall_canvas_creates_tall_image():
    """Test that render_verses_tall_canvas creates a tall canvas with all verses."""
    verses = [
        ("Deuteronomy 32:1", "הַאֲזִ֥ינוּ הַשָּׁמַ֖יִם וַאֲדַבֵּ֑רָה"),
        ("Deuteronomy 32:2", "יַעֲרֹ֤ף כַּמָּטָר֙ לִקְחִ֔י"),
        ("Deuteronomy 32:3", "כִּ֛י שֵׁ֥ם יְהוָ֖ה אֶקְרָ֑א"),
    ]

    canvas, verse_positions = render_verses_tall_canvas(
        verses=verses,
        width=1280,
        font_path="/System/Library/Fonts/ArialHB.ttc",
        font_size=40,
        text_color="#FFFFFF",
        verse_spacing=120,
        top_margin=40,
    )

    # Canvas should be tall enough for all verses
    expected_height = 40 + (3 * 120)  # top_margin + (num_verses * spacing)
    assert canvas.size == (1280, expected_height), f"Canvas size should be 1280x{expected_height}"
    assert canvas.mode == "RGBA", "Canvas should be RGBA for transparency"

    # Should have Y positions for all verses
    assert len(verse_positions) == 3, "Should have positions for all 3 verses"
    assert verse_positions[0] == 40, "First verse should be at top_margin"
    assert verse_positions[1] == 160, "Second verse should be at top_margin + spacing"
    assert verse_positions[2] == 280, "Third verse should be at top_margin + 2*spacing"


def test_scrolling_clips_uses_scrolling_for_many_verses():
    """Test that VideoRenderer uses scrolling layout for > 6 verses."""
    renderer = VideoRenderer(resolution=(1280, 720), fps=30)

    # Create 7 verses (triggers scrolling)
    verses = [(f"Verse {i}", f"Text {i}") for i in range(1, 8)]
    pasuk_alignments = [
        PasukAlignment(
            alignment_run_id=1,
            reference=f"Verse {i}",
            hebrew_text=f"Text {i}",
            verse_order=i,
            start_time=i * 5.0,
            end_time=(i + 1) * 5.0,
            confidence=0.95,
        )
        for i in range(1, 8)
    ]

    alignment_run = AlignmentRun(
        alya_audio_id=1,
        alignment_quality=0.93,
        verse_count=7,
    )

    clips = renderer._create_text_clips(
        alignment_run=alignment_run,
        verses=verses,
        audio_duration=50.0,
        pasuk_alignments=pasuk_alignments,
    )

    # Should create 1 normal scrolling layer + 7 highlight layers = 8 clips
    assert len(clips) == 8, f"Expected 8 clips (1 normal + 7 highlights), got {len(clips)}"

    # First clip should be the scrolling normal layer
    normal_clip = clips[0]
    assert normal_clip.duration == 50.0, "Normal clip duration should match audio"

    # Check that position function exists (indicates scrolling)
    assert hasattr(normal_clip, 'pos'), "Normal clip should have position function for scrolling"


def test_scrolling_clips_uses_static_for_few_verses():
    """Test that VideoRenderer uses static layout for <= 6 verses."""
    renderer = VideoRenderer(resolution=(1280, 720), fps=30)

    # Create 5 verses (uses static layout)
    verses = [(f"Verse {i}", f"Text {i}") for i in range(1, 6)]
    pasuk_alignments = [
        PasukAlignment(
            alignment_run_id=1,
            reference=f"Verse {i}",
            hebrew_text=f"Text {i}",
            verse_order=i,
            start_time=i * 5.0,
            end_time=(i + 1) * 5.0,
            confidence=0.95,
        )
        for i in range(1, 6)
    ]

    alignment_run = AlignmentRun(
        alya_audio_id=1,
        alignment_quality=0.93,
        verse_count=5,
    )

    clips = renderer._create_text_clips(
        alignment_run=alignment_run,
        verses=verses,
        audio_duration=30.0,
        pasuk_alignments=pasuk_alignments,
    )

    # Should create 5 verses × 2 layers = 10 clips (static layout)
    assert len(clips) == 10, f"Expected 10 clips (5 verses × 2 layers), got {len(clips)}"


def test_scrolling_clips_threshold_at_six_verses():
    """Test that exactly 6 verses uses static, 7 uses scrolling."""
    renderer = VideoRenderer(resolution=(1280, 720), fps=30)

    # Test with exactly 6 verses (static)
    verses_6 = [(f"Verse {i}", f"Text {i}") for i in range(1, 7)]
    pasuk_alignments_6 = [
        PasukAlignment(
            alignment_run_id=1,
            reference=f"Verse {i}",
            hebrew_text=f"Text {i}",
            verse_order=i,
            start_time=i * 5.0,
            end_time=(i + 1) * 5.0,
            confidence=0.95,
        )
        for i in range(1, 7)
    ]

    alignment_run = AlignmentRun(
        alya_audio_id=1,
        alignment_quality=0.93,
        verse_count=6,
    )

    clips_6 = renderer._create_text_clips(
        alignment_run=alignment_run,
        verses=verses_6,
        audio_duration=35.0,
        pasuk_alignments=pasuk_alignments_6,
    )

    # 6 verses should use static (6 × 2 = 12 clips)
    assert len(clips_6) == 12, f"6 verses should use static layout (12 clips), got {len(clips_6)}"

    # Test with 7 verses (scrolling)
    verses_7 = [(f"Verse {i}", f"Text {i}") for i in range(1, 8)]
    pasuk_alignments_7 = [
        PasukAlignment(
            alignment_run_id=1,
            reference=f"Verse {i}",
            hebrew_text=f"Text {i}",
            verse_order=i,
            start_time=i * 5.0,
            end_time=(i + 1) * 5.0,
            confidence=0.95,
        )
        for i in range(1, 8)
    ]

    alignment_run_7 = AlignmentRun(
        alya_audio_id=1,
        alignment_quality=0.93,
        verse_count=7,
    )

    clips_7 = renderer._create_text_clips(
        alignment_run=alignment_run_7,
        verses=verses_7,
        audio_duration=40.0,
        pasuk_alignments=pasuk_alignments_7,
    )

    # 7 verses should use scrolling (1 + 7 = 8 clips)
    assert len(clips_7) == 8, f"7 verses should use scrolling layout (8 clips), got {len(clips_7)}"


def test_scrolling_clips_handles_many_verses():
    """Test that scrolling works with many verses (10+)."""
    renderer = VideoRenderer(resolution=(1280, 720), fps=30)

    # Create 15 verses
    verses = [(f"Verse {i}", f"Text {i}") for i in range(1, 16)]
    pasuk_alignments = [
        PasukAlignment(
            alignment_run_id=1,
            reference=f"Verse {i}",
            hebrew_text=f"Text {i}",
            verse_order=i,
            start_time=i * 4.0,
            end_time=(i + 1) * 4.0,
            confidence=0.95,
        )
        for i in range(1, 16)
    ]

    alignment_run = AlignmentRun(
        alya_audio_id=1,
        alignment_quality=0.93,
        verse_count=15,
    )

    clips = renderer._create_text_clips(
        alignment_run=alignment_run,
        verses=verses,
        audio_duration=64.0,
        pasuk_alignments=pasuk_alignments,
    )

    # Should create 1 normal + 15 highlight layers = 16 clips
    assert len(clips) == 16, f"Expected 16 clips (1 normal + 15 highlights), got {len(clips)}"
