# Generated by Claude Code
"""VideoRenderer for creating synchronized videos with Hebrew text overlay."""

from pathlib import Path

from bidi.algorithm import get_display
from moviepy import (
    AudioFileClip,
    ColorClip,
    CompositeVideoClip,
    TextClip,
    concatenate_videoclips,
)

from src.lib.config import get_font_path, settings
from src.lib.exceptions import VideoRenderError
from src.lib.logging import get_logger
from src.models.timestamp_map import TimestampMap
from src.models.video import SynchronizedVideo

logger = get_logger(__name__)


class VideoRenderer:
    """Renderer for synchronized Torah reading videos with text overlay.

    Creates MP4 videos with scrolling Hebrew text that highlights in sync
    with audio playback.
    """

    def __init__(
        self,
        resolution: tuple[int, int] | None = None,
        fps: int | None = None,
        font_path: Path | None = None,
    ) -> None:
        """Initialize video renderer.

        Args:
            resolution: Video resolution (width, height) - default from config
            fps: Frames per second - default from config
            font_path: Path to Hebrew font - default from config
        """
        self.resolution = tuple(resolution) if resolution else tuple(
            settings.get("video.resolution", [640, 360])
        )
        self.fps = fps or settings.get("video.fps", 30)
        self.font_path = font_path or get_font_path()
        self.font_size = settings.get("video.font_size", 20)
        self.highlight_color = settings.get("video.highlight_color", "#FFD700")
        self.normal_color = settings.get("video.normal_color", "#FFFFFF")

        logger.debug(
            f"Initialized VideoRenderer",
            resolution=self.resolution,
            fps=self.fps,
            font_path=str(self.font_path),
        )

    def render(
        self,
        audio_file: Path,
        timestamp_map: TimestampMap,
        output_path: Path,
        verses: list[tuple[str, str]] | None = None,
    ) -> SynchronizedVideo:
        """Render synchronized video with text overlay.

        Args:
            audio_file: Path to audio file
            timestamp_map: TimestampMap with verse timestamps
            output_path: Output video file path
            verses: Optional list of (reference, hebrew_text) tuples

        Returns:
            SynchronizedVideo model

        Raises:
            VideoRenderError: If rendering fails
        """
        logger.info(
            f"Starting video render",
            audio_file=str(audio_file),
            verse_count=len(timestamp_map.verse_timestamps),
            output_path=str(output_path),
        )

        try:
            # Load audio
            audio_clip = AudioFileClip(str(audio_file))
            duration = audio_clip.duration

            # Create background
            background = ColorClip(
                size=self.resolution, color=(0, 0, 0), duration=duration
            )  # Black background

            # Create text clips for each verse
            text_clips = self._create_text_clips(timestamp_map, verses)

            # Composite video
            video = CompositeVideoClip([background] + text_clips)
            video = video.with_audio(audio_clip)
            video = video.with_fps(self.fps)

            # Ensure output directory exists
            output_path.parent.mkdir(parents=True, exist_ok=True)

            # Render video
            logger.info(f"Encoding video", codec="libx264", bitrate="1000k")
            video.write_videofile(
                str(output_path),
                codec="libx264",
                audio_codec="aac",
                fps=self.fps,
                preset="medium",
                bitrate="1000k",
                logger=None,  # Suppress moviepy's verbose logging
            )

            # Clean up
            audio_clip.close()
            video.close()

            # Validate output
            if not output_path.exists():
                raise VideoRenderError(f"Video file was not created: {output_path}")

            logger.info(
                f"Video rendered successfully",
                output_path=str(output_path),
                file_size_mb=output_path.stat().st_size / (1024 * 1024),
            )

            # Create SynchronizedVideo model
            return SynchronizedVideo(
                file_path=output_path,
                format="mp4",
                resolution=self.resolution,
                frame_rate=self.fps,
                codec="h264",
                duration_seconds=duration,
                parasha_name=timestamp_map.parasha_name,
                aliyah_name=timestamp_map.aliyah_name,
            )

        except Exception as e:
            raise VideoRenderError(f"Video rendering failed: {e}") from e

    def _create_text_clips(
        self, timestamp_map: TimestampMap, verses: list[tuple[str, str]] | None = None
    ) -> list:
        """Create text clips for each verse with highlighting.

        Args:
            timestamp_map: TimestampMap with verse timestamps
            verses: Optional list of (reference, hebrew_text) tuples

        Returns:
            List of TextClip objects
        """
        text_clips = []
        width, height = self.resolution

        # Create verse lookup dict from verses list
        verse_dict = {}
        if verses:
            verse_dict = {ref: text for ref, text in verses}

        # Calculate vertical spacing
        max_visible_verses = 10
        line_height = height // (max_visible_verses + 2)
        y_start = line_height

        for i, verse_ts in enumerate(timestamp_map.verse_timestamps):
            # Get Hebrew text or fall back to reference
            verse_text = verse_dict.get(verse_ts.reference, verse_ts.reference)

            # Apply bidirectional text reordering for Hebrew RTL display
            # The bidi algorithm properly reorders Hebrew text (RTL) with diacritics for visual display
            # This converts logical order (storage) to visual order (display)
            if verse_text and not verse_text.startswith("Deuteronomy"):
                verse_text = get_display(verse_text)

            # Calculate y position (scroll effect)
            y_position = y_start + (i * line_height)

            # Create highlighted clip (gold) during the verse being read
            highlighted_clip = (
                TextClip(
                    text=verse_text,
                    font_size=self.font_size,
                    color=self.highlight_color,
                    font=str(self.font_path),
                    method="label",
                    size=(width - 40, None),
                )
                .with_position(("center", y_position))
                .with_start(verse_ts.start_time)
                .with_duration(verse_ts.duration)
            )
            text_clips.append(highlighted_clip)

        return text_clips
