# Generated by Claude Sonnet 4.5
"""Contract tests verifying API call reduction through batch fetching."""

from unittest.mock import Mock, call

import pytest

from src.services.text.parasha_fetcher import ParashaTextFetcher
from src.services.text.sefaria_client import SefariaClient


@pytest.fixture
def mock_sefaria_client_with_call_tracking():
    """Create mock SefariaClient that tracks API calls."""
    client = Mock(spec=SefariaClient)
    
    # Mock get_verse to return individual verses
    def mock_get_verse(book, chapter, verse):
        return f"Hebrew text for {book} {chapter}:{verse}"
    
    # Mock get_range to return batch of verses
    def mock_get_range(book, chapter_start, verse_start, chapter_end, verse_end):
        results = []
        for v in range(verse_start, verse_end + 1):
            results.append((f"{book} {chapter_start}:{v}", f"Hebrew text for {book} {chapter_start}:{v}"))
        return results
    
    client.get_verse.side_effect = mock_get_verse
    client.get_range.side_effect = mock_get_range
    
    return client


def test_batch_fetch_reduces_api_calls_haazinu_rishon(mock_sefaria_client_with_call_tracking):
    """Test batch fetch for Haazinu Rishon uses 1 API call instead of 6.

    Performance requirement PR-003: 80% reduction target
    Expected: 6 calls → 1 call = 83% reduction
    """
    fetcher = ParashaTextFetcher(sefaria_client=mock_sefaria_client_with_call_tracking)

    # Batch fetch using ParashaTextFetcher
    verses = fetcher.fetch_aliyah_text("האזינו", "ראשון")
    
    # Verify batch API call
    assert mock_sefaria_client_with_call_tracking.get_range.call_count == 1
    assert mock_sefaria_client_with_call_tracking.get_verse.call_count == 0
    
    # Verify correct parameters
    mock_sefaria_client_with_call_tracking.get_range.assert_called_once_with(
        book="Deuteronomy",
        chapter_start=32,
        verse_start=1,
        chapter_end=32,
        verse_end=6,
    )
    
    # Verify verse count
    assert len(verses) == 6
    
    # Calculate reduction
    naive_calls = 6  # Per-verse approach
    batch_calls = 1  # Batch approach
    reduction_pct = ((naive_calls - batch_calls) / naive_calls) * 100
    
    assert reduction_pct >= 80, f"API call reduction ({reduction_pct:.1f}%) below PR-003 target (80%)"


def test_batch_fetch_reduces_api_calls_haazinu_full_parasha(mock_sefaria_client_with_call_tracking):
    """Test batch fetch for all Haazinu Aliyot uses 7 API calls instead of 52.

    Performance requirement PR-003: 80% reduction target
    Expected: 52 calls → 7 calls = 86.5% reduction
    """
    fetcher = ParashaTextFetcher(sefaria_client=mock_sefaria_client_with_call_tracking)

    # Fetch all 7 Aliyot
    aliyot = ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שביעי"]
    total_verses = 0

    for aliyah in aliyot:
        verses = fetcher.fetch_aliyah_text("האזינו", aliyah)
        total_verses += len(verses)
    
    # Verify batch API calls (one per aliyah)
    assert mock_sefaria_client_with_call_tracking.get_range.call_count == 7
    assert mock_sefaria_client_with_call_tracking.get_verse.call_count == 0
    
    # Verify total verses (Haazinu has 52 verses)
    assert total_verses == 52
    
    # Calculate reduction
    naive_calls = 52  # Per-verse approach
    batch_calls = 7   # Batch approach (one per aliyah)
    reduction_pct = ((naive_calls - batch_calls) / naive_calls) * 100
    
    assert reduction_pct >= 80, f"API call reduction ({reduction_pct:.1f}%) below PR-003 target (80%)"
    print(f"\n✓ API call reduction: {reduction_pct:.1f}% (52 → 7 calls)")


def test_batch_fetch_call_parameters_match_config():
    """Test batch fetch uses correct parameters from aliyah_ranges.toml."""
    client = Mock(spec=SefariaClient)
    client.get_range.return_value = [
        ("Deuteronomy 32:7", "Hebrew 7"),
        ("Deuteronomy 32:8", "Hebrew 8"),
        ("Deuteronomy 32:9", "Hebrew 9"),
        ("Deuteronomy 32:10", "Hebrew 10"),
        ("Deuteronomy 32:11", "Hebrew 11"),
        ("Deuteronomy 32:12", "Hebrew 12"),
    ]
    
    fetcher = ParashaTextFetcher(sefaria_client=client)

    # Fetch Sheni (verses 7-12)
    verses = fetcher.fetch_aliyah_text("האזינו", "שני")
    
    # Verify exact parameters from configuration
    client.get_range.assert_called_once_with(
        book="Deuteronomy",
        chapter_start=32,
        verse_start=7,
        chapter_end=32,
        verse_end=12,
    )
    
    assert len(verses) == 6


def test_performance_comparison_documentation():
    """Document performance improvement metrics for all Haazinu Aliyot.
    
    This test verifies the performance gains match specification claims.
    """
    aliyah_verse_counts = {
        "rishon": 6,   # Verses 1-6
        "sheni": 6,    # Verses 7-12
        "shlishi": 6,  # Verses 13-18
        "revii": 10,   # Verses 19-28
        "chamishi": 11, # Verses 29-39
        "shishi": 4,   # Verses 40-43
        "shevii": 9,   # Verses 44-52
    }
    
    total_verses = sum(aliyah_verse_counts.values())
    assert total_verses == 52, "Haazinu verse count mismatch"
    
    # Naive approach: one API call per verse
    naive_total_calls = total_verses
    
    # Batch approach: one API call per aliyah
    batch_total_calls = len(aliyah_verse_counts)
    
    reduction_pct = ((naive_total_calls - batch_total_calls) / naive_total_calls) * 100
    
    print(f"\nPerformance Improvement (Haazinu):")
    print(f"  Naive approach:  {naive_total_calls} API calls (1 per verse)")
    print(f"  Batch approach:  {batch_total_calls} API calls (1 per aliyah)")
    print(f"  Reduction:       {reduction_pct:.1f}%")
    print(f"  Target (PR-003): 80% minimum")
    
    assert reduction_pct >= 80, f"Performance target not met: {reduction_pct:.1f}% < 80%"
    assert reduction_pct == pytest.approx(86.5, abs=0.1), "Reduction mismatch with spec claim"
