# Generated by Claude Sonnet 4.5
"""Test YouTube DuckDB schema verification."""

import pytest

from src.repositories.db import get_connection


@pytest.mark.integration
def test_youtube_thumbnails_table_exists():
    """Verify youtube_thumbnails table exists."""
    conn = get_connection()
    result = conn.execute("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_name = 'youtube_thumbnails'
    """).fetchone()

    assert result is not None
    assert result[0] == "youtube_thumbnails"


@pytest.mark.integration
def test_youtube_uploads_table_exists():
    """Verify youtube_uploads table exists."""
    conn = get_connection()
    result = conn.execute("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_name = 'youtube_uploads'
    """).fetchone()

    assert result is not None
    assert result[0] == "youtube_uploads"


@pytest.mark.integration
def test_youtube_playlist_meta_table_exists():
    """Verify youtube_playlist_meta table exists."""
    conn = get_connection()
    result = conn.execute("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_name = 'youtube_playlist_meta'
    """).fetchone()

    assert result is not None
    assert result[0] == "youtube_playlist_meta"


@pytest.mark.integration
def test_youtube_thumbnails_has_correct_columns():
    """Verify youtube_thumbnails has correct columns."""
    conn = get_connection()
    result = conn.execute("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = 'youtube_thumbnails'
        ORDER BY column_name
    """).fetchall()

    column_names = [row[0] for row in result]
    expected_columns = [
        "cached_path",
        "downloaded_at",
        "id",
        "original_url",
        "title",
        "video_id",
    ]

    assert sorted(column_names) == sorted(expected_columns)


@pytest.mark.integration
def test_youtube_uploads_has_correct_columns():
    """Verify youtube_uploads has correct columns."""
    conn = get_connection()
    result = conn.execute("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = 'youtube_uploads'
    """).fetchall()

    column_names = [row[0] for row in result]
    expected_columns = [
        "added_to_playlist",
        "alya_video_id",
        "completed_at",
        "error_message",
        "id",
        "new_youtube_video_id",
        "old_youtube_video_id",
        "thumbnail_restored",
        "upload_status",
        "uploaded_at",
    ]

    assert sorted(column_names) == sorted(expected_columns)


@pytest.mark.integration
def test_youtube_playlist_meta_has_correct_columns():
    """Verify youtube_playlist_meta has correct columns."""
    conn = get_connection()
    result = conn.execute("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_name = 'youtube_playlist_meta'
    """).fetchall()

    column_names = [row[0] for row in result]
    expected_columns = [
        "created_at",
        "description",
        "expected_video_count",
        "id",
        "playlist_id",
        "privacy_status",
        "title",
        "tradition",
        "updated_at",
        "video_count",
        "youtube_playlist_id",
    ]

    assert sorted(column_names) == sorted(expected_columns)
