# Generated by Claude Sonnet 4.5
"""Integration tests for YouTube repositories with DuckDB."""

from datetime import datetime
from pathlib import Path

import duckdb
import pytest

from src.repositories.youtube_playlist_meta_repo import (
    YouTubePlaylistMetaRepository,
)
from src.repositories.youtube_thumbnail_repo import YouTubeThumbnailRepository
from src.repositories.youtube_upload_repo import YouTubeUploadRepository


@pytest.fixture
def test_db(tmp_path):
    """Create test DuckDB database with YouTube schema."""
    db_path = tmp_path / "test_youtube.duckdb"
    conn = duckdb.connect(str(db_path))

    # Create sequences
    for seq in (
        "seq_playlists",
        "seq_alyot",
        "seq_alya_videos",
        "seq_youtube_thumbnails",
        "seq_youtube_uploads",
        "seq_youtube_playlist_meta",
    ):
        conn.execute(f"CREATE SEQUENCE IF NOT EXISTS {seq}")

    # Create base tables (minimal for testing)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS playlists (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_playlists'),
            name VARCHAR NOT NULL,
            book VARCHAR NOT NULL,
            chapter_start INTEGER NOT NULL,
            verse_start INTEGER NOT NULL,
            chapter_end INTEGER NOT NULL,
            verse_end INTEGER NOT NULL,
            youtube_playlist_id VARCHAR,
            created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS alyot (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_alyot'),
            playlist_id INTEGER NOT NULL REFERENCES playlists(id),
            name VARCHAR NOT NULL,
            order_num INTEGER NOT NULL,
            state VARCHAR NOT NULL DEFAULT 'pending',
            created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS alya_videos (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_alya_videos'),
            alya_id INTEGER NOT NULL REFERENCES alyot(id),
            file_path VARCHAR NOT NULL,
            format VARCHAR NOT NULL,
            resolution_w INTEGER NOT NULL,
            resolution_h INTEGER NOT NULL,
            frame_rate INTEGER NOT NULL,
            codec VARCHAR NOT NULL,
            duration_seconds DOUBLE NOT NULL,
            youtube_video_id VARCHAR,
            created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
        )
    """)

    # Create YouTube tables
    conn.execute("""
        CREATE TABLE IF NOT EXISTS youtube_thumbnails (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_youtube_thumbnails'),
            video_id VARCHAR NOT NULL UNIQUE,
            original_url VARCHAR NOT NULL,
            cached_path VARCHAR NOT NULL,
            title VARCHAR,
            downloaded_at TIMESTAMP NOT NULL DEFAULT current_timestamp
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS youtube_uploads (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_youtube_uploads'),
            alya_video_id INTEGER NOT NULL REFERENCES alya_videos(id),
            old_youtube_video_id VARCHAR,
            new_youtube_video_id VARCHAR NOT NULL,
            thumbnail_restored BOOLEAN NOT NULL DEFAULT false,
            added_to_playlist BOOLEAN NOT NULL DEFAULT false,
            upload_status VARCHAR NOT NULL DEFAULT 'pending',
            error_message VARCHAR,
            uploaded_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
            completed_at TIMESTAMP
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS youtube_playlist_meta (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_youtube_playlist_meta'),
            playlist_id INTEGER NOT NULL UNIQUE REFERENCES playlists(id),
            youtube_playlist_id VARCHAR NOT NULL UNIQUE,
            title VARCHAR NOT NULL,
            description VARCHAR,
            privacy_status VARCHAR NOT NULL DEFAULT 'unlisted',
            tradition VARCHAR NOT NULL DEFAULT 'Ashkenaz',
            video_count INTEGER NOT NULL DEFAULT 0,
            expected_video_count INTEGER NOT NULL DEFAULT 7,
            created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
            updated_at TIMESTAMP NOT NULL DEFAULT current_timestamp
        )
    """)

    yield conn
    conn.close()


@pytest.fixture
def thumbnail_repo(test_db):
    """Create YouTubeThumbnailRepository with test database."""
    return YouTubeThumbnailRepository(conn=test_db)


@pytest.fixture
def upload_repo(test_db):
    """Create YouTubeUploadRepository with test database."""
    return YouTubeUploadRepository(conn=test_db)


@pytest.fixture
def playlist_meta_repo(test_db):
    """Create YouTubePlaylistMetaRepository with test database."""
    return YouTubePlaylistMetaRepository(conn=test_db)


@pytest.fixture
def sample_playlist(test_db):
    """Create a sample playlist for testing."""
    test_db.execute("""
        INSERT INTO playlists (name, book, chapter_start, verse_start, chapter_end, verse_end)
        VALUES ('פרשת בראשית', 'Genesis', 1, 1, 2, 3)
    """)
    result = test_db.execute("SELECT id FROM playlists WHERE name = 'פרשת בראשית'").fetchone()
    return result[0]


@pytest.fixture
def sample_alya_video(test_db, sample_playlist):
    """Create sample alya and video for testing."""
    # Create alya
    test_db.execute("""
        INSERT INTO alyot (playlist_id, name, order_num)
        VALUES (?, 'ראשון', 1)
    """, [sample_playlist])
    alya_id = test_db.execute("SELECT id FROM alyot WHERE name = 'ראשון'").fetchone()[0]

    # Create video
    test_db.execute("""
        INSERT INTO alya_videos (
            alya_id, file_path, format, resolution_w, resolution_h,
            frame_rate, codec, duration_seconds
        ) VALUES (?, '/tmp/test.mp4', 'mp4', 1280, 720, 30, 'h264', 120.0)
    """, [alya_id])
    video_id = test_db.execute("SELECT id FROM alya_videos WHERE alya_id = ?", [alya_id]).fetchone()[0]

    return {"alya_id": alya_id, "video_id": video_id}


class TestYouTubeThumbnailRepository:
    """Tests for YouTubeThumbnailRepository."""

    def test_save_thumbnail(self, thumbnail_repo, tmp_path):
        """Test saving thumbnail metadata."""
        thumb_path = tmp_path / "thumb.jpg"
        thumb_path.write_text("fake thumbnail")

        thumbnail = thumbnail_repo.save_thumbnail(
            video_id="abc123",
            original_url="https://example.com/thumb.jpg",
            cached_path=thumb_path,
            title="Test Video",
        )

        assert thumbnail.id > 0
        assert thumbnail.video_id == "abc123"
        assert thumbnail.cached_path == thumb_path
        assert thumbnail.title == "Test Video"

    def test_get_by_video_id(self, thumbnail_repo, tmp_path):
        """Test retrieving thumbnail by video ID."""
        thumb_path = tmp_path / "thumb.jpg"
        thumb_path.write_text("fake thumbnail")

        # Save first
        thumbnail_repo.save_thumbnail(
            video_id="abc123",
            original_url="https://example.com/thumb.jpg",
            cached_path=thumb_path,
        )

        # Retrieve
        retrieved = thumbnail_repo.get_by_video_id("abc123")
        assert retrieved is not None
        assert retrieved.video_id == "abc123"

    def test_get_by_video_id_not_found(self, thumbnail_repo):
        """Test retrieving non-existent thumbnail."""
        retrieved = thumbnail_repo.get_by_video_id("nonexistent")
        assert retrieved is None

    def test_list_all(self, thumbnail_repo, tmp_path):
        """Test listing all thumbnails."""
        # Save multiple thumbnails
        for i in range(3):
            thumb_path = tmp_path / f"thumb{i}.jpg"
            thumb_path.write_text(f"fake thumbnail {i}")
            thumbnail_repo.save_thumbnail(
                video_id=f"vid{i}",
                original_url=f"https://example.com/thumb{i}.jpg",
                cached_path=thumb_path,
            )

        # List all
        thumbnails = thumbnail_repo.list_all()
        assert len(thumbnails) == 3
        # Should be ordered by downloaded_at DESC
        assert thumbnails[0].video_id == "vid2"

    def test_delete_by_video_id(self, thumbnail_repo, tmp_path):
        """Test deleting thumbnail metadata."""
        thumb_path = tmp_path / "thumb.jpg"
        thumb_path.write_text("fake thumbnail")

        thumbnail_repo.save_thumbnail(
            video_id="abc123",
            original_url="https://example.com/thumb.jpg",
            cached_path=thumb_path,
        )

        # Delete
        deleted = thumbnail_repo.delete_by_video_id("abc123")
        assert deleted

        # Verify deleted
        retrieved = thumbnail_repo.get_by_video_id("abc123")
        assert retrieved is None

    def test_delete_by_video_id_not_found(self, thumbnail_repo):
        """Test deleting non-existent thumbnail."""
        deleted = thumbnail_repo.delete_by_video_id("nonexistent")
        assert not deleted


class TestYouTubeUploadRepository:
    """Tests for YouTubeUploadRepository."""

    def test_create_upload(self, upload_repo, sample_alya_video):
        """Test creating upload record."""
        upload = upload_repo.create_upload(
            alya_video_id=sample_alya_video["video_id"],
            new_youtube_video_id="new123",
            old_youtube_video_id="old123",
        )

        assert upload.id > 0
        assert upload.alya_video_id == sample_alya_video["video_id"]
        assert upload.new_youtube_video_id == "new123"
        assert upload.old_youtube_video_id == "old123"
        assert upload.upload_status == "pending"

    def test_update_status(self, upload_repo, sample_alya_video):
        """Test updating upload status."""
        upload = upload_repo.create_upload(
            alya_video_id=sample_alya_video["video_id"],
            new_youtube_video_id="new123",
        )

        # Update status
        updated = upload_repo.update_status(
            upload_id=upload.id,
            status="completed",
            thumbnail_restored=True,
            added_to_playlist=True,
        )

        assert updated.upload_status == "completed"
        assert updated.thumbnail_restored
        assert updated.added_to_playlist
        assert updated.completed_at is not None

    def test_get_by_alya_video(self, upload_repo, sample_alya_video):
        """Test retrieving upload by alya video ID."""
        upload_repo.create_upload(
            alya_video_id=sample_alya_video["video_id"],
            new_youtube_video_id="new123",
        )

        retrieved = upload_repo.get_by_alya_video(sample_alya_video["video_id"])
        assert retrieved is not None
        assert retrieved.alya_video_id == sample_alya_video["video_id"]

    def test_get_by_id(self, upload_repo, sample_alya_video):
        """Test retrieving upload by ID."""
        upload = upload_repo.create_upload(
            alya_video_id=sample_alya_video["video_id"],
            new_youtube_video_id="new123",
        )

        retrieved = upload_repo.get_by_id(upload.id)
        assert retrieved is not None
        assert retrieved.id == upload.id

    def test_list_pending(self, upload_repo, sample_alya_video):
        """Test listing pending uploads."""
        # Create multiple uploads with different statuses
        upload1 = upload_repo.create_upload(
            alya_video_id=sample_alya_video["video_id"],
            new_youtube_video_id="new123",
        )

        # Create another alya/video for second upload
        test_db = upload_repo.conn
        test_db.execute("""
            INSERT INTO alyot (playlist_id, name, order_num)
            SELECT playlist_id, 'שני', 2 FROM alyot WHERE id = ?
        """, [sample_alya_video["alya_id"]])
        alya_id2 = test_db.execute("SELECT id FROM alyot WHERE name = 'שני'").fetchone()[0]

        test_db.execute("""
            INSERT INTO alya_videos (
                alya_id, file_path, format, resolution_w, resolution_h,
                frame_rate, codec, duration_seconds
            ) VALUES (?, '/tmp/test2.mp4', 'mp4', 1280, 720, 30, 'h264', 120.0)
        """, [alya_id2])
        video_id2 = test_db.execute("SELECT id FROM alya_videos WHERE alya_id = ?", [alya_id2]).fetchone()[0]

        upload2 = upload_repo.create_upload(
            alya_video_id=video_id2,
            new_youtube_video_id="new456",
        )

        # Update one to completed
        upload_repo.update_status(upload1.id, "completed")

        # List pending
        pending = upload_repo.list_pending()
        assert len(pending) == 1
        assert pending[0].id == upload2.id

    def test_list_all(self, upload_repo, sample_alya_video):
        """Test listing all uploads."""
        upload_repo.create_upload(
            alya_video_id=sample_alya_video["video_id"],
            new_youtube_video_id="new123",
        )

        uploads = upload_repo.list_all()
        assert len(uploads) >= 1


class TestYouTubePlaylistMetaRepository:
    """Tests for YouTubePlaylistMetaRepository."""

    def test_create_meta(self, playlist_meta_repo, sample_playlist):
        """Test creating playlist metadata."""
        playlist_meta_repo.create_meta(
            playlist_id=sample_playlist,
            youtube_playlist_id="PLxyz123",
            title="פרשת בראשית - Ashkenaz | CIFRIA",
            description="Test description",
            tradition="Ashkenaz",
        )

        # Verify created
        playlist = playlist_meta_repo.get_by_playlist(sample_playlist)
        assert playlist is not None
        assert playlist.youtube_playlist_id == "PLxyz123"
        assert playlist.title == "פרשת בראשית - Ashkenaz | CIFRIA"

    def test_get_by_playlist(self, playlist_meta_repo, sample_playlist):
        """Test retrieving playlist metadata."""
        playlist_meta_repo.create_meta(
            playlist_id=sample_playlist,
            youtube_playlist_id="PLxyz123",
            title="Test Playlist",
            description="Test",
        )

        retrieved = playlist_meta_repo.get_by_playlist(sample_playlist)
        assert retrieved is not None
        assert retrieved.playlist_id == sample_playlist

    def test_get_by_youtube_id(self, playlist_meta_repo, sample_playlist):
        """Test retrieving playlist by YouTube ID."""
        playlist_meta_repo.create_meta(
            playlist_id=sample_playlist,
            youtube_playlist_id="PLxyz123",
            title="Test Playlist",
            description="Test",
        )

        retrieved = playlist_meta_repo.get_by_youtube_id("PLxyz123")
        assert retrieved is not None
        assert retrieved.youtube_playlist_id == "PLxyz123"

    def test_update_video_count(self, playlist_meta_repo, sample_playlist):
        """Test updating video count."""
        playlist_meta_repo.create_meta(
            playlist_id=sample_playlist,
            youtube_playlist_id="PLxyz123",
            title="Test",
            description="Test",
        )

        playlist_meta_repo.update_video_count(sample_playlist, 5)

        retrieved = playlist_meta_repo.get_by_playlist(sample_playlist)
        assert len(retrieved.video_ids) == 5  # Assuming 5 videos added

    def test_is_complete(self, playlist_meta_repo, sample_playlist):
        """Test checking if playlist is complete."""
        playlist_meta_repo.create_meta(
            playlist_id=sample_playlist,
            youtube_playlist_id="PLxyz123",
            title="Test",
            description="Test",
            expected_video_count=7,
        )

        # Initially not complete
        assert not playlist_meta_repo.is_complete(sample_playlist)

        # Update to complete
        playlist_meta_repo.update_video_count(sample_playlist, 7)
        assert playlist_meta_repo.is_complete(sample_playlist)

    def test_list_all(self, playlist_meta_repo, sample_playlist, test_db):
        """Test listing all playlist metadata."""
        playlist_meta_repo.create_meta(
            playlist_id=sample_playlist,
            youtube_playlist_id="PLxyz123",
            title="Test 1",
            description="Test",
        )

        # Create another playlist
        test_db.execute("""
            INSERT INTO playlists (name, book, chapter_start, verse_start, chapter_end, verse_end)
            VALUES ('פרשת נח', 'Genesis', 6, 9, 11, 32)
        """)
        playlist_id2 = test_db.execute("SELECT id FROM playlists WHERE name = 'פרשת נח'").fetchone()[0]

        playlist_meta_repo.create_meta(
            playlist_id=playlist_id2,
            youtube_playlist_id="PLabc456",
            title="Test 2",
            description="Test",
        )

        playlists = playlist_meta_repo.list_all()
        assert len(playlists) == 2
