# Generated by Claude Sonnet 4.5
"""YouTube OAuth2 authentication service."""

import logging
import pickle
from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow

logger = logging.getLogger(__name__)

# YouTube API scopes
# - youtube.upload: Upload videos
# - youtube.force-ssl: Full account access (playlists, metadata, thumbnails)
SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube.force-ssl",
]


class YouTubeAuth:
    """Handles YouTube OAuth2 authentication.

    Manages OAuth2 credentials with automatic token refresh and
    pickle-based persistence.

    Attributes:
        client_secrets_path: Path to OAuth2 client secrets JSON file
        token_path: Path to store pickled access token
    """

    def __init__(
        self,
        client_secrets_path: Path,
        token_path: Path = Path("config/youtube_token.pickle"),
    ):
        """Initialize YouTube authentication.

        Args:
            client_secrets_path: Path to OAuth2 client secrets JSON
            token_path: Path to store access token (default: config/youtube_token.pickle)

        Raises:
            FileNotFoundError: If client_secrets_path doesn't exist
        """
        if not client_secrets_path.exists():
            raise FileNotFoundError(
                f"Client secrets not found: {client_secrets_path}. "
                "Download from Google Cloud Console and save to this path."
            )

        self.client_secrets_path = client_secrets_path
        self.token_path = token_path
        logger.debug(f"{client_secrets_path=}, {token_path=}")

    def get_credentials(self) -> Credentials:
        """Get valid YouTube API credentials.

        Workflow:
        1. Check if token exists and load it
        2. If expired, refresh the token
        3. If no token or refresh fails, run OAuth2 flow (browser popup)
        4. Save credentials for future use

        Returns:
            Valid OAuth2 credentials

        Raises:
            FileNotFoundError: If client secrets not found
            Exception: If OAuth2 flow fails
        """
        creds = None

        # Load existing token
        if self.token_path.exists():
            logger.debug(f"Loading existing token from {self.token_path}")
            with open(self.token_path, "rb") as token_file:
                creds = pickle.load(token_file)
            logger.info("Loaded existing credentials")

        # Refresh or obtain new credentials
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                logger.info("Refreshing expired credentials")
                try:
                    creds.refresh(Request())
                    logger.info("Credentials refreshed successfully")
                except Exception as e:
                    logger.warning(f"Token refresh failed: {e}")
                    logger.info("Starting new OAuth2 flow")
                    creds = self._run_oauth_flow()
            else:
                logger.info("No valid credentials found, starting OAuth2 flow")
                creds = self._run_oauth_flow()

            # Save credentials
            self.token_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self.token_path, "wb") as token_file:
                pickle.dump(creds, token_file)
            logger.info(f"Saved credentials to {self.token_path}")

        return creds

    def _run_oauth_flow(self) -> Credentials:
        """Run OAuth2 flow to obtain credentials.

        Opens a browser window for user to authorize the application.

        Returns:
            OAuth2 credentials

        Raises:
            Exception: If OAuth2 flow fails
        """
        logger.info("Starting OAuth2 flow (will open browser)")

        flow = InstalledAppFlow.from_client_secrets_file(
            str(self.client_secrets_path), SCOPES
        )

        # Run local server on port 0 (random available port)
        creds = flow.run_local_server(port=0)

        logger.info("OAuth2 flow completed successfully")
        return creds

    def clear_credentials(self) -> None:
        """Clear stored credentials.

        Deletes the token file, forcing re-authentication on next use.
        """
        if self.token_path.exists():
            self.token_path.unlink()
            logger.info(f"Cleared credentials: {self.token_path}")
        else:
            logger.debug("No credentials to clear")
