# Generated by Claude Sonnet 4.5
"""YouTube channel scanner to list all videos."""

import logging

from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from src.models.youtube_video import YouTubeVideo
from src.services.youtube.auth import YouTubeAuth

logger = logging.getLogger(__name__)


class ChannelScanner:
    """Scans YouTube channel and lists all videos with metadata."""

    def __init__(self, auth: YouTubeAuth):
        """Initialize channel scanner.

        Args:
            auth: YouTube authentication service
        """
        self.auth = auth
        self._youtube = None

    @property
    def youtube(self):
        """Lazy-load YouTube API service."""
        if not self._youtube:
            creds = self.auth.get_credentials()
            self._youtube = build("youtube", "v3", credentials=creds)
        return self._youtube

    def get_channel_id_from_handle(self, handle: str) -> str:
        """Get channel ID from custom handle/username.

        Args:
            handle: Channel handle (e.g., "@קריאהבתורהמפייוסףבודנהיימר")

        Returns:
            Channel ID

        Raises:
            ValueError: If channel not found
            HttpError: If API request fails
        """
        logger.debug(f"{handle=}")

        # Remove @ prefix if present
        handle = handle.lstrip("@")

        try:
            # Search for channel by handle
            response = self.youtube.channels().list(
                part="id",
                forHandle=handle
            ).execute()

            if "items" not in response or not response["items"]:
                raise ValueError(f"Channel not found: {handle}")

            channel_id = response["items"][0]["id"]
            logger.info(f"Found channel ID: {channel_id}")
            return channel_id

        except HttpError as e:
            logger.error(f"Failed to get channel ID: {e}")
            raise

    def list_all_videos(
        self,
        channel_id: str,
        max_results: int = 50
    ) -> list[YouTubeVideo]:
        """List all videos from a channel.

        Args:
            channel_id: YouTube channel ID
            max_results: Maximum videos per page (max 50)

        Returns:
            List of YouTubeVideo objects

        Raises:
            HttpError: If API request fails
        """
        logger.info(f"Listing videos from channel: {channel_id}")

        videos = []
        next_page_token = None

        # Get channel uploads playlist
        try:
            response = self.youtube.channels().list(
                part="contentDetails",
                id=channel_id
            ).execute()

            if "items" not in response or not response["items"]:
                logger.warning(f"Channel not found: {channel_id}")
                return videos

            uploads_playlist_id = response["items"][0]["contentDetails"][
                "relatedPlaylists"
            ]["uploads"]

            logger.debug(f"Uploads playlist ID: {uploads_playlist_id}")

        except HttpError as e:
            logger.error(f"Failed to get channel details: {e}")
            raise

        # Get videos from uploads playlist with pagination
        while True:
            try:
                playlist_response = self.youtube.playlistItems().list(
                    part="snippet,contentDetails",
                    playlistId=uploads_playlist_id,
                    maxResults=max_results,
                    pageToken=next_page_token
                ).execute()

                # Extract video details
                for item in playlist_response.get("items", []):
                    video_id = item["contentDetails"]["videoId"]
                    snippet = item["snippet"]

                    # Get best thumbnail URL (maxres > high > default)
                    thumbnails = snippet.get("thumbnails", {})
                    thumbnail_url = (
                        thumbnails.get("maxres", {}).get("url")
                        or thumbnails.get("high", {}).get("url")
                        or thumbnails.get("default", {}).get("url")
                    )

                    if not thumbnail_url:
                        logger.warning(f"No thumbnail URL for {video_id=}")
                        continue

                    video = YouTubeVideo(
                        video_id=video_id,
                        title=snippet.get("title", ""),
                        description=snippet.get("description", ""),
                        thumbnail_url=thumbnail_url,
                        published_at=snippet.get("publishedAt"),
                        privacy_status=snippet.get("privacyStatus", "unlisted")
                    )

                    videos.append(video)

                logger.debug(f"Found {len(playlist_response.get('items', []))} videos")

                # Check for more pages
                next_page_token = playlist_response.get("nextPageToken")
                if not next_page_token:
                    break

            except HttpError as e:
                logger.error(f"Failed to list videos: {e}")
                raise

        logger.info(f"Total videos found: {len(videos)}")
        return videos
