# Generated by Claude Sonnet 4.5
"""Thumbnail download, preservation, and restoration service."""

import logging
from pathlib import Path

import httpx

from src.models.youtube_video import YouTubeVideo
from src.repositories.youtube_thumbnail_repo import YouTubeThumbnailRepository

logger = logging.getLogger(__name__)


class ThumbnailManager:
    """Manages thumbnail download, caching, and restoration."""

    def __init__(
        self,
        cache_dir: Path = Path("data/thumbnails"),
        thumbnail_repo: YouTubeThumbnailRepository | None = None
    ):
        """Initialize thumbnail manager.

        Args:
            cache_dir: Directory to cache downloaded thumbnails
            thumbnail_repo: Repository for thumbnail metadata (uses default if None)
        """
        self.cache_dir = cache_dir
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.thumbnail_repo = thumbnail_repo or YouTubeThumbnailRepository()

    def download_thumbnail(self, video: YouTubeVideo) -> Path:
        """Download and cache thumbnail for a video.

        Args:
            video: YouTube video with thumbnail URL

        Returns:
            Path to cached thumbnail

        Raises:
            httpx.HTTPError: If download fails
        """
        logger.info(f"Downloading thumbnail for video: {video.video_id}")

        # Check if already cached
        cached_thumbnail = self.thumbnail_repo.get_by_video_id(video.video_id)
        if cached_thumbnail and cached_thumbnail.exists():
            logger.debug(f"Thumbnail already cached: {cached_thumbnail.cached_path}")
            video.thumbnail_local_path = cached_thumbnail.cached_path
            return cached_thumbnail.cached_path

        # Determine file extension from URL
        url = video.thumbnail_url
        ext = ".jpg"  # Default to jpg
        if "default.jpg" in url or "hqdefault.jpg" in url:
            ext = ".jpg"

        cached_path = self.cache_dir / f"{video.video_id}{ext}"

        # Download thumbnail
        try:
            response = httpx.get(url, timeout=30.0, follow_redirects=True)
            response.raise_for_status()

            # Save to cache
            with open(cached_path, "wb") as f:
                f.write(response.content)

            logger.debug(f"Downloaded {len(response.content)} bytes to {cached_path}")

            # Save metadata to DuckDB
            self.thumbnail_repo.save_thumbnail(
                video_id=video.video_id,
                original_url=video.thumbnail_url,
                cached_path=cached_path,
                title=video.title
            )

            video.thumbnail_local_path = cached_path
            logger.info(f"Thumbnail cached: {cached_path}")
            return cached_path

        except httpx.HTTPError as e:
            logger.error(f"Failed to download thumbnail: {e}")
            raise

    def download_all_thumbnails(
        self,
        videos: list[YouTubeVideo]
    ) -> dict[str, Path]:
        """Download thumbnails for all videos in batch.

        Args:
            videos: List of YouTube videos

        Returns:
            Dictionary mapping video_id to cached thumbnail path
        """
        logger.info(f"Downloading {len(videos)} thumbnails")

        results = {}
        for i, video in enumerate(videos, 1):
            try:
                logger.debug(f"Processing {i}/{len(videos)}: {video.video_id}")
                thumbnail_path = self.download_thumbnail(video)
                results[video.video_id] = thumbnail_path
            except Exception as e:
                logger.warning(
                    f"Failed to download thumbnail for {video.video_id}: {e}"
                )
                continue

        logger.info(f"Successfully downloaded {len(results)} thumbnails")
        return results

    def get_cached_thumbnail(self, video_id: str) -> Path | None:
        """Get cached thumbnail path for a video.

        Queries DuckDB and verifies file exists on disk.

        Args:
            video_id: YouTube video ID

        Returns:
            Path to cached thumbnail or None if not cached or file missing
        """
        logger.debug(f"{video_id=}")

        thumbnail = self.thumbnail_repo.get_by_video_id(video_id)

        if not thumbnail:
            logger.debug(f"Thumbnail not in cache: {video_id=}")
            return None

        if not thumbnail.exists():
            logger.warning(
                f"Thumbnail record exists but file missing: {thumbnail.cached_path}"
            )
            return None

        logger.debug(f"Found cached thumbnail: {thumbnail.cached_path}")
        return thumbnail.cached_path
