# Generated by Claude Opus 4.6
"""Repository for AlignmentRun entities."""

from src.models.alignment_run import AlignmentRun
from src.repositories.db import get_connection


class AlignmentRunRepository:
    """CRUD operations for the alignment_runs table."""

    def insert(self, run: AlignmentRun) -> AlignmentRun:
        """Insert a new alignment run and return it with the generated id."""
        conn = get_connection()
        result = conn.execute(
            """
            INSERT INTO alignment_runs
                (alya_id, audio_file_path, audio_duration_seconds, alignment_quality,
                 verse_count, timestamps_json, manual_corrections, manually_corrected,
                 corrected_at, backup_path, original_quality)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING id
            """,
            [
                run.alya_id,
                run.audio_file_path,
                run.audio_duration_seconds,
                run.alignment_quality,
                run.verse_count,
                run.timestamps_json,
                run.manual_corrections,
                run.manually_corrected,
                run.corrected_at,
                run.backup_path,
                run.original_quality,
            ],
        ).fetchone()
        run.id = result[0]
        return run

    def get_by_id(self, run_id: int) -> AlignmentRun | None:
        """Get an alignment run by id."""
        conn = get_connection()
        row = conn.execute("SELECT * FROM alignment_runs WHERE id = ?", [run_id]).fetchone()
        if row is None:
            return None
        return self._row_to_model(row)

    def get_latest_by_alya(self, alya_id: int) -> AlignmentRun | None:
        """Get the most recent alignment run for an alya."""
        conn = get_connection()
        row = conn.execute(
            "SELECT * FROM alignment_runs WHERE alya_id = ? ORDER BY generated_at DESC LIMIT 1",
            [alya_id],
        ).fetchone()
        if row is None:
            return None
        return self._row_to_model(row)

    def list_by_alya(self, alya_id: int) -> list[AlignmentRun]:
        """List all alignment runs for an alya."""
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM alignment_runs WHERE alya_id = ? ORDER BY generated_at DESC",
            [alya_id],
        ).fetchall()
        return [self._row_to_model(row) for row in rows]

    def list_all(self) -> list[AlignmentRun]:
        """List all alignment runs."""
        conn = get_connection()
        rows = conn.execute("SELECT * FROM alignment_runs ORDER BY id").fetchall()
        return [self._row_to_model(row) for row in rows]

    def update(self, run: AlignmentRun) -> None:
        """Update an existing alignment run."""
        conn = get_connection()
        conn.execute(
            """
            UPDATE alignment_runs
            SET alya_id = ?, audio_file_path = ?, audio_duration_seconds = ?,
                alignment_quality = ?, verse_count = ?, timestamps_json = ?,
                manual_corrections = ?, manually_corrected = ?, corrected_at = ?,
                backup_path = ?, original_quality = ?
            WHERE id = ?
            """,
            [
                run.alya_id,
                run.audio_file_path,
                run.audio_duration_seconds,
                run.alignment_quality,
                run.verse_count,
                run.timestamps_json,
                run.manual_corrections,
                run.manually_corrected,
                run.corrected_at,
                run.backup_path,
                run.original_quality,
                run.id,
            ],
        )

    def delete(self, run_id: int) -> None:
        """Delete an alignment run by id."""
        conn = get_connection()
        conn.execute("DELETE FROM alignment_runs WHERE id = ?", [run_id])

    @staticmethod
    def _row_to_model(row: tuple) -> AlignmentRun:
        """Convert a database row to an AlignmentRun model."""
        return AlignmentRun(
            id=row[0],
            alya_id=row[1],
            audio_file_path=row[2],
            audio_duration_seconds=row[3],
            alignment_quality=row[4],
            verse_count=row[5],
            timestamps_json=row[6],
            manual_corrections=row[7],
            manually_corrected=row[8],
            corrected_at=row[9],
            backup_path=row[10],
            original_quality=row[11],
            generated_at=row[12],
        )
