# Generated by Claude Opus 4.6
"""Repository for AlyaVideo entities."""

from src.models.alya_video import AlyaVideo
from src.repositories.db import get_connection


class AlyaVideoRepository:
    """CRUD operations for the alya_videos table."""

    def insert(self, video: AlyaVideo) -> AlyaVideo:
        """Insert a new alya video record and return it with the generated id."""
        conn = get_connection()
        result = conn.execute(
            """
            INSERT INTO alya_videos
                (alya_id, file_path, format, resolution_w, resolution_h, frame_rate, codec, duration_seconds, youtube_video_id)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING id
            """,
            [
                video.alya_id,
                video.file_path,
                video.format,
                video.resolution_w,
                video.resolution_h,
                video.frame_rate,
                video.codec,
                video.duration_seconds,
                video.youtube_video_id,
            ],
        ).fetchone()
        video.id = result[0]
        return video

    def get_by_id(self, video_id: int) -> AlyaVideo | None:
        """Get an alya video by id."""
        conn = get_connection()
        row = conn.execute("SELECT * FROM alya_videos WHERE id = ?", [video_id]).fetchone()
        if row is None:
            return None
        return self._row_to_model(row)

    def list_by_alya(self, alya_id: int) -> list[AlyaVideo]:
        """List all video records for an alya."""
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM alya_videos WHERE alya_id = ? ORDER BY created_at DESC",
            [alya_id],
        ).fetchall()
        return [self._row_to_model(row) for row in rows]

    def list_all(self) -> list[AlyaVideo]:
        """List all alya video records."""
        conn = get_connection()
        rows = conn.execute("SELECT * FROM alya_videos ORDER BY id").fetchall()
        return [self._row_to_model(row) for row in rows]

    def update(self, video: AlyaVideo) -> None:
        """Update an existing alya video record."""
        conn = get_connection()
        conn.execute(
            """
            UPDATE alya_videos
            SET alya_id = ?, file_path = ?, format = ?, resolution_w = ?, resolution_h = ?,
                frame_rate = ?, codec = ?, duration_seconds = ?, youtube_video_id = ?
            WHERE id = ?
            """,
            [
                video.alya_id,
                video.file_path,
                video.format,
                video.resolution_w,
                video.resolution_h,
                video.frame_rate,
                video.codec,
                video.duration_seconds,
                video.youtube_video_id,
                video.id,
            ],
        )

    def delete(self, video_id: int) -> None:
        """Delete an alya video record by id."""
        conn = get_connection()
        conn.execute("DELETE FROM alya_videos WHERE id = ?", [video_id])

    @staticmethod
    def _row_to_model(row: tuple) -> AlyaVideo:
        """Convert a database row to an AlyaVideo model."""
        return AlyaVideo(
            id=row[0],
            alya_id=row[1],
            file_path=row[2],
            format=row[3],
            resolution_w=row[4],
            resolution_h=row[5],
            frame_rate=row[6],
            codec=row[7],
            duration_seconds=row[8],
            youtube_video_id=row[9],
            created_at=row[10],
        )
