# Generated by Claude Opus 4.6
"""Repository for AlyaRange entities."""

from src.models.alya_range import AlyaRange
from src.repositories.db import get_connection


class AlyaRangeRepository:
    """CRUD operations for the alya_ranges table."""

    def insert(self, range: AlyaRange) -> AlyaRange:
        """Insert a new alya range record and return it with the generated id."""
        conn = get_connection()
        result = conn.execute(
            """
            INSERT INTO alya_ranges (alya_id, range_order, book, chapter_start, verse_start, chapter_end, verse_end)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            RETURNING id
            """,
            [
                range.alya_id,
                range.range_order,
                range.book,
                range.chapter_start,
                range.verse_start,
                range.chapter_end,
                range.verse_end,
            ],
        ).fetchone()
        range.id = result[0]
        return range

    def get_by_id(self, range_id: int) -> AlyaRange | None:
        """Get an alya range by id."""
        conn = get_connection()
        row = conn.execute("SELECT * FROM alya_ranges WHERE id = ?", [range_id]).fetchone()
        if row is None:
            return None
        return self._row_to_model(row)

    def list_by_alya(self, alya_id: int) -> list[AlyaRange]:
        """List all ranges for an alya, ordered by range_order."""
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM alya_ranges WHERE alya_id = ? ORDER BY range_order", [alya_id]
        ).fetchall()
        return [self._row_to_model(row) for row in rows]

    def list_all(self) -> list[AlyaRange]:
        """List all alya range records."""
        conn = get_connection()
        rows = conn.execute("SELECT * FROM alya_ranges ORDER BY id").fetchall()
        return [self._row_to_model(row) for row in rows]

    def update(self, range: AlyaRange) -> None:
        """Update an existing alya range record."""
        conn = get_connection()
        conn.execute(
            """
            UPDATE alya_ranges
            SET alya_id = ?, range_order = ?, book = ?, chapter_start = ?,
                verse_start = ?, chapter_end = ?, verse_end = ?
            WHERE id = ?
            """,
            [
                range.alya_id,
                range.range_order,
                range.book,
                range.chapter_start,
                range.verse_start,
                range.chapter_end,
                range.verse_end,
                range.id,
            ],
        )

    def delete(self, range_id: int) -> None:
        """Delete an alya range record by id."""
        conn = get_connection()
        conn.execute("DELETE FROM alya_ranges WHERE id = ?", [range_id])

    def delete_by_alya(self, alya_id: int) -> None:
        """Delete all ranges for an alya."""
        conn = get_connection()
        conn.execute("DELETE FROM alya_ranges WHERE alya_id = ?", [alya_id])

    @staticmethod
    def _row_to_model(row: tuple) -> AlyaRange:
        """Convert a database row to an AlyaRange model."""
        return AlyaRange(
            id=row[0],
            alya_id=row[1],
            range_order=row[2],
            book=row[3],
            chapter_start=row[4],
            verse_start=row[5],
            chapter_end=row[6],
            verse_end=row[7],
            created_at=row[8],
        )
