# Generated by Claude Opus 4.6
"""Repository for Alya entities."""

from src.models.alya import Alya, AlyaState
from src.repositories.db import get_connection


class AlyaRepository:
    """CRUD operations for the alyot table."""

    def insert(self, alya: Alya) -> Alya:
        """Insert a new alya and return it with the generated id."""
        conn = get_connection()
        result = conn.execute(
            """
            INSERT INTO alyot (playlist_id, name, order_num, state)
            VALUES (?, ?, ?, ?)
            RETURNING id
            """,
            [alya.playlist_id, alya.name, alya.order_num, alya.state.value],
        ).fetchone()
        alya.id = result[0]
        return alya

    def get_by_id(self, alya_id: int) -> Alya | None:
        """Get an alya by id."""
        conn = get_connection()
        row = conn.execute("SELECT * FROM alyot WHERE id = ?", [alya_id]).fetchone()
        if row is None:
            return None
        return self._row_to_model(row)

    def list_by_playlist(self, playlist_id: int) -> list[Alya]:
        """List all alyot for a playlist, ordered by order_num."""
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM alyot WHERE playlist_id = ? ORDER BY order_num",
            [playlist_id],
        ).fetchall()
        return [self._row_to_model(row) for row in rows]

    def list_all(self) -> list[Alya]:
        """List all alyot."""
        conn = get_connection()
        rows = conn.execute("SELECT * FROM alyot ORDER BY id").fetchall()
        return [self._row_to_model(row) for row in rows]

    def update(self, alya: Alya) -> None:
        """Update an existing alya."""
        conn = get_connection()
        conn.execute(
            """
            UPDATE alyot SET playlist_id = ?, name = ?, order_num = ?, state = ?
            WHERE id = ?
            """,
            [alya.playlist_id, alya.name, alya.order_num, alya.state.value, alya.id],
        )

    def update_state(self, alya_id: int, state: AlyaState) -> None:
        """Update only the state of an alya."""
        conn = get_connection()
        conn.execute("UPDATE alyot SET state = ? WHERE id = ?", [state.value, alya_id])

    def delete(self, alya_id: int) -> None:
        """Delete an alya by id."""
        conn = get_connection()
        conn.execute("DELETE FROM alyot WHERE id = ?", [alya_id])

    @staticmethod
    def _row_to_model(row: tuple) -> Alya:
        """Convert a database row to an Alya model."""
        return Alya(
            id=row[0],
            playlist_id=row[1],
            name=row[2],
            order_num=row[3],
            state=AlyaState(row[4]),
            created_at=row[5],
        )
