# Generated by Claude Opus 4.6
"""DuckDB connection manager and schema initialization."""

import logging
import threading

import duckdb

from src.lib.config import get_db_path

logger = logging.getLogger(__name__)

_local = threading.local()


def get_connection() -> duckdb.DuckDBPyConnection:
    """Get a thread-local DuckDB connection, creating if needed."""
    if not hasattr(_local, "conn") or _local.conn is None:
        db_path = get_db_path()
        logger.debug(f"{db_path=}")
        _local.conn = duckdb.connect(str(db_path))
        ensure_schema(_local.conn)
    return _local.conn


def close_connection() -> None:
    """Close the thread-local DuckDB connection if open."""
    if hasattr(_local, "conn") and _local.conn is not None:
        _local.conn.close()
        _local.conn = None


def ensure_schema(conn: duckdb.DuckDBPyConnection) -> None:
    """Create tables if they don't exist."""
    # Sequences for auto-increment PKs
    for seq in ("seq_playlists", "seq_alyot", "seq_alya_audio", "seq_alya_videos", "seq_alignment_runs"):
        conn.execute(f"CREATE SEQUENCE IF NOT EXISTS {seq}")

    conn.execute("""
        CREATE TABLE IF NOT EXISTS playlists (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_playlists'),
            name VARCHAR NOT NULL UNIQUE,
            book VARCHAR NOT NULL,
            chapter_start INTEGER NOT NULL CHECK (chapter_start > 0),
            verse_start INTEGER NOT NULL CHECK (verse_start > 0),
            chapter_end INTEGER NOT NULL CHECK (chapter_end > 0),
            verse_end INTEGER NOT NULL CHECK (verse_end > 0),
            youtube_playlist_id VARCHAR,
            created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS alyot (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_alyot'),
            playlist_id INTEGER NOT NULL REFERENCES playlists(id),
            name VARCHAR NOT NULL,
            order_num INTEGER NOT NULL CHECK (order_num BETWEEN 1 AND 9),
            state VARCHAR NOT NULL DEFAULT 'pending',
            created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
            UNIQUE (playlist_id, order_num)
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS alya_audio (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_alya_audio'),
            alya_id INTEGER NOT NULL UNIQUE REFERENCES alyot(id),
            file_path VARCHAR NOT NULL,
            format VARCHAR NOT NULL,
            duration_seconds DOUBLE NOT NULL CHECK (duration_seconds > 0),
            sample_rate INTEGER NOT NULL CHECK (sample_rate BETWEEN 16000 AND 48000),
            channels INTEGER NOT NULL CHECK (channels BETWEEN 1 AND 2),
            attribution VARCHAR DEFAULT '',
            created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS alya_videos (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_alya_videos'),
            alya_id INTEGER NOT NULL REFERENCES alyot(id),
            file_path VARCHAR NOT NULL,
            format VARCHAR NOT NULL DEFAULT 'mp4',
            resolution_w INTEGER NOT NULL,
            resolution_h INTEGER NOT NULL,
            frame_rate INTEGER NOT NULL DEFAULT 30,
            codec VARCHAR NOT NULL DEFAULT 'h264',
            duration_seconds DOUBLE NOT NULL CHECK (duration_seconds > 0),
            youtube_video_id VARCHAR,
            created_at TIMESTAMP NOT NULL DEFAULT current_timestamp
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS alignment_runs (
            id INTEGER PRIMARY KEY DEFAULT nextval('seq_alignment_runs'),
            alya_id INTEGER NOT NULL REFERENCES alyot(id),
            audio_file_path VARCHAR NOT NULL,
            audio_duration_seconds DOUBLE NOT NULL CHECK (audio_duration_seconds > 0),
            alignment_quality DOUBLE NOT NULL CHECK (alignment_quality BETWEEN 0.0 AND 1.0),
            verse_count INTEGER NOT NULL CHECK (verse_count > 0),
            timestamps_json VARCHAR NOT NULL,
            manual_corrections INTEGER NOT NULL DEFAULT 0,
            manually_corrected BOOLEAN NOT NULL DEFAULT false,
            corrected_at TIMESTAMP,
            backup_path VARCHAR,
            original_quality DOUBLE CHECK (original_quality BETWEEN 0.0 AND 1.0),
            generated_at TIMESTAMP NOT NULL DEFAULT current_timestamp
        )
    """)
