# Generated by Claude Sonnet 4.5
"""YouTube playlist metadata repository for DuckDB operations."""

import logging

import duckdb

from src.models.youtube_playlist import YouTubePlaylist
from src.repositories.db import get_connection

logger = logging.getLogger(__name__)


class YouTubePlaylistMetaRepository:
    """Repository for managing YouTube playlist metadata in DuckDB."""

    def __init__(self, conn: duckdb.DuckDBPyConnection | None = None):
        """Initialize repository.

        Args:
            conn: Optional DuckDB connection (uses thread-local if not provided)
        """
        self.conn = conn or get_connection()

    def create_meta(
        self,
        playlist_id: int,
        youtube_playlist_id: str,
        title: str,
        description: str,
        tradition: str = "Ashkenaz",
        expected_video_count: int = 7,
    ) -> None:
        """Create playlist metadata and update playlists table.

        Args:
            playlist_id: FK to playlists.id
            youtube_playlist_id: YouTube playlist ID
            title: Playlist title
            description: Playlist description
            tradition: Reading tradition (default: Ashkenaz)
            expected_video_count: Expected number of videos (default: 7 aliyot)
        """
        logger.debug(f"{playlist_id=}, {youtube_playlist_id=}")

        # Insert into youtube_playlist_meta
        self.conn.execute(
            """
            INSERT INTO youtube_playlist_meta (
                playlist_id, youtube_playlist_id, title, description,
                tradition, expected_video_count
            ) VALUES (?, ?, ?, ?, ?, ?)
            """,
            [
                playlist_id,
                youtube_playlist_id,
                title,
                description,
                tradition,
                expected_video_count,
            ],
        )

        # Also update playlists table with youtube_playlist_id
        self.conn.execute(
            "UPDATE playlists SET youtube_playlist_id = ? WHERE id = ?",
            [youtube_playlist_id, playlist_id],
        )

        logger.info(f"Created playlist metadata for {playlist_id=}")

    def get_by_playlist(self, playlist_id: int) -> YouTubePlaylist | None:
        """Get playlist metadata by playlist ID.

        Args:
            playlist_id: FK to playlists.id

        Returns:
            YouTubePlaylist if found, None otherwise
        """
        logger.debug(f"{playlist_id=}")

        result = self.conn.execute(
            """
            SELECT
                ypm.playlist_id,
                ypm.youtube_playlist_id,
                ypm.title,
                ypm.description,
                ypm.privacy_status,
                ypm.video_count,
                ypm.expected_video_count,
                ypm.created_at,
                ypm.updated_at
            FROM youtube_playlist_meta ypm
            WHERE ypm.playlist_id = ?
            """,
            [playlist_id],
        ).fetchone()

        if not result:
            logger.debug(f"Playlist metadata not found for {playlist_id=}")
            return None

        # Get video IDs from alya_videos (ordered by alya order_num)
        video_ids_result = self.conn.execute(
            """
            SELECT av.youtube_video_id
            FROM alyot a
            JOIN alya_videos av ON a.id = av.alya_id
            WHERE a.playlist_id = ?
            AND av.youtube_video_id IS NOT NULL
            ORDER BY a.order_num
            """,
            [playlist_id],
        ).fetchall()

        video_ids = [row[0] for row in video_ids_result if row[0]]

        return YouTubePlaylist(
            playlist_id=result[0],
            youtube_playlist_id=result[1],
            title=result[2],
            description=result[3],
            privacy_status=result[4],
            video_ids=video_ids,
            aliyah_count=result[6],
            created_at=result[7],
            updated_at=result[8],
        )

    def get_by_youtube_id(self, youtube_playlist_id: str) -> YouTubePlaylist | None:
        """Get playlist metadata by YouTube playlist ID.

        Args:
            youtube_playlist_id: YouTube playlist ID

        Returns:
            YouTubePlaylist if found, None otherwise
        """
        logger.debug(f"{youtube_playlist_id=}")

        result = self.conn.execute(
            """
            SELECT playlist_id
            FROM youtube_playlist_meta
            WHERE youtube_playlist_id = ?
            """,
            [youtube_playlist_id],
        ).fetchone()

        if not result:
            logger.debug(f"Playlist not found: {youtube_playlist_id=}")
            return None

        return self.get_by_playlist(result[0])

    def update_video_count(self, playlist_id: int, count: int) -> None:
        """Update video count for a playlist.

        Args:
            playlist_id: FK to playlists.id
            count: New video count
        """
        logger.debug(f"{playlist_id=}, {count=}")

        self.conn.execute(
            """
            UPDATE youtube_playlist_meta
            SET video_count = ?, updated_at = current_timestamp
            WHERE playlist_id = ?
            """,
            [count, playlist_id],
        )

        logger.info(f"Updated video count for {playlist_id=}: {count}")

    def is_complete(self, playlist_id: int) -> bool:
        """Check if playlist has all expected videos.

        Args:
            playlist_id: FK to playlists.id

        Returns:
            True if video_count == expected_video_count, False otherwise
        """
        logger.debug(f"{playlist_id=}")

        result = self.conn.execute(
            """
            SELECT video_count = expected_video_count as is_complete
            FROM youtube_playlist_meta
            WHERE playlist_id = ?
            """,
            [playlist_id],
        ).fetchone()

        if not result:
            logger.debug(f"Playlist metadata not found: {playlist_id=}")
            return False

        is_complete = result[0]
        logger.debug(f"{playlist_id=} {is_complete=}")
        return bool(is_complete)

    def list_all(self) -> list[YouTubePlaylist]:
        """List all playlist metadata.

        Returns:
            List of YouTubePlaylist instances
        """
        logger.debug("Listing all playlist metadata")

        results = self.conn.execute(
            """
            SELECT DISTINCT playlist_id
            FROM youtube_playlist_meta
            ORDER BY created_at DESC
            """
        ).fetchall()

        playlists = []
        for row in results:
            playlist = self.get_by_playlist(row[0])
            if playlist:
                playlists.append(playlist)

        logger.debug(f"Found {len(playlists)} playlists")
        return playlists
