# Generated by Claude Sonnet 4.5
"""YouTube upload repository for tracking upload history in DuckDB."""

import logging
from datetime import datetime

import duckdb

from src.models.youtube_upload import YouTubeUpload
from src.repositories.db import get_connection

logger = logging.getLogger(__name__)


class YouTubeUploadRepository:
    """Repository for managing YouTube upload audit trail in DuckDB."""

    def __init__(self, conn: duckdb.DuckDBPyConnection | None = None):
        """Initialize repository.

        Args:
            conn: Optional DuckDB connection (uses thread-local if not provided)
        """
        self.conn = conn or get_connection()

    def create_upload(
        self,
        alya_video_id: int,
        new_youtube_video_id: str,
        old_youtube_video_id: str | None = None,
    ) -> YouTubeUpload:
        """Create upload record.

        Args:
            alya_video_id: FK to alya_videos.id
            new_youtube_video_id: New uploaded video ID
            old_youtube_video_id: Original video ID (if replacing)

        Returns:
            Created YouTubeUpload instance
        """
        logger.debug(f"{alya_video_id=}, {new_youtube_video_id=}")

        self.conn.execute(
            """
            INSERT INTO youtube_uploads (
                alya_video_id, old_youtube_video_id, new_youtube_video_id
            ) VALUES (?, ?, ?)
            """,
            [alya_video_id, old_youtube_video_id, new_youtube_video_id],
        )

        # Retrieve the created record
        result = self.conn.execute(
            """
            SELECT * FROM youtube_uploads
            WHERE alya_video_id = ? AND new_youtube_video_id = ?
            ORDER BY uploaded_at DESC LIMIT 1
            """,
            [alya_video_id, new_youtube_video_id],
        ).fetchone()

        logger.info(f"Created upload record (id={result[0]})")

        return self._row_to_upload(result)

    def update_status(
        self,
        upload_id: int,
        status: str,
        thumbnail_restored: bool = False,
        added_to_playlist: bool = False,
        error_message: str | None = None,
    ) -> YouTubeUpload:
        """Update upload status.

        Args:
            upload_id: Upload record ID
            status: Upload status (pending, uploading, completed, failed)
            thumbnail_restored: Whether thumbnail was restored
            added_to_playlist: Whether video was added to playlist
            error_message: Error message if failed

        Returns:
            Updated YouTubeUpload instance
        """
        logger.debug(f"{upload_id=}, {status=}")

        # Set completed_at if status is completed
        completed_at = datetime.utcnow() if status == "completed" else None

        self.conn.execute(
            """
            UPDATE youtube_uploads
            SET upload_status = ?,
                thumbnail_restored = ?,
                added_to_playlist = ?,
                error_message = ?,
                completed_at = ?
            WHERE id = ?
            """,
            [
                status,
                thumbnail_restored,
                added_to_playlist,
                error_message,
                completed_at,
                upload_id,
            ],
        )

        # Retrieve updated record
        result = self.conn.execute(
            "SELECT * FROM youtube_uploads WHERE id = ?", [upload_id]
        ).fetchone()

        logger.info(f"Updated upload {upload_id=} to {status=}")

        return self._row_to_upload(result)

    def get_by_alya_video(self, alya_video_id: int) -> YouTubeUpload | None:
        """Get upload record for a specific alya video.

        Returns the most recent upload record.

        Args:
            alya_video_id: FK to alya_videos.id

        Returns:
            YouTubeUpload if found, None otherwise
        """
        logger.debug(f"{alya_video_id=}")

        result = self.conn.execute(
            """
            SELECT * FROM youtube_uploads
            WHERE alya_video_id = ?
            ORDER BY uploaded_at DESC LIMIT 1
            """,
            [alya_video_id],
        ).fetchone()

        if not result:
            logger.debug(f"Upload not found for {alya_video_id=}")
            return None

        return self._row_to_upload(result)

    def get_by_id(self, upload_id: int) -> YouTubeUpload | None:
        """Get upload record by ID.

        Args:
            upload_id: Upload record ID

        Returns:
            YouTubeUpload if found, None otherwise
        """
        logger.debug(f"{upload_id=}")

        result = self.conn.execute(
            "SELECT * FROM youtube_uploads WHERE id = ?", [upload_id]
        ).fetchone()

        if not result:
            logger.debug(f"Upload not found: {upload_id=}")
            return None

        return self._row_to_upload(result)

    def list_pending(self) -> list[YouTubeUpload]:
        """List all pending uploads.

        Returns:
            List of YouTubeUpload instances with status='pending'
        """
        logger.debug("Listing pending uploads")

        results = self.conn.execute(
            """
            SELECT * FROM youtube_uploads
            WHERE upload_status = 'pending'
            ORDER BY uploaded_at ASC
            """
        ).fetchall()

        uploads = [self._row_to_upload(row) for row in results]
        logger.debug(f"Found {len(uploads)} pending uploads")
        return uploads

    def list_all(self) -> list[YouTubeUpload]:
        """List all upload records.

        Returns:
            List of YouTubeUpload instances ordered by upload time (newest first)
        """
        logger.debug("Listing all uploads")

        results = self.conn.execute(
            "SELECT * FROM youtube_uploads ORDER BY uploaded_at DESC"
        ).fetchall()

        uploads = [self._row_to_upload(row) for row in results]
        logger.debug(f"Found {len(uploads)} uploads")
        return uploads

    def _row_to_upload(self, row: tuple) -> YouTubeUpload:
        """Convert DuckDB row to YouTubeUpload model.

        Args:
            row: DuckDB query result row

        Returns:
            YouTubeUpload instance
        """
        return YouTubeUpload(
            id=row[0],
            alya_video_id=row[1],
            old_youtube_video_id=row[2],
            new_youtube_video_id=row[3],
            thumbnail_restored=row[4],
            added_to_playlist=row[5],
            upload_status=row[6],
            error_message=row[7],
            uploaded_at=row[8],
            completed_at=row[9],
        )
