# Generated by Claude Opus 4.6
"""Tests for MLflow experiment tracker."""

from unittest.mock import MagicMock, patch

import pytest

from src.services.alignment.evaluator import AlignmentMetrics


@pytest.fixture
def sample_metrics():
    """AlignmentMetrics with realistic test values."""
    return AlignmentMetrics(
        total_verses=10,
        mae_start=0.35,
        mae_end=0.42,
        mean_bias_start=0.1,
        mean_bias_end=-0.05,
        max_error_start=1.2,
        max_error_end=0.8,
        within_200ms=0.3,
        within_500ms=0.6,
        within_1s=0.9,
        worst_verse_ref="Deut 32:5",
        per_position_mae={1: 0.2, 2: 0.4, 3: 0.5},
        per_run_mae={1: 0.35},
    )


@pytest.fixture
def sample_report():
    return "Alignment Evaluation Report\n===========\nMAE: 0.35s"


# --- is_tracking_available() ---


def test_is_tracking_available_when_mlflow_installed():
    """Returns True when MLFLOW_AVAILABLE is True."""
    with patch("src.services.alignment.tracker.MLFLOW_AVAILABLE", True):
        from src.services.alignment.tracker import is_tracking_available

        assert is_tracking_available() is True


def test_is_tracking_available_when_mlflow_missing():
    """Returns False when MLFLOW_AVAILABLE is False."""
    with patch("src.services.alignment.tracker.MLFLOW_AVAILABLE", False):
        from src.services.alignment.tracker import is_tracking_available

        assert is_tracking_available() is False


# --- get_alignment_params() ---


def test_get_alignment_params_has_expected_keys():
    """Params dict contains all required keys for experiment logging."""
    from src.services.alignment.tracker import get_alignment_params

    params = get_alignment_params()

    expected_keys = {
        "model_version", "tts_engine", "task_language",
        "audio_sample_rate", "audio_channels",
        "min_confidence_threshold", "max_gap_seconds",
        "boundary_algorithm", "mfcc_window", "dtw_margin",
    }
    assert set(params.keys()) == expected_keys


def test_get_alignment_params_default_values():
    """Default params match the current aeneas configuration."""
    from src.services.alignment.tracker import get_alignment_params

    params = get_alignment_params()

    assert params["model_version"] == "aeneas-dtw-1.0"
    assert params["tts_engine"] == "espeak"
    assert params["task_language"] == "eng"


# --- log_experiment_run() ---


def test_log_experiment_run_returns_none_when_unavailable(sample_metrics, sample_report):
    """Gracefully returns None when MLflow is not installed."""
    with patch("src.services.alignment.tracker.MLFLOW_AVAILABLE", False):
        from src.services.alignment.tracker import log_experiment_run

        result = log_experiment_run(metrics=sample_metrics, report=sample_report)
        assert result is None


def test_log_experiment_run_calls_mlflow(sample_metrics, sample_report):
    """Verifies MLflow functions are called with correct data."""
    mock_mlflow = MagicMock()
    mock_run = MagicMock()
    mock_run.info.run_id = "test-run-123"
    mock_mlflow.start_run.return_value.__enter__ = MagicMock(return_value=mock_run)
    mock_mlflow.start_run.return_value.__exit__ = MagicMock(return_value=False)

    with (
        patch("src.services.alignment.tracker.MLFLOW_AVAILABLE", True),
        patch("src.services.alignment.tracker.mlflow", mock_mlflow, create=True),
    ):
        from src.services.alignment.tracker import log_experiment_run

        run_id = log_experiment_run(
            metrics=sample_metrics,
            report=sample_report,
            params={"model_version": "test-1.0", "tts_engine": "macos"},
        )

    assert run_id == "test-run-123"
    mock_mlflow.set_tracking_uri.assert_called_once()
    mock_mlflow.set_experiment.assert_called_once()
    mock_mlflow.log_params.assert_called_once()
    mock_mlflow.log_metrics.assert_called_once()
    mock_mlflow.log_artifacts.assert_called_once()

    # Verify metrics contain expected keys
    logged_metrics = mock_mlflow.log_metrics.call_args[0][0]
    assert "mae_start" in logged_metrics
    assert "within_500ms" in logged_metrics
    assert logged_metrics["mae_start"] == 0.35


def test_log_experiment_run_custom_params(sample_metrics, sample_report):
    """Custom params override auto-detected defaults."""
    mock_mlflow = MagicMock()
    mock_run = MagicMock()
    mock_run.info.run_id = "custom-run"
    mock_mlflow.start_run.return_value.__enter__ = MagicMock(return_value=mock_run)
    mock_mlflow.start_run.return_value.__exit__ = MagicMock(return_value=False)

    custom_params = {"tts_engine": "macos", "task_language": "heb"}

    with (
        patch("src.services.alignment.tracker.MLFLOW_AVAILABLE", True),
        patch("src.services.alignment.tracker.mlflow", mock_mlflow, create=True),
    ):
        from src.services.alignment.tracker import log_experiment_run

        log_experiment_run(
            metrics=sample_metrics, report=sample_report, params=custom_params,
        )

    logged_params = mock_mlflow.log_params.call_args[0][0]
    assert logged_params["tts_engine"] == "macos"
    assert logged_params["task_language"] == "heb"


def test_log_experiment_run_auto_run_name(sample_metrics, sample_report):
    """Auto-generated run name includes model version and timestamp."""
    mock_mlflow = MagicMock()
    mock_run = MagicMock()
    mock_run.info.run_id = "auto-name-run"
    mock_mlflow.start_run.return_value.__enter__ = MagicMock(return_value=mock_run)
    mock_mlflow.start_run.return_value.__exit__ = MagicMock(return_value=False)

    with (
        patch("src.services.alignment.tracker.MLFLOW_AVAILABLE", True),
        patch("src.services.alignment.tracker.mlflow", mock_mlflow, create=True),
    ):
        from src.services.alignment.tracker import log_experiment_run

        log_experiment_run(metrics=sample_metrics, report=sample_report)

    # Verify run_name was auto-generated with model version prefix
    call_kwargs = mock_mlflow.start_run.call_args[1]
    assert call_kwargs["run_name"].startswith("aeneas-dtw-1.0-")


def test_log_experiment_run_custom_experiment_name(sample_metrics, sample_report):
    """Custom experiment name overrides config default."""
    mock_mlflow = MagicMock()
    mock_run = MagicMock()
    mock_run.info.run_id = "exp-run"
    mock_mlflow.start_run.return_value.__enter__ = MagicMock(return_value=mock_run)
    mock_mlflow.start_run.return_value.__exit__ = MagicMock(return_value=False)

    with (
        patch("src.services.alignment.tracker.MLFLOW_AVAILABLE", True),
        patch("src.services.alignment.tracker.mlflow", mock_mlflow, create=True),
    ):
        from src.services.alignment.tracker import log_experiment_run

        log_experiment_run(
            metrics=sample_metrics, report=sample_report,
            experiment_name="boundary-tuning",
        )

    mock_mlflow.set_experiment.assert_called_once_with("boundary-tuning")
