# Generated by Claude Opus 4.6
"""Tests for alignment evaluator and list_corrected repository method."""

import pytest

from src.models.alignment_run import AlignmentRun
from src.models.alya import Alya
from src.models.alya_audio import AlyaAudio
from src.models.pasuk_alignment import PasukAlignment
from src.models.playlist import Playlist
from src.repositories.alignment_repo import AlignmentRunRepository
from src.repositories.alya_audio_repo import AlyaAudioRepository
from src.repositories.alya_repo import AlyaRepository
from src.repositories.pasuk_alignment_repo import PasukAlignmentRepository
from src.repositories.playlist_repo import PlaylistRepository
from src.services.alignment.evaluator import (
    AlignmentMetrics,
    evaluate_alignment,
    format_metrics_report,
)


@pytest.fixture
def repos(duckdb_conn):
    """Provide all repositories."""
    return {
        "playlist": PlaylistRepository(),
        "alya": AlyaRepository(),
        "audio": AlyaAudioRepository(),
        "run": AlignmentRunRepository(),
        "pa": PasukAlignmentRepository(),
    }


@pytest.fixture
def corrected_alignments(repos):
    """Insert seed data with corrected pasuk alignments."""
    p = repos["playlist"].insert(
        Playlist(name="האזינו", book="Deuteronomy", chapter_start=32, verse_start=1, chapter_end=32, verse_end=52)
    )
    a = repos["alya"].insert(Alya(playlist_id=p.id, name="ראשון", order_num=1))
    aa = repos["audio"].insert(
        AlyaAudio(alya_id=a.id, file_path="test.mp4", format="mp4", duration_seconds=30.0, sample_rate=16000, channels=1)
    )
    run = repos["run"].insert(
        AlignmentRun(alya_audio_id=aa.id, alignment_quality=0.85, verse_count=3, manually_corrected=True)
    )

    # Verse 1: corrected start 0.5s later, end 0.2s earlier
    repos["pa"].insert(PasukAlignment(
        alignment_run_id=run.id, reference="Deuteronomy 32:1", hebrew_text="הַאֲזִ֥ינוּ",
        verse_order=1, start_time=0.5, end_time=4.8, confidence=0.9,
        original_start_time=0.0, original_end_time=5.0, manually_corrected=True,
    ))
    # Verse 2: corrected start 0.3s earlier, end 1.0s later
    repos["pa"].insert(PasukAlignment(
        alignment_run_id=run.id, reference="Deuteronomy 32:2", hebrew_text="יַעֲרֹ֤ף",
        verse_order=2, start_time=4.7, end_time=11.0, confidence=0.85,
        original_start_time=5.0, original_end_time=10.0, manually_corrected=True,
    ))
    # Verse 3: not corrected (should be excluded)
    repos["pa"].insert(PasukAlignment(
        alignment_run_id=run.id, reference="Deuteronomy 32:3", hebrew_text="כִּ֤י",
        verse_order=3, start_time=11.0, end_time=15.0, confidence=0.95,
        manually_corrected=False,
    ))

    return run


# --- list_corrected() tests ---


def test_list_corrected_returns_only_corrected(repos, corrected_alignments):
    """Only manually_corrected=true rows with original times are returned."""
    result = repos["pa"].list_corrected()
    assert len(result) == 2
    assert all(pa.manually_corrected for pa in result)
    assert all(pa.original_start_time is not None for pa in result)


def test_list_corrected_empty_when_no_corrections(repos, duckdb_conn):
    """Returns empty list when no corrections exist."""
    result = repos["pa"].list_corrected()
    assert result == []


def test_list_corrected_excludes_without_originals(repos, duckdb_conn):
    """Exclude rows where manually_corrected=true but original times are null."""
    p = repos["playlist"].insert(
        Playlist(name="test", book="Genesis", chapter_start=1, verse_start=1, chapter_end=1, verse_end=5)
    )
    a = repos["alya"].insert(Alya(playlist_id=p.id, name="ראשון", order_num=1))
    aa = repos["audio"].insert(
        AlyaAudio(alya_id=a.id, file_path="t.mp4", format="mp4", duration_seconds=10.0, sample_rate=16000, channels=1)
    )
    run = repos["run"].insert(AlignmentRun(alya_audio_id=aa.id, alignment_quality=0.9, verse_count=1))
    repos["pa"].insert(PasukAlignment(
        alignment_run_id=run.id, reference="Genesis 1:1", hebrew_text="בְּרֵאשִׁית",
        verse_order=1, start_time=0.0, end_time=3.0, confidence=0.9,
        manually_corrected=True,
    ))

    result = repos["pa"].list_corrected()
    assert result == []


# --- evaluate_alignment() tests ---


def test_evaluate_empty_input():
    """Returns zero metrics for empty input."""
    metrics = evaluate_alignment(corrected=[])
    assert metrics.total_verses == 0


def test_evaluate_computes_mae():
    """Correctly computes MAE for start and end deltas."""
    corrected = [
        PasukAlignment(
            alignment_run_id=1, reference="Deut 32:1", hebrew_text="x",
            verse_order=1, start_time=0.5, end_time=4.8, confidence=0.9,
            original_start_time=0.0, original_end_time=5.0, manually_corrected=True,
        ),
        PasukAlignment(
            alignment_run_id=1, reference="Deut 32:2", hebrew_text="y",
            verse_order=2, start_time=4.7, end_time=11.0, confidence=0.9,
            original_start_time=5.0, original_end_time=10.0, manually_corrected=True,
        ),
    ]

    metrics = evaluate_alignment(corrected=corrected)

    assert metrics.total_verses == 2
    # start deltas: 0.5, -0.3 -> MAE = (0.5 + 0.3) / 2 = 0.4
    assert metrics.mae_start == pytest.approx(0.4)
    # end deltas: -0.2, 1.0 -> MAE = (0.2 + 1.0) / 2 = 0.6
    assert metrics.mae_end == pytest.approx(0.6)


def test_evaluate_computes_bias():
    """Positive bias means corrected timestamps are later than predicted."""
    corrected = [
        PasukAlignment(
            alignment_run_id=1, reference="Deut 32:1", hebrew_text="x",
            verse_order=1, start_time=1.0, end_time=6.0, confidence=0.9,
            original_start_time=0.0, original_end_time=5.0, manually_corrected=True,
        ),
    ]

    metrics = evaluate_alignment(corrected=corrected)

    assert metrics.mean_bias_start == pytest.approx(1.0)
    assert metrics.mean_bias_end == pytest.approx(1.0)


def test_evaluate_tolerance_percentages():
    """Tolerance buckets count correctly."""
    corrected = [
        # 0.1s error -> within all
        PasukAlignment(
            alignment_run_id=1, reference="v1", hebrew_text="x",
            verse_order=1, start_time=0.1, end_time=5.0, confidence=0.9,
            original_start_time=0.0, original_end_time=5.0, manually_corrected=True,
        ),
        # 0.4s error -> within 500ms and 1s
        PasukAlignment(
            alignment_run_id=1, reference="v2", hebrew_text="y",
            verse_order=2, start_time=5.4, end_time=10.0, confidence=0.9,
            original_start_time=5.0, original_end_time=10.0, manually_corrected=True,
        ),
        # 0.8s error -> within 1s only
        PasukAlignment(
            alignment_run_id=1, reference="v3", hebrew_text="z",
            verse_order=3, start_time=10.8, end_time=15.0, confidence=0.9,
            original_start_time=10.0, original_end_time=15.0, manually_corrected=True,
        ),
        # 1.5s error -> outside all
        PasukAlignment(
            alignment_run_id=1, reference="v4", hebrew_text="w",
            verse_order=4, start_time=16.5, end_time=20.0, confidence=0.9,
            original_start_time=15.0, original_end_time=20.0, manually_corrected=True,
        ),
    ]

    metrics = evaluate_alignment(corrected=corrected)

    assert metrics.within_200ms == pytest.approx(1 / 4)
    assert metrics.within_500ms == pytest.approx(2 / 4)
    assert metrics.within_1s == pytest.approx(3 / 4)


def test_evaluate_worst_verse():
    """Identifies the verse with the largest error."""
    corrected = [
        PasukAlignment(
            alignment_run_id=1, reference="small-error", hebrew_text="x",
            verse_order=1, start_time=0.1, end_time=5.0, confidence=0.9,
            original_start_time=0.0, original_end_time=5.0, manually_corrected=True,
        ),
        PasukAlignment(
            alignment_run_id=1, reference="big-error", hebrew_text="y",
            verse_order=2, start_time=7.0, end_time=10.0, confidence=0.9,
            original_start_time=5.0, original_end_time=10.0, manually_corrected=True,
        ),
    ]

    metrics = evaluate_alignment(corrected=corrected)
    assert metrics.worst_verse_ref == "big-error"


def test_evaluate_per_position_mae():
    """Per-position MAE groups by verse_order."""
    corrected = [
        PasukAlignment(
            alignment_run_id=1, reference="v1", hebrew_text="x",
            verse_order=1, start_time=0.5, end_time=5.0, confidence=0.9,
            original_start_time=0.0, original_end_time=5.0, manually_corrected=True,
        ),
        PasukAlignment(
            alignment_run_id=2, reference="v1-run2", hebrew_text="x",
            verse_order=1, start_time=0.3, end_time=5.0, confidence=0.9,
            original_start_time=0.0, original_end_time=5.0, manually_corrected=True,
        ),
    ]

    metrics = evaluate_alignment(corrected=corrected)
    # Position 1: errors 0.5 and 0.3 -> MAE = 0.4
    assert metrics.per_position_mae[1] == pytest.approx(0.4)


def test_evaluate_integration_with_duckdb(repos, corrected_alignments):
    """End-to-end: evaluator reads corrected data from DuckDB."""
    corrected = repos["pa"].list_corrected()
    metrics = evaluate_alignment(corrected=corrected)

    assert metrics.total_verses == 2
    assert metrics.mae_start > 0
    assert metrics.mae_end > 0


# --- format_metrics_report() tests ---


def test_format_empty_metrics():
    """Empty metrics produce a helpful message."""
    report = format_metrics_report(AlignmentMetrics())
    assert "No corrected alignments found" in report


def test_format_report_contains_key_sections():
    """Report includes accuracy, bias, and tolerance sections."""
    metrics = AlignmentMetrics(
        total_verses=10, mae_start=0.3, mae_end=0.4,
        mean_bias_start=0.1, mean_bias_end=-0.05,
        max_error_start=1.2, max_error_end=0.8,
        within_200ms=0.3, within_500ms=0.6, within_1s=0.9,
        worst_verse_ref="Deut 32:5",
    )
    report = format_metrics_report(metrics)

    assert "MAE start_time" in report
    assert "Bias" in report
    assert "Tolerance" in report
    assert "Deut 32:5" in report
