#!/usr/bin/env python3
# Generated by Claude Sonnet 4.5
"""Analyze keyword performance by comparing generated keywords with actual search traffic."""

import csv
import sys
from collections import Counter
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.lib.logging import get_logger

logger = get_logger(__name__)


def load_generated_keywords(file_path: str = "youtube_keywords_export.csv") -> dict:
    """Load generated keywords from export.

    Returns:
        dict: {video_id: [keywords]}
    """
    keywords_by_video = {}

    with Path(file_path).open('r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            alya_id = row['Alya ID']
            combined_tags = row['Combined Tags']
            keywords = [k.strip() for k in combined_tags.split(',')]
            keywords_by_video[alya_id] = keywords

    return keywords_by_video


def load_actual_search_terms(file_path: str = "youtube_search_terms.csv") -> list:
    """Load actual search terms from YouTube Analytics export.

    Returns:
        list: [(search_term, views)]
    """
    search_terms = []

    with Path(file_path).open('r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            search_term = row['Search Term']
            views = int(row['Views'])
            search_terms.append((search_term, views))

    return search_terms


def analyze_keyword_coverage(generated_keywords: dict, actual_searches: list) -> dict:
    """Analyze how well generated keywords cover actual searches.

    Returns:
        dict: Analysis results
    """
    # Flatten all generated keywords
    all_keywords = []
    for keywords in generated_keywords.values():
        all_keywords.extend([k.lower() for k in keywords])

    keyword_counter = Counter(all_keywords)

    # Check coverage
    covered_searches = []
    uncovered_searches = []
    total_views_covered = 0
    total_views_uncovered = 0

    for search_term, views in actual_searches:
        search_lower = search_term.lower()

        # Check if search term matches any keyword (partial match)
        is_covered = any(
            keyword in search_lower or search_lower in keyword
            for keyword in keyword_counter.keys()
        )

        if is_covered:
            covered_searches.append((search_term, views))
            total_views_covered += views
        else:
            uncovered_searches.append((search_term, views))
            total_views_uncovered += views

    return {
        'total_keywords': len(keyword_counter),
        'total_searches': len(actual_searches),
        'covered_searches': len(covered_searches),
        'uncovered_searches': len(uncovered_searches),
        'coverage_rate': len(covered_searches) / len(actual_searches) * 100 if actual_searches else 0,
        'total_views_covered': total_views_covered,
        'total_views_uncovered': total_views_uncovered,
        'view_coverage_rate': total_views_covered / (total_views_covered + total_views_uncovered) * 100 if (total_views_covered + total_views_uncovered) > 0 else 0,
        'uncovered_searches': sorted(uncovered_searches, key=lambda x: x[1], reverse=True),
        'most_common_keywords': keyword_counter.most_common(20),
    }


def export_gap_analysis(analysis: dict, output_file: str = "keyword_gap_analysis.csv"):
    """Export keyword gap analysis.

    Args:
        analysis: Analysis results
        output_file: Output CSV file
    """
    output_path = Path(output_file)

    with output_path.open('w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)

        # Write summary
        writer.writerow(["Keyword Coverage Analysis"])
        writer.writerow([])
        writer.writerow(["Metric", "Value"])
        writer.writerow(["Total Generated Keywords", analysis['total_keywords']])
        writer.writerow(["Total Actual Searches", analysis['total_searches']])
        writer.writerow(["Covered Searches", analysis['covered_searches']])
        writer.writerow(["Uncovered Searches", analysis['uncovered_searches']])
        writer.writerow(["Search Coverage Rate", f"{analysis['coverage_rate']:.1f}%"])
        writer.writerow(["View Coverage Rate", f"{analysis['view_coverage_rate']:.1f}%"])
        writer.writerow([])

        # Write gap keywords (uncovered searches)
        writer.writerow(["Missing Keywords (Actual Searches Not Covered)"])
        writer.writerow(["Search Term", "Views", "Impact"])
        for search_term, views in analysis['uncovered_searches'][:50]:
            impact = "HIGH" if views > 100 else "MEDIUM" if views > 10 else "LOW"
            writer.writerow([search_term, views, impact])

        writer.writerow([])

        # Write most common generated keywords
        writer.writerow(["Most Common Generated Keywords"])
        writer.writerow(["Keyword", "Frequency"])
        for keyword, count in analysis['most_common_keywords']:
            writer.writerow([keyword, count])

    logger.info(f"✓ Exported gap analysis to {output_path.absolute()}")


def main():
    """Main entry point."""
    # Check if files exist
    generated_file = "youtube_keywords_export.csv"
    search_file = "youtube_search_terms.csv"

    if not Path(generated_file).exists():
        logger.error(f"File not found: {generated_file}")
        logger.info("Run: uv run python scripts/export_youtube_keywords.py")
        sys.exit(1)

    if not Path(search_file).exists():
        logger.error(f"File not found: {search_file}")
        logger.info("Export search terms from YouTube Studio Analytics first")
        logger.info("Or use: uv run python scripts/export_youtube_analytics.py")
        sys.exit(1)

    # Load data
    logger.info("Loading generated keywords...")
    generated_keywords = load_generated_keywords(generated_file)

    logger.info("Loading actual search terms...")
    actual_searches = load_actual_search_terms(search_file)

    # Analyze
    logger.info("Analyzing keyword coverage...")
    analysis = analyze_keyword_coverage(generated_keywords, actual_searches)

    # Display summary
    print("\n" + "=" * 60)
    print("KEYWORD PERFORMANCE ANALYSIS")
    print("=" * 60)
    print(f"Total generated keywords: {analysis['total_keywords']}")
    print(f"Total actual searches: {analysis['total_searches']}")
    print(f"Covered searches: {analysis['covered_searches']} ({analysis['coverage_rate']:.1f}%)")
    print(f"Uncovered searches: {analysis['uncovered_searches']}")
    print(f"View coverage: {analysis['view_coverage_rate']:.1f}%")
    print()

    if analysis['uncovered_searches']:
        print("Top 10 Missing Keywords (High Impact):")
        for i, (term, views) in enumerate(analysis['uncovered_searches'][:10], 1):
            print(f"  {i}. {term} ({views} views)")
    print("=" * 60)

    # Export gap analysis
    export_gap_analysis(analysis)


if __name__ == "__main__":
    main()
