# Generated by Claude Opus 4.6
"""Backfill pasuk_alignments from cached JSON timestamp maps.

The old pipeline saved alignment data to JSON but never inserted
pasuk_alignments rows into DuckDB. This script reads the JSON files
and populates the pasuk_alignments table for existing alignment_runs.

Usage: uv run python scripts/backfill_pasuk_alignments.py
"""

import json
from pathlib import Path

from src.repositories.alignment_repo import AlignmentRunRepository
from src.repositories.alya_audio_repo import AlyaAudioRepository
from src.repositories.alya_repo import AlyaRepository
from src.repositories.db import get_connection
from src.repositories.pasuk_alignment_repo import PasukAlignmentRepository
from src.repositories.playlist_repo import PlaylistRepository
from src.models.pasuk_alignment import PasukAlignment


def backfill():
    conn = get_connection()

    playlist_repo = PlaylistRepository()
    alya_repo = AlyaRepository()
    audio_repo = AlyaAudioRepository()
    run_repo = AlignmentRunRepository()
    pa_repo = PasukAlignmentRepository()

    json_dir = Path("data/cache/timestamp_maps")
    if not json_dir.exists():
        print(f"No JSON directory found: {json_dir}")
        return

    json_files = list(json_dir.glob("*.json"))
    print(f"Found {len(json_files)} JSON files")

    for json_file in json_files:
        print(f"\nProcessing: {json_file.name}")

        with open(json_file, encoding="utf-8") as f:
            data = json.load(f)

        parasha_name = data.get("parasha_name")
        aliyah_name = data.get("aliyah_name")
        verses = data.get("verse_timestamps", [])

        if not verses:
            print(f"  No verses in file, skipping")
            continue

        # Find the alignment_run for this alya
        playlist = playlist_repo.get_by_name(parasha_name)
        if not playlist:
            print(f"  Playlist '{parasha_name}' not found in DB, skipping")
            continue

        alyot = alya_repo.list_by_playlist(playlist.id)
        alya = next((a for a in alyot if a.name == aliyah_name), None)
        if not alya:
            print(f"  Alya '{aliyah_name}' not found in DB, skipping")
            continue

        audio = audio_repo.get_by_alya(alya.id)
        if not audio:
            print(f"  No audio for alya {alya.id}, skipping")
            continue

        alignment_run = run_repo.get_latest_by_audio(audio.id)
        if not alignment_run:
            print(f"  No alignment_run for audio {audio.id}, skipping")
            continue

        # Check if pasuk_alignments already exist
        existing = pa_repo.list_by_alignment_run(alignment_run.id)
        if existing:
            print(f"  Already has {len(existing)} pasuk_alignments, skipping")
            continue

        # Insert pasuk_alignments from JSON
        pasuk_alignments = []
        for i, v in enumerate(verses):
            pa = PasukAlignment(
                alignment_run_id=alignment_run.id,
                reference=v["reference"],
                hebrew_text=v.get("hebrew_text", v["reference"]),
                verse_order=i + 1,
                start_time=v["start_time"],
                end_time=v["end_time"],
                confidence=v.get("confidence", 0.0),
            )
            pasuk_alignments.append(pa)

        pa_repo.insert_batch(pasuk_alignments)
        print(f"  Inserted {len(pasuk_alignments)} pasuk_alignments for run {alignment_run.id}")

    print("\nBackfill complete.")


if __name__ == "__main__":
    backfill()
