#!/usr/bin/env python3
# Generated by Claude Sonnet 4.5
"""Export YouTube keywords to CSV for Google Sheets import."""

import csv
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.lib.logging import get_logger
from src.repositories.db import get_connection

logger = get_logger(__name__)


def export_keywords_csv(output_file: str = "youtube_keywords_export.csv") -> None:
    """Export all YouTube keywords to CSV file.

    Args:
        output_file: Path to output CSV file
    """
    conn = get_connection(read_only=True)

    logger.info("Querying YouTube keywords from database...")

    # Query with all necessary context
    rows = conn.execute("""
        SELECT
            p.id as playlist_id,
            p.name as playlist_name,
            p.book as book,
            p.playlist_type as playlist_type,
            a.id as alya_id,
            a.name as alya_name,
            a.order_num as order_num,
            yk.tier1_keywords,
            yk.tier2_keywords,
            yk.tier3_keywords,
            yk.tier4_keywords,
            yk.combined_tags,
            yk.tag_count,
            yk.char_count
        FROM youtube_keywords yk
        JOIN alyot a ON yk.alya_id = a.id
        JOIN playlists p ON a.playlist_id = p.id
        ORDER BY p.id, a.order_num
    """).fetchall()

    logger.info(f"Found {len(rows)} keyword records")

    # Write to CSV
    output_path = Path(output_file)
    with output_path.open('w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)

        # Write header
        writer.writerow([
            'Playlist ID',
            'Playlist Name',
            'Book',
            'Type',
            'Alya ID',
            'Alya Name',
            'Order',
            'Tier 1 (Universal)',
            'Tier 2 (Playlist)',
            'Tier 3 (Video)',
            'Tier 4 (Audience)',
            'Combined Tags',
            'Tag Count',
            'Char Count',
            'Char Usage %'
        ])

        # Write data rows
        for row in rows:
            playlist_id = row[0]
            playlist_name = row[1]
            book = row[2]
            playlist_type = row[3]
            alya_id = row[4]
            alya_name = row[5]
            order_num = row[6]
            tier1 = ', '.join(row[7])  # Convert array to comma-separated string
            tier2 = ', '.join(row[8])
            tier3 = ', '.join(row[9])
            tier4 = ', '.join(row[10])
            combined = row[11]
            tag_count = row[12]
            char_count = row[13]
            char_usage = f"{char_count/500*100:.1f}%"

            writer.writerow([
                playlist_id,
                playlist_name,
                book,
                playlist_type,
                alya_id,
                alya_name,
                order_num,
                tier1,
                tier2,
                tier3,
                tier4,
                combined,
                tag_count,
                char_count,
                char_usage
            ])

    logger.info(f"✓ Exported to {output_path.absolute()}")
    logger.info(f"  Total records: {len(rows)}")
    logger.info(f"  File size: {output_path.stat().st_size / 1024:.1f} KB")
    logger.info("\nTo import into Google Sheets:")
    logger.info("  1. Open Google Sheets")
    logger.info("  2. File → Import → Upload")
    logger.info(f"  3. Select {output_path.name}")
    logger.info("  4. Choose 'Comma' as separator")


def export_keywords_summary_csv(output_file: str = "youtube_keywords_summary.csv") -> None:
    """Export a summary view with just the combined tags.

    Args:
        output_file: Path to output CSV file
    """
    conn = get_connection(read_only=True)

    logger.info("Querying YouTube keywords summary from database...")

    # Query with simplified view
    rows = conn.execute("""
        SELECT
            p.name as playlist_name,
            a.name as alya_name,
            a.order_num,
            yk.combined_tags,
            yk.tag_count,
            yk.char_count
        FROM youtube_keywords yk
        JOIN alyot a ON yk.alya_id = a.id
        JOIN playlists p ON a.playlist_id = p.id
        ORDER BY p.id, a.order_num
    """).fetchall()

    logger.info(f"Found {len(rows)} keyword records")

    # Write to CSV
    output_path = Path(output_file)
    with output_path.open('w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)

        # Write header
        writer.writerow([
            'Playlist',
            'Alya',
            'Order',
            'YouTube Tags',
            'Tag Count',
            'Char Count',
            'Usage %'
        ])

        # Write data rows
        for row in rows:
            playlist_name = row[0]
            alya_name = row[1]
            order_num = row[2]
            combined = row[3]
            tag_count = row[4]
            char_count = row[5]
            char_usage = f"{char_count/500*100:.1f}%"

            writer.writerow([
                playlist_name,
                alya_name,
                order_num,
                combined,
                tag_count,
                char_count,
                char_usage
            ])

    logger.info(f"✓ Exported summary to {output_path.absolute()}")
    logger.info(f"  Total records: {len(rows)}")
    logger.info(f"  File size: {output_path.stat().st_size / 1024:.1f} KB")


def main() -> None:
    """Main entry point."""
    if len(sys.argv) > 1 and sys.argv[1] == "summary":
        # Export summary view
        output_file = "youtube_keywords_summary.csv"
        if len(sys.argv) > 2:
            output_file = sys.argv[2]
        export_keywords_summary_csv(output_file)
    else:
        # Export full view
        output_file = "youtube_keywords_export.csv"
        if len(sys.argv) > 1:
            output_file = sys.argv[1]
        export_keywords_csv(output_file)


if __name__ == "__main__":
    main()
