#!/usr/bin/env python3
# Generated by Claude Opus 4.6
"""Ingest a Megillah folder into DuckDB.

Creates Playlist, Alya (per chapter), AlyaRange, and AlyaAudio records
from a megillah data folder containing renamed MP3 files.

Usage:
    uv run python scripts/ingest_megillah.py "שיר השירים" "Song of Songs" \
        "data/torah_read/מגילות/שיר השירים" [--dry-run]
"""

import sys
from pathlib import Path

from pydub import AudioSegment

# Ensure project root is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.models.alya import Alya
from src.models.alya_audio import AlyaAudio
from src.models.alya_range import AlyaRange
from src.models.playlist import Playlist, PlaylistType
from src.repositories.alya_audio_repo import AlyaAudioRepository
from src.repositories.alya_range_repo import AlyaRangeRepository
from src.repositories.alya_repo import AlyaRepository
from src.repositories.playlist_repo import PlaylistRepository
from src.services.text.parasha_fetcher import ParashaTextFetcher

# Hebrew chapter names (1-indexed: position 0 unused)
HEBREW_CHAPTER_NAMES = [
    "",
    "פרק א",
    "פרק ב",
    "פרק ג",
    "פרק ד",
    "פרק ה",
    "פרק ו",
    "פרק ז",
    "פרק ח",
    "פרק ט",
    "פרק י",
    "פרק יא",
    "פרק יב",
]


def get_audio_metadata(audio_path: Path) -> dict:
    """Read audio file metadata using pydub."""
    audio = AudioSegment.from_file(audio_path)
    return {
        "duration_seconds": len(audio) / 1000.0,
        "sample_rate": audio.frame_rate,
        "channels": audio.channels,
        "format": audio_path.suffix.lstrip("."),
    }


def ingest(
    hebrew_name: str,
    sefaria_book: str,
    folder: Path,
    *,
    dry_run: bool = False,
) -> None:
    """Ingest a megillah folder into the database."""
    folder = folder.resolve()
    if not folder.is_dir():
        print(f"Error: {folder} is not a directory", file=sys.stderr)
        sys.exit(1)

    # Find MP3 files sorted by name
    mp3_files = sorted(folder.glob("*.mp3"))
    if not mp3_files:
        print(f"Error: No MP3 files found in {folder}", file=sys.stderr)
        sys.exit(1)

    num_chapters = len(mp3_files)
    print(f"Found {num_chapters} MP3 files in {folder}")

    # Load ranges from TOML to get verse counts
    fetcher = ParashaTextFetcher()
    available_chapters = []
    for ch in range(1, num_chapters + 1):
        ch_name = HEBREW_CHAPTER_NAMES[ch]
        key = (hebrew_name, ch_name)
        if key in fetcher.ranges:
            available_chapters.append((ch, ch_name, fetcher.ranges[key]))
        else:
            print(f"Warning: No TOML range for {hebrew_name}/{ch_name}", file=sys.stderr)

    if not available_chapters:
        print("Error: No chapter ranges found in aliyah_ranges.toml", file=sys.stderr)
        sys.exit(1)

    if dry_run:
        print(f"\n=== DRY RUN for {hebrew_name} ({sefaria_book}) ===\n")
        print(f"Playlist: name={hebrew_name}, book={sefaria_book}, type=megillah")
        overall_start = available_chapters[0][2]
        overall_end = available_chapters[-1][2]
        print(
            f"  Range: {sefaria_book} {overall_start.chapter_start}:{overall_start.verse_start}"
            f" - {overall_end.chapter_end}:{overall_end.verse_end}"
        )
        for ch_num, ch_name, rng in available_chapters:
            mp3 = mp3_files[ch_num - 1]
            print(f"\n  {ch_name} (order_num={ch_num}):")
            print(f"    Audio: {mp3.name}")
            print(f"    Range: {rng.book} {rng.chapter_start}:{rng.verse_start}-{rng.chapter_end}:{rng.verse_end}")
        return

    # Create repositories
    playlist_repo = PlaylistRepository()
    alya_repo = AlyaRepository()
    range_repo = AlyaRangeRepository()
    audio_repo = AlyaAudioRepository()

    # Get overall range from first/last chapter
    first_range = available_chapters[0][2]
    last_range = available_chapters[-1][2]

    # Upsert playlist
    existing = playlist_repo.get_by_name(hebrew_name)
    if existing:
        print(f"Playlist '{hebrew_name}' already exists (id={existing.id}), reusing.")
        playlist = existing
    else:
        playlist = playlist_repo.insert(
            Playlist(
                name=hebrew_name,
                book=sefaria_book,
                playlist_type=PlaylistType.MEGILLAH,
                chapter_start=first_range.chapter_start,
                verse_start=first_range.verse_start,
                chapter_end=last_range.chapter_end,
                verse_end=last_range.verse_end,
            )
        )
        print(f"Created playlist '{hebrew_name}' (id={playlist.id})")

    # Get existing alyot
    existing_alyot = {a.order_num: a for a in alya_repo.list_by_playlist(playlist.id)}

    for ch_num, ch_name, rng in available_chapters:
        mp3_path = mp3_files[ch_num - 1]

        # Create Alya
        if ch_num in existing_alyot:
            alya = existing_alyot[ch_num]
            print(f"  {ch_name}: alya exists (id={alya.id}), reusing.")
        else:
            alya = alya_repo.insert(
                Alya(playlist_id=playlist.id, name=ch_name, order_num=ch_num)
            )
            print(f"  {ch_name}: created alya (id={alya.id})")

        # Create AlyaRange
        existing_ranges = range_repo.list_by_alya(alya.id)
        if not existing_ranges:
            range_repo.insert(
                AlyaRange(
                    alya_id=alya.id,
                    range_order=1,
                    book=rng.book,
                    chapter_start=rng.chapter_start,
                    verse_start=rng.verse_start,
                    chapter_end=rng.chapter_end,
                    verse_end=rng.verse_end,
                )
            )
            print(f"    Created range: {rng.book} {rng.chapter_start}:{rng.verse_start}-{rng.chapter_end}:{rng.verse_end}")

        # Create AlyaAudio
        existing_audio = audio_repo.get_by_alya(alya.id)
        if existing_audio:
            print(f"    Audio already exists (id={existing_audio.id}), skipping.")
        else:
            meta = get_audio_metadata(mp3_path)
            audio_repo.insert(
                AlyaAudio(
                    alya_id=alya.id,
                    file_path=str(mp3_path),
                    format=meta["format"],
                    duration_seconds=meta["duration_seconds"],
                    sample_rate=meta["sample_rate"],
                    channels=meta["channels"],
                )
            )
            print(f"    Created audio: {mp3_path.name} ({meta['duration_seconds']:.1f}s)")

    print(f"\nDone! Ingested {len(available_chapters)} chapters for {hebrew_name}.")


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Ingest a Megillah into DuckDB.")
    parser.add_argument("hebrew_name", help="Hebrew name (e.g., 'שיר השירים')")
    parser.add_argument("sefaria_book", help="Sefaria book name (e.g., 'Song of Songs')")
    parser.add_argument("folder", type=Path, help="Path to megillah data folder")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be done")
    args = parser.parse_args()

    try:
        ingest(args.hebrew_name, args.sefaria_book, args.folder, dry_run=args.dry_run)
        return 0
    except Exception as e:
        print(f"\nError: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
