#!/usr/bin/env python3
# Generated by Claude Sonnet 4.5
"""Populate aliyah_ranges.toml using Hebcal API for Torah readings."""

import sys
import time
from pathlib import Path

import httpx


def fetch_torah_readings_year():
    """Fetch Torah readings from Hebcal API for entire year."""
    url = "https://www.hebcal.com/hebcal?v=1&cfg=json&maj=on&min=off&mod=off&nx=off&year=now&month=x&ss=off&mf=off&c=off&geo=none&M=on&s=off"
    
    print("Fetching Torah reading schedule from Hebcal...")
    response = httpx.get(url, timeout=30.0)
    response.raise_for_status()
    
    data = response.json()
    items = data.get("items", [])
    
    # Filter for Parashat Hashavua
    parashot = [
        item for item in items 
        if item.get("category") == "parashat" and "link" in item
    ]
    
    print(f"Found {len(parashot)} Parashot readings")
    return parashot


def fetch_sefaria_parasha_aliyot(parasha_url: str):
    """Fetch Aliyah details from Sefaria for a specific Parasha."""
    # Extract reference from URL
    # Example: https://www.sefaria.org/Genesis.1.1-6.8?lang=bi
    
    import re
    match = re.search(r'/([^/]+)\?', parasha_url)
    if not match:
        return None
    
    ref = match.group(1)
    print(f"  Checking Sefaria for: {ref}")
    
    # This won't work - Sefaria doesn't provide Aliyah divisions via simple API
    return None


def main():
    print("Attempting to populate Torah Aliyot from Hebcal...")
    print("=" * 70)
    
    parashot = fetch_torah_readings_year()
    
    for p in parashot[:5]:
        print(f"\n{p.get('hebrew', 'N/A')}: {p.get('link', 'N/A')}")
    
    print("\n" + "=" * 70)
    print("Note: Hebcal provides Parasha schedules but not Aliyah divisions.")
    print("Aliyah divisions would need to be:")
    print("  1. Manually entered from authoritative sources")
    print("  2. Or extracted from Torah study databases")
    print("=" * 70)


if __name__ == "__main__":
    main()
