#!/usr/bin/env python3
# Generated by Claude Sonnet 4.5
"""Populate YouTube keywords for all existing alyot."""

import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.lib.logging import get_logger
from src.repositories.alya_repo import AlyaRepository
from src.repositories.playlist_repo import PlaylistRepository
from src.repositories.youtube_keyword_repo import YouTubeKeywordRepository
from src.services.youtube_keyword_service import YouTubeKeywordService

logger = get_logger(__name__)


def main() -> None:
    """Populate YouTube keywords for all alyot."""
    playlist_repo = PlaylistRepository()
    alya_repo = AlyaRepository()
    keyword_repo = YouTubeKeywordRepository()
    keyword_service = YouTubeKeywordService()

    # Get all playlists
    playlists = playlist_repo.list_all()
    logger.info(f"Found {len(playlists)} playlists")

    total_alyot = 0
    processed_alyot = 0
    skipped_alyot = 0
    errors = 0

    for playlist in playlists:
        logger.info(f"\nProcessing playlist: {playlist.name} ({playlist.playlist_type})")

        # Get all alyot for this playlist
        alyot = alya_repo.list_by_playlist(playlist.id)
        logger.info(f"  Found {len(alyot)} alyot")
        total_alyot += len(alyot)

        for alya in alyot:
            try:
                # Check if keywords already exist
                existing = keyword_repo.get_by_alya(alya.id)
                if existing:
                    logger.debug(f"  Skipping alya {alya.id} ({alya.name}) - keywords already exist")
                    skipped_alyot += 1
                    continue

                # Generate keywords
                tier1, tier2, tier3, tier4 = keyword_service.generate_keywords(playlist, alya)

                # Insert into database
                keywords = keyword_repo.insert(
                    alya_id=alya.id,
                    tier1=tier1,
                    tier2=tier2,
                    tier3=tier3,
                    tier4=tier4,
                )

                logger.info(
                    f"  ✓ Alya {alya.id} ({alya.name}): "
                    f"{keywords.tag_count} tags, {keywords.char_count} chars"
                )
                processed_alyot += 1

            except Exception as e:
                logger.error(f"  ✗ Failed to process alya {alya.id} ({alya.name}): {e}")
                errors += 1
                continue

    # Summary
    logger.info("\n" + "=" * 60)
    logger.info("SUMMARY")
    logger.info("=" * 60)
    logger.info(f"Total alyot: {total_alyot}")
    logger.info(f"Processed: {processed_alyot}")
    logger.info(f"Skipped (already exist): {skipped_alyot}")
    logger.info(f"Errors: {errors}")
    logger.info("=" * 60)

    if errors > 0:
        logger.warning(f"{errors} errors occurred during processing")
        sys.exit(1)


if __name__ == "__main__":
    main()
