#!/usr/bin/env python3
# Generated by Claude Opus 4.6
"""Populate DuckDB with all 54 Torah Parashot and their Aliyot from Sefaria.

Uses the Sefaria Index API (/api/v2/index/{Book}) which returns all parashot
and their 7 aliyot per Torah book. Only 5 API calls needed (one per book).

Maftir is derived from the last aliyah (standard practice: last few verses of shvi'i).

Usage:
    uv run python scripts/populate_alyot.py [--dry-run]
"""

import re
import sys
import time
from pathlib import Path

import httpx

# Ensure project root is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.models.alya import Alya
from src.models.alya_range import AlyaRange
from src.models.playlist import Playlist
from src.repositories.alya_range_repo import AlyaRangeRepository
from src.repositories.alya_repo import AlyaRepository
from src.repositories.playlist_repo import PlaylistRepository

TORAH_BOOKS = ["Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy"]

ALIYAH_NAMES = ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שביעי"]

# Ashkenazi Haftarot for all 54 parashot (authoritative, well-established data)
HAFTAROT: dict[str, list[str]] = {
    "בראשית": ["Isaiah 42:5-43:10"],
    "נח": ["Isaiah 54:1-55:5"],
    "לך לך": ["Isaiah 40:27-41:16"],
    "וירא": ["II Kings 4:1-4:37"],
    "חיי שרה": ["I Kings 1:1-1:31"],
    "תולדות": ["Malachi 1:1-2:7"],
    "ויצא": ["Hosea 12:13-14:10"],
    "וישלח": ["Obadiah 1:1-1:21"],
    "וישב": ["Amos 2:6-3:8"],
    "מקץ": ["I Kings 3:15-4:1"],
    "ויגש": ["Ezekiel 37:15-37:28"],
    "ויחי": ["I Kings 2:1-2:12"],
    "שמות": ["Isaiah 27:6-28:13", "Isaiah 29:22-29:23"],
    "וארא": ["Ezekiel 28:25-29:21"],
    "בא": ["Jeremiah 46:13-46:28"],
    "בשלח": ["Judges 4:4-5:31"],
    "יתרו": ["Isaiah 6:1-7:6", "Isaiah 9:5-9:6"],
    "משפטים": ["Jeremiah 34:8-34:22", "Jeremiah 33:25-33:26"],
    "תרומה": ["I Kings 5:26-6:13"],
    "תצוה": ["Ezekiel 43:10-43:27"],
    "כי תשא": ["I Kings 18:1-18:39"],
    "ויקהל": ["I Kings 7:40-7:50"],
    "פקודי": ["I Kings 7:51-8:21"],
    "ויקרא": ["Isaiah 43:21-44:23"],
    "צו": ["Jeremiah 7:21-8:3", "Jeremiah 9:22-9:23"],
    "שמיני": ["II Samuel 6:1-7:17"],
    "תזריע": ["II Kings 4:42-5:19"],
    "מצורע": ["II Kings 7:3-7:20"],
    "אחרי מות": ["Ezekiel 22:1-22:19"],
    "קדושים": ["Amos 9:7-9:15"],
    "אמור": ["Ezekiel 44:15-44:31"],
    "בהר": ["Jeremiah 32:6-32:27"],
    "בחוקתי": ["Jeremiah 16:19-17:14"],
    "במדבר": ["Hosea 2:1-2:22"],
    "נשא": ["Judges 13:2-13:25"],
    "בהעלותך": ["Zechariah 2:14-4:7"],
    "שלח": ["Joshua 2:1-2:24"],
    "קרח": ["I Samuel 11:14-12:22"],
    "חקת": ["Judges 11:1-11:33"],
    "בלק": ["Micah 5:6-6:8"],
    "פנחס": ["I Kings 18:46-19:21"],
    "מטות": ["Jeremiah 1:1-2:3"],
    "מסעי": ["Jeremiah 2:4-2:28", "Jeremiah 3:4-3:4"],
    "דברים": ["Isaiah 1:1-1:27"],
    "ואתחנן": ["Isaiah 40:1-40:26"],
    "עקב": ["Isaiah 49:14-51:3"],
    "ראה": ["Isaiah 54:11-55:5"],
    "שופטים": ["Isaiah 51:12-52:12"],
    "כי תצא": ["Isaiah 54:1-54:10"],
    "כי תבוא": ["Isaiah 60:1-60:22"],
    "נצבים": ["Isaiah 61:10-63:9"],
    "וילך": ["Isaiah 55:6-56:8"],
    "האזינו": ["II Samuel 22:1-22:51"],
    "וזאת הברכה": ["Joshua 1:1-1:18"],
}


def parse_ref(ref: str) -> dict:
    """Parse a Sefaria reference like 'Genesis 1:1-2:3' into components."""
    # Edited by Claude Opus 4.6 - handles multi-word book names and en-dashes
    ref = ref.replace("\u2013", "-")  # normalize en-dash to hyphen

    # Range: "Book Ch:V-Ch:V" or "Book Ch:V-V"
    range_pattern = r"(.+?)\s+(\d+):(\d+)-(?:(\d+):)?(\d+)"
    match = re.match(range_pattern, ref)
    if match:
        book, ch_start, v_start, ch_end, v_end = match.groups()
        if ch_end is None:
            ch_end = ch_start
        return {
            "book": book,
            "chapter_start": int(ch_start),
            "verse_start": int(v_start),
            "chapter_end": int(ch_end),
            "verse_end": int(v_end),
        }

    # Single verse: "Book Ch:V"
    single_pattern = r"(.+?)\s+(\d+):(\d+)$"
    match = re.match(single_pattern, ref)
    if match:
        book, ch, v = match.groups()
        return {
            "book": book,
            "chapter_start": int(ch),
            "verse_start": int(v),
            "chapter_end": int(ch),
            "verse_end": int(v),
        }

    msg = f"Could not parse reference: {ref}"
    raise ValueError(msg)


def fetch_parashot_from_index(book: str) -> list[dict]:
    """Fetch all parashot from a Torah book's index.

    Returns list of dicts with keys: he_title, whole_ref, refs (7 aliyot)
    """
    url = f"https://www.sefaria.org/api/v2/index/{book}"
    response = httpx.get(url, timeout=30.0)
    response.raise_for_status()
    data = response.json()

    nodes = data.get("alts", {}).get("Parasha", {}).get("nodes", [])
    result = []
    for node in nodes:
        result.append({
            "he_title": node["heTitle"],
            "en_title": node["sharedTitle"],
            "whole_ref": node["wholeRef"],
            "refs": node["refs"],  # 7 aliyot refs
        })
    return result


def derive_maftir_ref(seventh_aliyah_ref: str) -> str | None:
    """Derive maftir reference from the 7th aliyah.

    Maftir is typically the last 3 verses of the 7th aliyah.
    Returns a ref string or None if we can't derive it.
    """
    parsed = parse_ref(seventh_aliyah_ref)
    ch_end = parsed["chapter_end"]
    v_end = parsed["verse_end"]

    # Maftir starts ~3 verses before the end of shvi'i
    maftir_v_start = max(1, v_end - 2)
    return f"{parsed['book']} {ch_end}:{maftir_v_start}-{ch_end}:{v_end}"


def parse_haftara_refs(parasha_he: str) -> list[dict] | None:
    """Parse haftara reference(s) for a parasha. Returns list of parsed refs."""
    refs = HAFTAROT.get(parasha_he)
    if not refs:
        return None
    return [parse_ref(r) for r in refs]


def populate(*, dry_run: bool = False, overwrite: bool = False) -> None:
    """Fetch all parashot from Sefaria and populate DuckDB."""
    playlist_repo = PlaylistRepository()
    alya_repo = AlyaRepository()
    alya_range_repo = AlyaRangeRepository()

    stats = {"playlists_created": 0, "playlists_updated": 0, "alyot_created": 0,
             "alya_ranges_created": 0, "skipped": 0}

    all_parashot = []
    for book in TORAH_BOOKS:
        print(f"Fetching {book}...")
        parashot = fetch_parashot_from_index(book)
        all_parashot.extend(parashot)
        time.sleep(0.2)  # rate limit courtesy

    print(f"\nFetched {len(all_parashot)} parashot from Sefaria index API\n")

    for parasha in all_parashot:
        he_title = parasha["he_title"]
        whole = parse_ref(parasha["whole_ref"])
        refs = parasha["refs"]

        print(f"  {he_title} ({parasha['en_title']}): {parasha['whole_ref']}")

        if dry_run:
            for i, ref in enumerate(refs):
                p = parse_ref(ref)
                print(f"    {ALIYAH_NAMES[i]}: {ref}")
            maftir = derive_maftir_ref(refs[6])
            if maftir:
                print(f"    מפטיר: {maftir}")
            haftara_refs = HAFTAROT.get(he_title)
            if haftara_refs:
                print(f"    הפטרה: {', '.join(haftara_refs)}")
            print()
            continue

        # Upsert playlist
        existing_playlist = playlist_repo.get_by_name(he_title)
        if existing_playlist:
            # Update with real data if it had placeholders or overwrite requested
            if overwrite or existing_playlist.book == "Unknown" or existing_playlist.chapter_start == 1:
                existing_playlist.book = whole["book"]
                existing_playlist.chapter_start = whole["chapter_start"]
                existing_playlist.verse_start = whole["verse_start"]
                existing_playlist.chapter_end = whole["chapter_end"]
                existing_playlist.verse_end = whole["verse_end"]
                playlist_repo.update(existing_playlist)
                stats["playlists_updated"] += 1
                print(f"    [updated playlist]")
            playlist = existing_playlist
        else:
            playlist = playlist_repo.insert(Playlist(
                name=he_title,
                book=whole["book"],
                chapter_start=whole["chapter_start"],
                verse_start=whole["verse_start"],
                chapter_end=whole["chapter_end"],
                verse_end=whole["verse_end"],
            ))
            stats["playlists_created"] += 1

        # Get existing alyot for this playlist
        existing_alyot = {a.order_num: a for a in alya_repo.list_by_playlist(playlist.id)}

        # Insert 7 aliyot + ranges
        for i, ref in enumerate(refs):
            order_num = i + 1
            parsed = parse_ref(ref)

            if order_num in existing_alyot:
                alya = existing_alyot[order_num]
                stats["skipped"] += 1
            else:
                alya = alya_repo.insert(Alya(
                    playlist_id=playlist.id,
                    name=ALIYAH_NAMES[i],
                    order_num=order_num,
                ))
                stats["alyot_created"] += 1

            # Insert alya_range if not exists (or overwrite)
            existing_ranges = alya_range_repo.list_by_alya(alya.id)
            if existing_ranges and overwrite:
                alya_range_repo.delete_by_alya(alya.id)
                existing_ranges = []
            if not existing_ranges:
                alya_range_repo.insert(AlyaRange(
                    alya_id=alya.id,
                    range_order=1,
                    book=parsed["book"],
                    chapter_start=parsed["chapter_start"],
                    verse_start=parsed["verse_start"],
                    chapter_end=parsed["chapter_end"],
                    verse_end=parsed["verse_end"],
                ))
                stats["alya_ranges_created"] += 1

        # Maftir (order_num=8)
        if 8 not in existing_alyot:
            maftir_ref = derive_maftir_ref(refs[6])
            if maftir_ref:
                maftir_parsed = parse_ref(maftir_ref)
                maftir_alya = alya_repo.insert(Alya(
                    playlist_id=playlist.id, name="מפטיר", order_num=8,
                ))
                alya_range_repo.insert(AlyaRange(
                    alya_id=maftir_alya.id, range_order=1,
                    book=maftir_parsed["book"],
                    chapter_start=maftir_parsed["chapter_start"],
                    verse_start=maftir_parsed["verse_start"],
                    chapter_end=maftir_parsed["chapter_end"],
                    verse_end=maftir_parsed["verse_end"],
                ))
                stats["alyot_created"] += 1
                stats["alya_ranges_created"] += 1
        else:
            # Maftir alya exists but might lack range
            maftir_alya = existing_alyot[8]
            existing_maftir_ranges = alya_range_repo.list_by_alya(maftir_alya.id)
            if existing_maftir_ranges and overwrite:
                alya_range_repo.delete_by_alya(maftir_alya.id)
                existing_maftir_ranges = []
            if not existing_maftir_ranges:
                maftir_ref = derive_maftir_ref(refs[6])
                if maftir_ref:
                    maftir_parsed = parse_ref(maftir_ref)
                    alya_range_repo.insert(AlyaRange(
                        alya_id=maftir_alya.id, range_order=1,
                        book=maftir_parsed["book"],
                        chapter_start=maftir_parsed["chapter_start"],
                        verse_start=maftir_parsed["verse_start"],
                        chapter_end=maftir_parsed["chapter_end"],
                        verse_end=maftir_parsed["verse_end"],
                    ))
                    stats["alya_ranges_created"] += 1

        # Haftara (order_num=9)
        haftara_parsed_list = parse_haftara_refs(he_title)
        if haftara_parsed_list:
            if 9 not in existing_alyot:
                haftara_alya = alya_repo.insert(Alya(
                    playlist_id=playlist.id, name="הפטרה", order_num=9,
                ))
                stats["alyot_created"] += 1
            else:
                haftara_alya = existing_alyot[9]

            existing_haftara_ranges = alya_range_repo.list_by_alya(haftara_alya.id)
            if existing_haftara_ranges and overwrite:
                alya_range_repo.delete_by_alya(haftara_alya.id)
                existing_haftara_ranges = []
            if not existing_haftara_ranges:
                for range_idx, hp in enumerate(haftara_parsed_list, 1):
                    alya_range_repo.insert(AlyaRange(
                        alya_id=haftara_alya.id,
                        range_order=range_idx,
                        book=hp["book"],
                        chapter_start=hp["chapter_start"],
                        verse_start=hp["verse_start"],
                        chapter_end=hp["chapter_end"],
                        verse_end=hp["verse_end"],
                    ))
                    stats["alya_ranges_created"] += 1

    print(f"\n{'[DRY RUN] ' if dry_run else ''}Results:")
    for k, v in stats.items():
        print(f"  {k}: {v}")


def main() -> int:
    # Edited by Claude Opus 4.6 - added --overwrite flag
    dry_run = "--dry-run" in sys.argv
    overwrite = "--overwrite" in sys.argv
    if dry_run:
        print("=== DRY RUN - no DB writes ===\n")
    else:
        print("=== Populating DuckDB with all Torah Parashot ===\n")
    if overwrite:
        print("  (overwrite mode: existing ranges will be replaced)\n")

    try:
        populate(dry_run=dry_run, overwrite=overwrite)
        return 0
    except Exception as e:
        print(f"\nError: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
