#!/usr/bin/env python3
# Generated by Claude Sonnet 4.5
"""Populate aliyah_ranges.toml for all 54 Torah Parashot using Sefaria API.

Fetches Aliyah divisions from Sefaria's calendar API and generates
the complete TOML configuration file.
"""

import re
import sys
from datetime import datetime, timedelta
from pathlib import Path

import httpx


# All 54 Torah Parashot in Hebrew with their corresponding English names
PARASHOT = {
    "בראשית": "Bereshit",
    "נח": "Noach",
    "לך לך": "Lech-Lecha",
    "וירא": "Vayera",
    "חיי שרה": "Chayei Sara",
    "תולדות": "Toldot",
    "ויצא": "Vayetzei",
    "וישלח": "Vayishlach",
    "וישב": "Vayeshev",
    "מקץ": "Miketz",
    "ויגש": "Vayigash",
    "ויחי": "Vayechi",
    "שמות": "Shemot",
    "וארא": "Vaera",
    "בא": "Bo",
    "בשלח": "Beshalach",
    "יתרו": "Yitro",
    "משפטים": "Mishpatim",
    "תרומה": "Terumah",
    "תצוה": "Tetzaveh",
    "כי תשא": "Ki Tisa",
    "ויקהל": "Vayakhel",
    "פקודי": "Pekudei",
    "ויקרא": "Vayikra",
    "צו": "Tzav",
    "שמיני": "Shmini",
    "תזריע": "Tazria",
    "מצורע": "Metzora",
    "אחרי מות": "Achrei Mot",
    "קדושים": "Kedoshim",
    "אמור": "Emor",
    "בהר": "Behar",
    "בחוקתי": "Bechukotai",
    "במדבר": "Bamidbar",
    "נשא": "Nasso",
    "בהעלתך": "Beha'alotcha",
    "שלח לך": "Sh'lach",
    "קרח": "Korach",
    "חקת": "Chukat",
    "בלק": "Balak",
    "פנחס": "Pinchas",
    "מטות": "Matot",
    "מסעי": "Masei",
    "דברים": "Devarim",
    "ואתחנן": "Vaetchanan",
    "עקב": "Eikev",
    "ראה": "Re'eh",
    "שפטים": "Shoftim",
    "כי תצא": "Ki Teitzei",
    "כי תבוא": "Ki Tavo",
    "נצבים": "Nitzavim",
    "וילך": "Vayeilech",
    "האזינו": "Haazinu",
    "וזאת הברכה": "V'Zot HaBerachah",
}

ALIYAH_NAMES_HEBREW = {
    "First": "ראשון",
    "Second": "שני",
    "Third": "שלישי",
    "Fourth": "רביעי",
    "Fifth": "חמישי",
    "Sixth": "שישי",
    "Seventh": "שביעי",
    "Maftir": "מפטיר",
}


def parse_verse_reference(ref: str) -> dict:
    """Parse Sefaria verse reference into components.
    
    Examples:
        "Exodus 30:11-31:17" → {book: Exodus, ch_start: 30, v_start: 11, ch_end: 31, v_end: 17}
        "Deuteronomy 32:1-6" → {book: Deuteronomy, ch_start: 32, v_start: 1, ch_end: 32, v_end: 6}
    """
    # Pattern: "Book Chapter:Verse-Chapter:Verse" or "Book Chapter:Verse-Verse"
    pattern = r"(\w+)\s+(\d+):(\d+)-(?:(\d+):)?(\d+)"
    match = re.match(pattern, ref)
    
    if not match:
        raise ValueError(f"Could not parse reference: {ref}")
    
    book, ch_start, v_start, ch_end, v_end = match.groups()
    
    # If ch_end is None, it's same chapter
    if ch_end is None:
        ch_end = ch_start
    
    return {
        "book": book,
        "chapter_start": int(ch_start),
        "verse_start": int(v_start),
        "chapter_end": int(ch_end),
        "verse_end": int(v_end),
    }


def fetch_parasha_aliyot_from_date(date_str: str) -> dict | None:
    """Fetch Parasha and Aliyot for a specific date from Sefaria calendar API.
    
    Args:
        date_str: Date in YYYY-MM-DD format
    
    Returns:
        Dict with parasha_name and aliyot list, or None if no Parasha that week
    """
    url = f"https://www.sefaria.org/api/calendars?diaspora=1&custom=ashkenazi&timezone=America/New_York"
    
    # Add date parameter if provided
    if date_str:
        url += f"&datetime={date_str}"
    
    try:
        response = httpx.get(url, timeout=30.0)
        response.raise_for_status()
        data = response.json()
        
        # Find Parashat Hashavua item
        for item in data.get("calendar_items", []):
            if item.get("title", {}).get("en") == "Parashat Hashavua":
                parasha_name_he = item["displayValue"]["he"]
                aliyot = item.get("extraDetails", {}).get("aliyot", [])
                
                if aliyot:
                    return {
                        "parasha_name_he": parasha_name_he,
                        "parasha_name_en": item["displayValue"]["en"],
                        "aliyot": aliyot,
                    }
        
        return None
    except Exception as e:
        print(f"  Error fetching {date_str}: {e}")
        return None


def scan_year_for_all_parashot(year: int = 2024):
    """Scan entire Jewish year to collect all Parashot with Aliyot.
    
    Returns:
        Dict mapping Hebrew parasha names to aliyot data
    """
    parashot_data = {}
    start_date = datetime(year, 9, 1)  # Start from September (around Rosh Hashanah)
    
    print(f"Scanning {year}-{year+1} Jewish year for all Parashot...")
    print("=" * 70)
    
    # Scan every Saturday for a full year
    for week in range(55):  # 54 weeks + buffer
        saturday = start_date + timedelta(days=week * 7)
        date_str = saturday.strftime("%Y-%m-%d")
        
        print(f"Week {week+1:2d} ({date_str})...", end=" ")
        
        parasha_data = fetch_parasha_aliyot_from_date(date_str)
        
        if parasha_data:
            parasha_name_he = parasha_data["parasha_name_he"]
            parasha_name_en = parasha_data["parasha_name_en"]
            
            # Handle combined Parashot (e.g., "Vayakhel-Pekudei")
            # Take the first one if combined
            if "-" in parasha_name_he and parasha_name_he not in PARASHOT:
                parasha_name_he = parasha_name_he.split("-")[0].strip()
            
            if parasha_name_he not in parashot_data:
                parashot_data[parasha_name_he] = parasha_data
                print(f"✓ Found: {parasha_name_he} ({parasha_name_en})")
            else:
                print(f"  (duplicate: {parasha_name_he})")
        else:
            print("  (no Parasha)")
    
    print("=" * 70)
    print(f"Found {len(parashot_data)} unique Parashot")
    
    return parashot_data


def generate_toml(parashot_data: dict, output_path: Path):
    """Generate aliyah_ranges.toml from collected Parasha data."""
    
    lines = [
        "# Aliyah verse range configuration",
        "# Generated by Claude Sonnet 4.5 using Sefaria API",
        "#",
        "# Format: [\"parasha_name\".\"aliyah_name\"]",
        "# All verse ranges are INCLUSIVE (verse_end is the last verse to include)",
        "# Using Hebrew names to match filename parser output",
        "",
    ]
    
    # Sort by Parasha order in PARASHOT dict
    parasha_order = list(PARASHOT.keys())
    sorted_parashot = sorted(
        parashot_data.items(),
        key=lambda x: parasha_order.index(x[0]) if x[0] in parasha_order else 999
    )
    
    for parasha_name_he, data in sorted_parashot:
        aliyot = data["aliyot"]
        
        # Process each Aliyah (skip Maftir which is usually last)
        for i, aliyah_ref in enumerate(aliyot[:7], 1):  # First 7 are regular Aliyot
            try:
                parsed = parse_verse_reference(aliyah_ref)
                
                # Map ordinal to Hebrew name
                aliyah_names = ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שביעי"]
                aliyah_name_he = aliyah_names[i - 1]
                
                lines.append(f'["{parasha_name_he}"."{aliyah_name_he}"]')
                lines.append(f'book = "{parsed["book"]}"')
                lines.append(f'chapter_start = {parsed["chapter_start"]}')
                lines.append(f'verse_start = {parsed["verse_start"]}')
                lines.append(f'chapter_end = {parsed["chapter_end"]}')
                lines.append(f'verse_end = {parsed["verse_end"]}')
                lines.append("")
                
            except Exception as e:
                print(f"  Warning: Could not parse Aliyah {i} for {parasha_name_he}: {e}")
                continue
    
    # Write to file
    output_path.write_text("\n".join(lines))
    print(f"\n✅ Generated: {output_path}")
    print(f"   Total entries: {len([l for l in lines if l.startswith('[\"')])}")


def main():
    """Main entry point."""
    output_path = Path("data/aliyah_ranges.toml")
    
    print("Populating aliyah_ranges.toml for all 54 Torah Parashot")
    print("Using Sefaria Calendar API")
    print("=" * 70)
    
    # Scan Jewish year for all Parashot
    parashot_data = scan_year_for_all_parashot(2024)
    
    if not parashot_data:
        print("\n❌ No Parashot found. Check API or date range.")
        return 1
    
    # Generate TOML
    print(f"\nGenerating {output_path}...")
    generate_toml(parashot_data, output_path)
    
    print("\n✅ Complete! Run validation:")
    print("   uv run python scripts/validate_aliyah_ranges.py")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
