#!/usr/bin/env python3
# Generated by Claude Sonnet 4.5
"""Query YouTube keywords for a specific video or playlist."""

import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.lib.logging import get_logger
from src.repositories.alya_repo import AlyaRepository
from src.repositories.playlist_repo import PlaylistRepository
from src.repositories.youtube_keyword_repo import YouTubeKeywordRepository

logger = get_logger(__name__)


def show_keywords_for_alya(alya_id: int) -> None:
    """Display keywords for a specific alya."""
    alya_repo = AlyaRepository()
    playlist_repo = PlaylistRepository()
    keyword_repo = YouTubeKeywordRepository()

    # Get alya
    alya = alya_repo.get_by_id(alya_id)
    if not alya:
        logger.error(f"Alya {alya_id} not found")
        return

    # Get playlist
    playlist = playlist_repo.get_by_id(alya.playlist_id)
    if not playlist:
        logger.error(f"Playlist {alya.playlist_id} not found")
        return

    # Get keywords
    keywords = keyword_repo.get_by_alya(alya_id)
    if not keywords:
        logger.error(f"No keywords found for alya {alya_id}")
        return

    # Display
    print("=" * 80)
    print(f"KEYWORDS FOR: {playlist.name} - {alya.name}")
    print("=" * 80)
    print(f"Playlist Type: {playlist.playlist_type}")
    print(f"Book: {playlist.book}")
    print()
    print(f"Tier 1 - Universal ({len(keywords.tier1_keywords)} tags):")
    for tag in keywords.tier1_keywords:
        print(f"  • {tag}")
    print()
    print(f"Tier 2 - Playlist ({len(keywords.tier2_keywords)} tags):")
    for tag in keywords.tier2_keywords:
        print(f"  • {tag}")
    print()
    print(f"Tier 3 - Video-Specific ({len(keywords.tier3_keywords)} tags):")
    for tag in keywords.tier3_keywords:
        print(f"  • {tag}")
    print()
    print(f"Tier 4 - Audience ({len(keywords.tier4_keywords)} tags):")
    for tag in keywords.tier4_keywords:
        print(f"  • {tag}")
    print()
    print("=" * 80)
    print(f"COMBINED TAGS ({keywords.tag_count} tags, {keywords.char_count} chars)")
    print("=" * 80)
    print(keywords.combined_tags)
    print()
    print(f"Character usage: {keywords.char_count}/500 ({keywords.char_count/500*100:.1f}%)")
    print(f"Reserve: {500 - keywords.char_count} chars")
    print("=" * 80)


def show_keywords_for_playlist(playlist_name: str) -> None:
    """Display keywords for all alyot in a playlist."""
    alya_repo = AlyaRepository()
    playlist_repo = PlaylistRepository()
    keyword_repo = YouTubeKeywordRepository()

    # Get playlist
    playlist = playlist_repo.get_by_name(playlist_name)
    if not playlist:
        logger.error(f"Playlist '{playlist_name}' not found")
        return

    # Get all alyot
    alyot = alya_repo.list_by_playlist(playlist.id)
    if not alyot:
        logger.error(f"No alyot found for playlist '{playlist_name}'")
        return

    print("=" * 80)
    print(f"KEYWORDS FOR PLAYLIST: {playlist.name}")
    print("=" * 80)
    print(f"Type: {playlist.playlist_type}")
    print(f"Book: {playlist.book}")
    print(f"Total videos: {len(alyot)}")
    print()

    for alya in alyot:
        keywords = keyword_repo.get_by_alya(alya.id)
        if keywords:
            print(f"  {alya.name:15} - {keywords.tag_count} tags, {keywords.char_count} chars")
        else:
            print(f"  {alya.name:15} - NO KEYWORDS")

    print("=" * 80)


def main() -> None:
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python query_youtube_keywords.py <alya_id>           # Show keywords for specific alya")
        print("  python query_youtube_keywords.py playlist <name>     # Show keywords for all alyot in playlist")
        print()
        print("Examples:")
        print("  python query_youtube_keywords.py 1                   # Alya ID 1")
        print("  python query_youtube_keywords.py playlist נשא        # Parashat Naso")
        print("  python query_youtube_keywords.py playlist 'שיר השירים'  # Song of Songs")
        sys.exit(1)

    if sys.argv[1] == "playlist":
        if len(sys.argv) < 3:
            logger.error("Please provide playlist name")
            sys.exit(1)
        playlist_name = sys.argv[2]
        show_keywords_for_playlist(playlist_name)
    else:
        try:
            alya_id = int(sys.argv[1])
            show_keywords_for_alya(alya_id)
        except ValueError:
            logger.error(f"Invalid alya ID: {sys.argv[1]}")
            sys.exit(1)


if __name__ == "__main__":
    main()
