# Generated by Claude Opus 4.6
"""Rename MP3 files in megillot folders to match JPG thumbnail naming pattern.

Scans a megillot subfolder, extracts the naming pattern from JPG files,
and renames MP3 files to match (ascending order mapping).

Usage:
    uv run python scripts/rename_megillot_audio.py "data/torah_read/מגילות/שיר השירים"
    uv run python scripts/rename_megillot_audio.py "data/torah_read/מגילות/שיר השירים" --apply
    uv run python scripts/rename_megillot_audio.py "data/torah_read/מגילות" --all
    uv run python scripts/rename_megillot_audio.py "data/torah_read/מגילות" --all --apply
"""

import argparse
import re
import sys
from pathlib import Path

# Matches filenames like "Megillat_Kohelet_1.jpg" or "megilat_ruth_4.jpg"
_NUMBERED_JPG_RE = re.compile(r"^(.+_)(\d+)\.jpg$")


def find_jpg_pattern(folder: Path) -> tuple[str, list[int]]:
    """Extract base name pattern and sorted numbers from JPG files.

    Skips JPGs that don't match the `{prefix}_{number}.jpg` pattern
    (e.g. ContactSheet-001.jpg).

    Returns:
        Tuple of (base_pattern, sorted_numbers).
        e.g. ("Megillat_Shir_Hashirim_", [1, 2, 3, ...])
    """
    jpgs = sorted(folder.glob("*.jpg"))
    if not jpgs:
        raise FileNotFoundError(f"No JPG files found in {folder}")

    # Find the first JPG that matches {prefix}_{number}.jpg
    base_pattern = None
    for jpg in jpgs:
        match = _NUMBERED_JPG_RE.match(jpg.name)
        if match:
            base_pattern = match.group(1)
            break

    if base_pattern is None:
        raise ValueError(f"No JPG files match the expected pattern in {folder}")

    # Collect all numbers matching this pattern
    numbers = []
    for jpg in jpgs:
        m = re.match(rf"^{re.escape(base_pattern)}(\d+)\.jpg$", jpg.name)
        if m:
            numbers.append(int(m.group(1)))

    numbers.sort()
    return base_pattern, numbers


def build_rename_mapping(
    folder: Path,
) -> list[tuple[Path, Path]]:
    """Build MP3 rename mapping based on JPG naming pattern.

    Returns:
        List of (old_path, new_path) tuples.
    """
    base_pattern, jpg_numbers = find_jpg_pattern(folder)

    mp3s = sorted(folder.glob("*.mp3"))
    if not mp3s:
        raise FileNotFoundError(f"No MP3 files found in {folder}")

    # Skip MP3s that already match the JPG pattern
    unmatched_mp3s = [
        mp3
        for mp3 in mp3s
        if not re.match(rf"^{re.escape(base_pattern)}\d+\.mp3$", mp3.name)
    ]

    if not unmatched_mp3s and mp3s:
        print(f"  {folder.name}: All MP3 files already match the JPG naming pattern.")
        return []

    if len(unmatched_mp3s) != len(jpg_numbers):
        raise ValueError(
            f"Mismatch in {folder.name}: {len(unmatched_mp3s)} unmatched MP3 files "
            f"vs {len(jpg_numbers)} JPG numbers"
        )

    mapping = []
    for mp3, num in zip(unmatched_mp3s, jpg_numbers):
        new_name = f"{base_pattern}{num}.mp3"
        mapping.append((mp3, mp3.parent / new_name))

    return mapping


def process_folder(folder: Path, *, apply: bool) -> bool:
    """Process a single megillah folder. Returns True if files were renamed."""
    mapping = build_rename_mapping(folder)
    if not mapping:
        return False

    print(f"\n  {folder.name} — {len(mapping)} files to rename:")
    for old, new in mapping:
        print(f"    {old.name} → {new.name}")

    if apply:
        for old, new in mapping:
            old.rename(new)

    return True


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Rename MP3 files to match JPG thumbnail naming pattern."
    )
    parser.add_argument(
        "folder",
        type=Path,
        help="Path to megillah folder, or parent folder with --all",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually rename files (default: dry-run)",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Process all subfolders under the given parent directory",
    )
    args = parser.parse_args()

    folder = args.folder.resolve()
    if not folder.is_dir():
        print(f"Error: {folder} is not a directory", file=sys.stderr)
        sys.exit(1)

    mode = "APPLYING" if args.apply else "DRY RUN"

    if args.all:
        subfolders = sorted(
            [d for d in folder.iterdir() if d.is_dir()],
            key=lambda p: p.name,
        )
        if not subfolders:
            print(f"No subfolders found in {folder}", file=sys.stderr)
            sys.exit(1)

        print(f"{mode} — scanning {len(subfolders)} subfolders:")
        total_renamed = 0
        for sub in subfolders:
            try:
                renamed = process_folder(sub, apply=args.apply)
                if renamed:
                    total_renamed += 1
            except (FileNotFoundError, ValueError) as e:
                print(f"\n  {sub.name}: SKIPPED — {e}")

        if args.apply:
            print(f"\nDone! Renamed files in {total_renamed} folders.")
        else:
            print(f"\nRe-run with --apply to execute.")
    else:
        mapping = build_rename_mapping(folder)
        if not mapping:
            return

        print(f"{mode} — {len(mapping)} files to rename:\n")
        for old, new in mapping:
            print(f"  {old.name} → {new.name}")

        if args.apply:
            for old, new in mapping:
                old.rename(new)
            print(f"\nRenamed {len(mapping)} files.")
        else:
            print("\nRe-run with --apply to execute.")


if __name__ == "__main__":
    main()
