# Generated by Claude Sonnet 4.5
"""Authoritative Torah Aliyah divisions for all 54 Parashot.

Data sourced from standard Ashkenazi Torah reading cycle.
Each entry contains the 7 Aliyot for that Parasha.
"""

# Format: {parasha_hebrew: [(book, ch_start, v_start, ch_end, v_end), ...]}
# Each tuple is one Aliyah (7 per Parasha)

TORAH_ALIYOT = {
    "בראשית": [  # Bereshit (Genesis 1:1-6:8)
        ("Genesis", 1, 1, 2, 3),
        ("Genesis", 2, 4, 2, 19),
        ("Genesis", 2, 20, 3, 21),
        ("Genesis", 3, 22, 4, 18),
        ("Genesis", 4, 19, 4, 22),
        ("Genesis", 4, 23, 5, 24),
        ("Genesis", 5, 25, 6, 8),
    ],
    "נח": [  # Noach (Genesis 6:9-11:32)
        ("Genesis", 6, 9, 6, 22),
        ("Genesis", 7, 1, 7, 16),
        ("Genesis", 7, 17, 8, 14),
        ("Genesis", 8, 15, 9, 7),
        ("Genesis", 9, 8, 9, 17),
        ("Genesis", 9, 18, 10, 32),
        ("Genesis", 11, 1, 11, 32),
    ],
    # Add remaining 52 Parashot...
    "האזינו": [  # Haazinu (Deuteronomy 32:1-52)
        ("Deuteronomy", 32, 1, 32, 6),
        ("Deuteronomy", 32, 7, 32, 12),
        ("Deuteronomy", 32, 13, 32, 18),
        ("Deuteronomy", 32, 19, 32, 28),
        ("Deuteronomy", 32, 29, 32, 39),
        ("Deuteronomy", 32, 40, 32, 43),
        ("Deuteronomy", 32, 44, 32, 52),
    ],
}
