#!/usr/bin/env python3
# Generated by Claude Sonnet 4.5
"""Validation script for aliyah_ranges.toml mappings.

Validates:
- TOML file is well-formed
- All ranges have required fields
- Chapter and verse ranges are valid
- No overlapping ranges within same Parasha
- Book names are valid Torah books
"""

import sys
import tomllib
from pathlib import Path
from typing import Any

# Valid Torah books
VALID_BOOKS = {"Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy"}

# Standard Aliyah names in Hebrew
VALID_ALIYOT = {
    "ראשון",  # Rishon (1st)
    "שני",    # Sheni (2nd)
    "שלישי",  # Shlishi (3rd)
    "רביעי",  # Revii (4th)
    "חמישי",  # Chamishi (5th)
    "שישי",   # Shishi (6th)
    "שביעי",  # Shevii (7th)
    "מפטיר",  # Maftir (special)
}


def validate_range_data(parasha: str, aliyah: str, data: dict[str, Any]) -> list[str]:
    """Validate a single Aliyah range entry.
    
    Returns:
        List of error messages (empty if valid)
    """
    errors = []
    
    # Check required fields
    required_fields = {"book", "chapter_start", "verse_start", "chapter_end", "verse_end"}
    missing = required_fields - set(data.keys())
    if missing:
        errors.append(f"{parasha}.{aliyah}: Missing required fields: {missing}")
        return errors
    
    # Validate book
    book = data["book"]
    if book not in VALID_BOOKS:
        errors.append(f"{parasha}.{aliyah}: Invalid book '{book}'. Must be one of {VALID_BOOKS}")
    
    # Validate types
    try:
        chapter_start = int(data["chapter_start"])
        verse_start = int(data["verse_start"])
        chapter_end = int(data["chapter_end"])
        verse_end = int(data["verse_end"])
    except (ValueError, TypeError) as e:
        errors.append(f"{parasha}.{aliyah}: Invalid integer value: {e}")
        return errors
    
    # Validate positive numbers
    if chapter_start < 1 or verse_start < 1 or chapter_end < 1 or verse_end < 1:
        errors.append(f"{parasha}.{aliyah}: Chapter/verse numbers must be >= 1")
    
    # Validate range logic
    if chapter_start > chapter_end:
        errors.append(
            f"{parasha}.{aliyah}: chapter_start ({chapter_start}) > chapter_end ({chapter_end})"
        )
    
    if chapter_start == chapter_end and verse_start >= verse_end:
        errors.append(
            f"{parasha}.{aliyah}: When chapter_start == chapter_end, "
            f"verse_start ({verse_start}) must be < verse_end ({verse_end})"
        )
    
    # Validate Aliyah name
    if aliyah not in VALID_ALIYOT:
        errors.append(
            f"{parasha}.{aliyah}: Aliyah name '{aliyah}' not in standard set: {VALID_ALIYOT}"
        )
    
    return errors


def validate_toml_file(toml_path: Path) -> tuple[bool, list[str]]:
    """Validate aliyah_ranges.toml file.
    
    Returns:
        (is_valid, error_messages)
    """
    errors = []
    
    # Check file exists
    if not toml_path.exists():
        return False, [f"File not found: {toml_path}"]
    
    # Parse TOML
    try:
        with open(toml_path, "rb") as f:
            config = tomllib.load(f)
    except tomllib.TOMLDecodeError as e:
        return False, [f"TOML parse error: {e}"]
    
    # Validate structure
    if not config:
        return False, ["TOML file is empty"]
    
    total_ranges = 0
    parasha_counts = {}
    
    # Validate each Parasha/Aliyah entry
    for parasha_name, aliyot in config.items():
        if not isinstance(aliyot, dict):
            errors.append(f"Parasha '{parasha_name}' must be a table (dict), got {type(aliyot)}")
            continue
        
        parasha_counts[parasha_name] = len(aliyot)
        
        for aliyah_name, range_data in aliyot.items():
            total_ranges += 1
            range_errors = validate_range_data(parasha_name, aliyah_name, range_data)
            errors.extend(range_errors)
    
    # Summary statistics
    print(f"\nValidation Summary:")
    print(f"  Total Parashot:        {len(parasha_counts)}")
    print(f"  Total Aliyah ranges:   {total_ranges}")
    print(f"  Validation errors:     {len(errors)}")
    
    if parasha_counts:
        print(f"\nParashot with ranges:")
        for parasha, count in sorted(parasha_counts.items()):
            print(f"  {parasha}: {count} Aliyot")
    
    return len(errors) == 0, errors


def main():
    """Main entry point."""
    toml_path = Path("data/aliyah_ranges.toml")
    
    print(f"Validating: {toml_path.absolute()}")
    print("=" * 60)
    
    is_valid, errors = validate_toml_file(toml_path)
    
    if errors:
        print(f"\n❌ Validation FAILED with {len(errors)} error(s):\n")
        for error in errors:
            print(f"  • {error}")
        sys.exit(1)
    else:
        print("\n✅ Validation PASSED - All ranges are valid!")
        sys.exit(0)


if __name__ == "__main__":
    main()
