-- Generated by Claude Sonnet 4.5
-- YouTube Integration DuckDB Schema Extensions
-- Add these tables to src/repositories/db.py ensure_schema()

-- Thumbnail cache (replaces data/thumbnails/metadata.json)
CREATE SEQUENCE IF NOT EXISTS seq_youtube_thumbnails;
CREATE TABLE IF NOT EXISTS youtube_thumbnails (
    id INTEGER PRIMARY KEY DEFAULT nextval('seq_youtube_thumbnails'),
    video_id VARCHAR NOT NULL UNIQUE,  -- YouTube video ID
    original_url VARCHAR NOT NULL,     -- Original thumbnail URL
    cached_path VARCHAR NOT NULL,      -- Local file path
    title VARCHAR,                     -- Original video title
    downloaded_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

-- YouTube upload tracking (audit trail for video uploads)
CREATE SEQUENCE IF NOT EXISTS seq_youtube_uploads;
CREATE TABLE IF NOT EXISTS youtube_uploads (
    id INTEGER PRIMARY KEY DEFAULT nextval('seq_youtube_uploads'),
    alya_video_id INTEGER NOT NULL REFERENCES alya_videos(id),
    old_youtube_video_id VARCHAR,      -- Original video ID (if replacing)
    new_youtube_video_id VARCHAR NOT NULL,  -- New uploaded video ID
    thumbnail_restored BOOLEAN NOT NULL DEFAULT false,
    added_to_playlist BOOLEAN NOT NULL DEFAULT false,
    upload_status VARCHAR NOT NULL DEFAULT 'pending',  -- pending, uploading, completed, failed
    error_message VARCHAR,
    uploaded_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
    completed_at TIMESTAMP
);

-- YouTube playlist metadata (extends playlists table, replaces data/playlists/parasha_playlists.json)
CREATE SEQUENCE IF NOT EXISTS seq_youtube_playlist_meta;
CREATE TABLE IF NOT EXISTS youtube_playlist_meta (
    id INTEGER PRIMARY KEY DEFAULT nextval('seq_youtube_playlist_meta'),
    playlist_id INTEGER NOT NULL UNIQUE REFERENCES playlists(id),
    youtube_playlist_id VARCHAR NOT NULL UNIQUE,  -- Populated to playlists.youtube_playlist_id
    title VARCHAR NOT NULL,            -- YouTube playlist title
    description VARCHAR,               -- YouTube playlist description
    privacy_status VARCHAR NOT NULL DEFAULT 'unlisted',  -- private, unlisted, public
    tradition VARCHAR NOT NULL DEFAULT 'Ashkenaz',  -- Reading tradition
    video_count INTEGER NOT NULL DEFAULT 0,
    expected_video_count INTEGER NOT NULL DEFAULT 7,  -- Usually 7 aliyot
    created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
    updated_at TIMESTAMP NOT NULL DEFAULT current_timestamp
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_youtube_thumbnails_video_id ON youtube_thumbnails(video_id);
CREATE INDEX IF NOT EXISTS idx_youtube_uploads_alya_video ON youtube_uploads(alya_video_id);
CREATE INDEX IF NOT EXISTS idx_youtube_uploads_status ON youtube_uploads(upload_status);
CREATE INDEX IF NOT EXISTS idx_youtube_playlist_meta_playlist ON youtube_playlist_meta(playlist_id);
