"""Test script to verify WavesurferWidget works correctly.

Generated by Claude Sonnet 4.5

This script tests the widget functionality without requiring the full marimo runtime.
Run with: uv run python demos/test_widget.py
"""

import sys
from pathlib import Path

# Add src to path
repo_root = Path(__file__).parent.parent
sys.path.insert(0, str(repo_root / "src"))

from widgets.wavesurfer_widget import WavesurferWidget


def test_widget_creation():
    """Test creating a widget with default parameters."""
    print("Test 1: Creating widget with defaults...")
    widget = WavesurferWidget()
    assert widget.audio_data == b""
    assert widget.regions == []
    assert widget.current_time == 0.0
    assert widget.is_playing is False
    assert widget.duration == 0.0
    print("✅ Widget created successfully")


def test_widget_with_audio():
    """Test loading audio into the widget."""
    print("\nTest 2: Loading sample audio...")
    sample_path = repo_root / "demos" / "assets" / "sample.mp3"

    if not sample_path.exists():
        print(f"⚠️  Sample audio not found at {sample_path}")
        print("   Skipping audio test")
        return

    with open(sample_path, "rb") as f:
        audio_bytes = f.read()

    widget = WavesurferWidget(audio_data=audio_bytes)
    assert len(widget.audio_data) > 0
    print(f"✅ Loaded {len(widget.audio_data):,} bytes of audio")


def test_widget_with_regions():
    """Test creating regions."""
    print("\nTest 3: Creating regions...")
    regions = [
        {
            "id": "test1",
            "start": 0.0,
            "end": 1.0,
            "label": "Test Region 1",
            "color": "rgba(255, 0, 0, 0.3)",
        },
        {
            "id": "test2",
            "start": 1.0,
            "end": 2.0,
            "label": "Test Region 2",
            "color": "rgba(0, 255, 0, 0.3)",
        },
    ]

    widget = WavesurferWidget(regions=regions)
    assert len(widget.regions) == 2
    assert widget.regions[0]["id"] == "test1"
    assert widget.regions[1]["start"] == 1.0
    print(f"✅ Created {len(widget.regions)} regions")


def test_widget_properties():
    """Test widget property access and modification."""
    print("\nTest 4: Testing properties...")
    widget = WavesurferWidget()

    # Test color properties
    widget.waveform_color = "#FF0000"
    assert widget.waveform_color == "#FF0000"

    widget.progress_color = "#00FF00"
    assert widget.progress_color == "#00FF00"

    # Test playback properties
    widget.current_time = 5.5
    assert widget.current_time == 5.5

    widget.is_playing = True
    assert widget.is_playing is True

    # Test selection
    widget.selected_region_id = "test_region"
    assert widget.selected_region_id == "test_region"

    print("✅ All properties working correctly")


def test_playback_speed():
    """Test playback speed control."""
    print("\nTest 5: Testing playback speed...")
    widget = WavesurferWidget()

    # Default speed
    assert widget.playback_speed == 1.0, "Default speed should be 1.0x"

    # Set speed
    widget.playback_speed = 1.5
    assert widget.playback_speed == 1.5, "Speed should update to 1.5x"

    # Test all supported speeds
    for speed in [0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]:
        widget.playback_speed = speed
        assert widget.playback_speed == speed, f"Speed should be {speed}x"

    print("✅ Playback speed control works")


def test_esm_module():
    """Test that ESM module is defined."""
    print("\nTest 6: Checking ESM module...")
    widget = WavesurferWidget()
    assert hasattr(widget, "_esm")
    assert "WaveSurfer" in widget._esm
    assert "RegionsPlugin" in widget._esm
    assert "render" in widget._esm
    print("✅ ESM module defined correctly")


def main():
    """Run all tests."""
    print("=" * 60)
    print("WavesurferWidget Test Suite")
    print("=" * 60)

    try:
        test_widget_creation()
        test_widget_with_audio()
        test_widget_with_regions()
        test_widget_properties()
        test_playback_speed()
        test_esm_module()

        print("\n" + "=" * 60)
        print("✅ All tests passed!")
        print("=" * 60)
        print("\nNext steps:")
        print("  1. Run the demo: marimo run demos/wavesurfer_demo.py")
        print("  2. Open in browser: http://localhost:2718")
        print("  3. Test interactive features")

    except AssertionError as e:
        print(f"\n❌ Test failed: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
