#!/bin/bash
# Verification script for WaveSurfer Widget Demo
# Generated by Claude Sonnet 4.5

set -e  # Exit on error

echo "═══════════════════════════════════════════════════════════════"
echo "  WaveSurfer Widget - Verification Script"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Test 1: Widget module
echo "Test 1: Widget Module"
echo "---------------------"
uv run python demos/test_widget.py
echo ""

# Test 2: marimo notebook validation
echo "Test 2: Notebook Validation"
echo "---------------------------"
uv run marimo check demos/wavesurfer_demo.py
if [ $? -eq 0 ]; then
    echo "✅ Notebook validation passed"
else
    echo "❌ Notebook validation failed"
    exit 1
fi
echo ""

# Test 3: Sample audio exists
echo "Test 3: Sample Audio"
echo "--------------------"
if [ -f "demos/assets/sample.mp3" ]; then
    SIZE=$(wc -c < "demos/assets/sample.mp3")
    echo "✅ Sample audio found (${SIZE} bytes)"
else
    echo "❌ Sample audio not found"
    exit 1
fi
echo ""

# Summary
echo "═══════════════════════════════════════════════════════════════"
echo "  ✅ All Verification Tests Passed!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Next Steps:"
echo "  1. Run the demo:  marimo run demos/wavesurfer_demo.py"
echo "  2. Open browser:  http://localhost:2718"
echo "  3. Test features: drag regions, click table, export JSON"
echo ""
echo "⚠️  DO NOT run with: python demos/wavesurfer_demo.py"
echo "   (marimo notebooks must use 'marimo run', not Python directly)"
echo ""
echo "For detailed testing guide, see: demos/TESTING.md"
echo "═══════════════════════════════════════════════════════════════"
