# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "marimo>=0.10.0",
#   "wavesurfer>=0.3.8",
#   "numpy>=1.24.0",
#   "ipython>=8.0.0",
# ]
# ///
"""Interactive Audio Waveform with Python Wavesurfer

Gallery-ready demonstration using the Python wavesurfer library for audio visualization.
Generated by Claude Sonnet 4.5

Features:
- Waveform visualization with alignment regions
- Editable region table with bidirectional sync
- Playback speed control (0.5x - 2.0x)
- JSON export functionality
- Multi-pitch synthetic audio (3 musical notes)
- Optional file upload for custom audio
"""

import marimo

__generated_with = "0.21.0"
app = marimo.App(width="full")


@app.cell
def imports():
    import marimo as mo
    import numpy as np
    import io
    import json
    from wavesurfer import play, Player

    return Player, io, json, mo, np, play


@app.cell(hide_code=True)
def title(mo):
    mo.md("""
    # 🎵 Interactive Audio Waveform with Python Wavesurfer

    A demonstration using the **Python wavesurfer library** for interactive audio visualization.
    Edit regions in the table below to adjust timing and labels, then regenerate the visualization!

    💡 **Try this**: Modify start/end times or labels in the region table and click "Update Visualization".
    """)
    return


@app.cell(hide_code=True)
def audio_upload_option(mo):
    """Optional file upload for custom audio."""
    mo.md("""
    ## Audio Source

    Choose an audio source:
    - **Upload your own** MP3/WAV/OGG file below, OR
    - **Use the generated sample** (3 different musical pitches)
    """)

    file_picker = mo.ui.file(
        filetypes=[".mp3", ".wav", ".ogg", ".m4a", ".flac"],
        label="Upload Audio File (optional)",
    )
    file_picker
    return (file_picker,)


@app.cell(hide_code=True)
def generate_synthetic_audio(np, io):
    """Generate multi-pitch synthetic audio sample.

    Generated by Claude Sonnet 4.5
    """
    sample_rate = 44100
    duration = 5.0

    # Three musical notes: A4 (440Hz), C5 (523Hz), E5 (659Hz)
    segment_duration = duration / 3

    # Generate three segments with different frequencies
    t1 = np.linspace(0, segment_duration, int(sample_rate * segment_duration))
    segment1 = np.sin(2 * np.pi * 440 * t1)  # A4

    t2 = np.linspace(0, segment_duration, int(sample_rate * segment_duration))
    segment2 = np.sin(2 * np.pi * 523 * t2)  # C5

    t3 = np.linspace(0, segment_duration, int(sample_rate * segment_duration))
    segment3 = np.sin(2 * np.pi * 659 * t3)  # E5

    # Concatenate segments
    audio = np.concatenate([segment1, segment2, segment3])

    # Normalize and convert to 16-bit PCM
    audio = audio / np.max(np.abs(audio)) * 0.8
    audio_int16 = (audio * 32767).astype(np.int16)

    # Create WAV file in memory
    wav_buffer = io.BytesIO()
    data_size = len(audio_int16) * 2
    byte_rate = sample_rate * 2

    wav_buffer.write(b"RIFF")
    wav_buffer.write((36 + data_size).to_bytes(4, "little"))
    wav_buffer.write(b"WAVE")
    wav_buffer.write(b"fmt ")
    wav_buffer.write((16).to_bytes(4, "little"))  # fmt chunk size
    wav_buffer.write((1).to_bytes(2, "little"))  # PCM format
    wav_buffer.write((1).to_bytes(2, "little"))  # Mono
    wav_buffer.write(sample_rate.to_bytes(4, "little"))
    wav_buffer.write(byte_rate.to_bytes(4, "little"))
    wav_buffer.write((2).to_bytes(2, "little"))  # Block align
    wav_buffer.write((16).to_bytes(2, "little"))  # Bits per sample
    wav_buffer.write(b"data")
    wav_buffer.write(data_size.to_bytes(4, "little"))
    wav_buffer.write(audio_int16.tobytes())

    audio_bytes = wav_buffer.getvalue()
    audio_path = "/tmp/wavesurfer_demo_audio.wav"

    # Write to temporary file for wavesurfer to read
    with open(audio_path, "wb") as _f:
        _f.write(audio_bytes)

    return (audio_path,)


@app.cell(hide_code=True)
def load_audio_source(audio_path, file_picker, mo):
    """Load audio from upload or use generated sample."""
    if file_picker.value is not None and len(file_picker.value) > 0:
        # Use uploaded file - save to temp file
        uploaded_audio = file_picker.value[0].contents
        audio_name = file_picker.value[0].name
        temp_path = f"/tmp/{audio_name}"
        with open(temp_path, "wb") as _f:
            _f.write(uploaded_audio)

        source_info = mo.callout(
            f"✅ Using uploaded file: **{audio_name}**", kind="success"
        )
        final_audio_path = temp_path
    else:
        # Use generated sample
        source_info = mo.callout(
            "🎹 Using generated sample (3 musical pitches: A4 → C5 → E5)",
            kind="info",
        )
        final_audio_path = audio_path

    source_info
    return (final_audio_path,)


@app.cell(hide_code=True)
def initial_regions():
    """Define initial audio regions/alignments."""
    regions_data = [
        {
            "id": "intro",
            "start": 0.0,
            "end": 1.67,
            "label": "Intro (A4 - 440Hz)",
        },
        {
            "id": "main",
            "start": 1.67,
            "end": 3.33,
            "label": "Main (C5 - 523Hz)",
        },
        {
            "id": "outro",
            "start": 3.33,
            "end": 5.0,
            "label": "Outro (E5 - 659Hz)",
        },
    ]
    return (regions_data,)


@app.cell(hide_code=True)
def playback_speed_control(mo):
    """Playback speed selector."""
    mo.md("## ⏩ Playback Speed")

    speed_selector = mo.ui.dropdown(
        options={
            "0.5x": 0.5,
            "0.75x": 0.75,
            "1.0x (Normal)": 1.0,
            "1.25x": 1.25,
            "1.5x": 1.5,
            "1.75x": 1.75,
            "2.0x": 2.0,
        },
        value=1.0,
        label="Speed",
    )
    speed_selector
    return (speed_selector,)


@app.cell(hide_code=True)
def region_table_ui(mo, regions_data):
    """Create editable table for regions."""
    mo.md("## 📊 Audio Regions / Alignments")

    # Create table data structure
    table_data = mo.ui.table(
        data=regions_data,
        label="Edit regions below",
        selection=None,
    )

    table_data
    return (table_data,)


@app.cell(hide_code=True)
def update_button(mo):
    """Button to trigger visualization update."""
    update_btn = mo.ui.button(
        label="Update Visualization",
        kind="success",
    )
    update_btn
    return (update_btn,)


@app.cell
def get_current_regions(regions_data, table_data, update_btn):
    """Get current regions from table (reactive to button click)."""
    # Trigger reactive update when button is clicked
    _ = update_btn.value

    # Use table data if modified, otherwise use initial data
    if table_data.value is not None and len(table_data.value) > 0:
        current_regions = table_data.value
    else:
        current_regions = regions_data

    return (current_regions,)


@app.cell(hide_code=True)
def display_waveform(current_regions, final_audio_path, mo, play, speed_selector):
    """Display waveform with alignments."""
    mo.md("## 🎵 Waveform Visualization")

    # Convert regions to alignment format for wavesurfer
    alignments = [
        {
            "start": float(r["start"]),
            "end": float(r["end"]),
            "content": r["label"],
        }
        for r in current_regions
    ]

    # Note: The Python wavesurfer library doesn't support playback speed in the same way
    # The speed_selector is provided for UI consistency but may not affect playback
    speed_note = mo.callout(
        f"ℹ️ Current speed setting: **{speed_selector.value}x** (Note: Python wavesurfer may not support runtime speed control)",
        kind="info",
    )

    # Display the waveform with alignments
    # The play() function from wavesurfer library will render the audio with regions
    try:
        _ = play(final_audio_path, alignments=alignments)
        display_result = mo.vstack([speed_note])
    except Exception as e:
        display_result = mo.callout(
            f"❌ Error displaying waveform: {str(e)}", kind="danger"
        )

    display_result
    return (alignments,)


@app.cell(hide_code=True)
def region_stats(current_regions, mo):
    """Display statistics about regions."""
    total_regions = len(current_regions)
    total_duration = sum(float(r["end"]) - float(r["start"]) for r in current_regions)

    mo.md(f"""
    ### 📈 Statistics

    - **Total Regions**: {total_regions}
    - **Total Coverage**: {total_duration:.2f} seconds
    - **Average Region Duration**: {total_duration / total_regions:.2f} seconds
    """)
    return


@app.cell(hide_code=True)
def export_section(mo):
    """Export functionality header."""
    mo.md("## 📥 Export Alignments")
    return


@app.cell(hide_code=True)
def export_handler(current_regions, json, mo):
    """Handle JSON export of regions."""
    export_data = {
        "alignments": current_regions,
        "version": "1.0",
        "format": "wavesurfer-python",
    }

    json_output = json.dumps(export_data, indent=2)

    download_btn = mo.ui.download(
        data=json_output.encode("utf-8"),
        filename="alignments.json",
        label="Download JSON",
    )

    mo.vstack([
        mo.md(f"""
        **Export Format**: JSON

        ```json
        {json_output}
        ```
        """),
        download_btn,
    ])
    return


@app.cell(hide_code=True)
def usage_guide(mo):
    """Display usage instructions."""
    mo.md("""
    ---

    ## 📖 How to Use

    1. **View Waveform**: The audio waveform is displayed with colored regions showing different segments
    2. **Edit Regions**: Modify the start/end times or labels in the table above
    3. **Update**: Click "Update Visualization" to regenerate the waveform with your changes
    4. **Playback Speed**: Select different playback speeds (note: may not be supported by Python wavesurfer)
    5. **Upload Audio**: Optionally upload your own audio file to visualize
    6. **Export**: Download your alignments as JSON for use in other applications

    ## 🎯 Use Cases

    - **Audio Transcription**: Mark sentence or word boundaries for transcription work
    - **Podcast Editing**: Identify chapter boundaries or topic segments
    - **Music Analysis**: Label verse/chorus sections or instrument entries
    - **Language Learning**: Align audio with text for language practice
    - **Torah Reading**: Synchronize audio with verse boundaries (pasuk alignments)

    ## 🔧 Technical Details

    - **Library**: Python wavesurfer (v0.3.8+)
    - **Framework**: marimo reactive notebooks
    - **Audio Formats**: WAV, MP3, FLAC, OGG, M4A
    - **Alignment Format**: JSON with start/end times and content labels
    - **Dependencies**: marimo, wavesurfer, numpy
    """)
    return


if __name__ == "__main__":
    app.run()
