# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "marimo>=0.10.0",
#   "anywidget>=0.9.0",
#   "traitlets>=5.0.0",
#   "numpy>=1.24.0",
# ]
# ///
"""Interactive Audio Waveform Widget with WaveSurfer.js

Gallery-ready demonstration of a custom anywidget for audio visualization.
Generated by Claude Sonnet 4.5
Edited by Claude Sonnet 4.5

Features:
- Interactive waveform with draggable regions
- Two-way sync between table and waveform
- Play/pause controls with timeline
- Adjustable playback speed (0.5x - 2.0x)
- JSON export functionality
- Multi-pitch synthetic audio (3 musical notes)
- Optional file upload for custom audio
"""

import marimo

__generated_with = "0.21.0"
app = marimo.App(width="full")


@app.cell
def imports():
    import marimo as mo
    import anywidget
    import traitlets

    return anywidget, mo, traitlets


@app.cell(hide_code=True)
def title(mo):
    mo.md("""
    # 🎵 Interactive Audio Waveform Widget

    A custom `anywidget` integrating **wavesurfer.js** for interactive audio visualization.
    Drag region boundaries to adjust segments, click regions to select them, or use the table below!

    💡 **Try this**: Drag the colored region edges in the waveform to adjust timing.
    """)
    return


@app.cell(hide_code=True)
def audio_upload_option(mo):
    """Optional file upload for custom audio."""
    mo.md("""
    ## Audio Source

    Choose an audio source:
    - **Upload your own** MP3/WAV/OGG file below, OR
    - **Use the generated sample** (3 different musical pitches)
    """)

    file_picker = mo.ui.file(
        filetypes=[".mp3", ".wav", ".ogg", ".m4a"],
        label="Upload Audio File (optional)",
    )
    file_picker
    return (file_picker,)


@app.cell(hide_code=True)
def wavesurfer_widget_code(anywidget, traitlets):
    """WaveSurfer anywidget implementation.

    Edited by Claude Sonnet 4.5
    """

    class WavesurferWidget(anywidget.AnyWidget):
        """Interactive audio waveform widget using wavesurfer.js v7.

        Attributes:
            audio_data: Audio file as bytes (converted to data URL in JS)
            regions: List of {id, start, end, label, color, drag, resize}
            current_time: Current playback position in seconds
            is_playing: Whether audio is currently playing
            selected_region_id: ID of currently selected region
            duration: Total audio duration in seconds (set by JS)
            waveform_color: Color of the waveform
            progress_color: Color of the played portion
            height: Height of waveform in pixels
        """

        # Audio data (Python → JavaScript)
        audio_data = traitlets.Bytes(default_value=b"").tag(sync=True)

        # Regions (bidirectional)
        regions = traitlets.List(trait=traitlets.Dict()).tag(sync=True)

        # Playback state (bidirectional)
        current_time = traitlets.Float(default_value=0.0).tag(sync=True)
        is_playing = traitlets.Bool(default_value=False).tag(sync=True)

        # Selection state (bidirectional)
        selected_region_id = traitlets.Unicode(default_value="").tag(sync=True)

        # Audio metadata (JavaScript → Python)
        duration = traitlets.Float(default_value=0.0).tag(sync=True)

        # Appearance (Python → JavaScript)
        waveform_color = traitlets.Unicode(default_value="#4F4A85").tag(sync=True)
        progress_color = traitlets.Unicode(default_value="#383351").tag(sync=True)
        height = traitlets.Int(default_value=128).tag(sync=True)

        # Playback speed (Python ↔ JavaScript)
        playback_speed = traitlets.Float(default_value=1.0).tag(sync=True)

        _esm = """
        import WaveSurfer from 'https://cdn.jsdelivr.net/npm/wavesurfer.js@7/dist/wavesurfer.esm.js';
        import RegionsPlugin from 'https://cdn.jsdelivr.net/npm/wavesurfer.js@7/dist/plugins/regions.esm.js';
        import TimelinePlugin from 'https://cdn.jsdelivr.net/npm/wavesurfer.js@7/dist/plugins/timeline.esm.js';

        function render({ model, el }) {
          const container = document.createElement('div');
          container.style.width = '100%';
          container.style.fontFamily = 'sans-serif';

          const waveformDiv = document.createElement('div');
          waveformDiv.id = 'waveform-' + Math.random().toString(36).substr(2, 9);

          const controls = document.createElement('div');
          controls.style.marginTop = '10px';
          controls.style.display = 'flex';
          controls.style.gap = '10px';
          controls.style.alignItems = 'center';

          const playPauseBtn = document.createElement('button');
          playPauseBtn.textContent = '▶ Play';
          playPauseBtn.style.padding = '8px 16px';
          playPauseBtn.style.cursor = 'pointer';
          playPauseBtn.style.fontSize = '14px';

          const speedLabel = document.createElement('span');
          speedLabel.textContent = 'Speed: ';
          speedLabel.style.cssText = 'font-size:14px;margin-left:8px;';

          const speedSelect = document.createElement('select');
          speedSelect.style.cssText = 'padding:4px 8px;cursor:pointer;font-size:14px;border:1px solid #ccc;border-radius:4px;background:#fff;';
          const speeds = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0];
          speeds.forEach(speed => {
            const option = document.createElement('option');
            option.value = speed;
            option.textContent = `${speed}x`;
            if (speed === 1.0) option.selected = true;
            speedSelect.appendChild(option);
          });

          const timeDisplay = document.createElement('span');
          timeDisplay.style.fontFamily = 'monospace';
          timeDisplay.style.fontSize = '14px';
          timeDisplay.textContent = '0.000 / 0.000';

          const regionInfo = document.createElement('div');
          regionInfo.style.marginTop = '10px';
          regionInfo.style.padding = '8px';
          regionInfo.style.backgroundColor = '#f0f0f0';
          regionInfo.style.borderRadius = '4px';
          regionInfo.style.fontSize = '13px';
          regionInfo.textContent = 'Click a region to select it';

          controls.appendChild(playPauseBtn);
          controls.appendChild(speedLabel);
          controls.appendChild(speedSelect);
          controls.appendChild(timeDisplay);
          container.appendChild(waveformDiv);
          container.appendChild(controls);
          container.appendChild(regionInfo);
          el.appendChild(container);

          const regionsPlugin = RegionsPlugin.create();
          const timelinePlugin = TimelinePlugin.create({
            height: 20,
            timeInterval: 0.5,
            primaryLabelInterval: 5,
            style: { fontSize: '10px', color: '#6B7280' },
          });

          const wavesurfer = WaveSurfer.create({
            container: waveformDiv,
            waveColor: model.get('waveform_color'),
            progressColor: model.get('progress_color'),
            height: model.get('height'),
            normalize: true,
            plugins: [regionsPlugin, timelinePlugin],
          });

          const audioData = model.get('audio_data');
          if (audioData && audioData.byteLength > 0) {
            const blob = new Blob([audioData], { type: 'audio/mpeg' });
            const url = URL.createObjectURL(blob);
            wavesurfer.load(url);
          }

          wavesurfer.on('ready', () => {
            const dur = wavesurfer.getDuration();
            model.set('duration', dur);
            model.save_changes();
            timeDisplay.textContent = `0.000 / ${dur.toFixed(3)}`;

            // Set initial playback speed
            const initialSpeed = model.get('playback_speed');
            if (initialSpeed && initialSpeed !== 1.0) {
              wavesurfer.setPlaybackRate(initialSpeed);
              speedSelect.value = initialSpeed;
            }

            const regions = model.get('regions') || [];
            regions.forEach((region) => {
              regionsPlugin.addRegion({
                id: region.id,
                start: region.start,
                end: region.end,
                color: region.color || 'rgba(0, 123, 255, 0.3)',
                drag: region.drag !== false,
                resize: region.resize !== false,
                content: region.label || '',
              });
            });
          });

          wavesurfer.on('timeupdate', (currentTime) => {
            const dur = wavesurfer.getDuration();
            timeDisplay.textContent = `${currentTime.toFixed(3)} / ${dur.toFixed(3)}`;
          });

          wavesurfer.on('play', () => {
            model.set('is_playing', true);
            model.save_changes();
            playPauseBtn.textContent = '⏸ Pause';
          });

          wavesurfer.on('pause', () => {
            model.set('is_playing', false);
            model.set('current_time', wavesurfer.getCurrentTime());
            model.save_changes();
            playPauseBtn.textContent = '▶ Play';
          });

          playPauseBtn.addEventListener('click', () => {
            wavesurfer.playPause();
          });

          speedSelect.addEventListener('change', () => {
            const speed = parseFloat(speedSelect.value);
            wavesurfer.setPlaybackRate(speed);
            model.set('playback_speed', speed);
            model.save_changes();
          });

          regionsPlugin.on('region-updated', (region) => {
            const regions = model.get('regions').map((r) => {
              if (r.id === region.id) {
                return { ...r, start: region.start, end: region.end };
              }
              return r;
            });
            model.set('regions', regions);
            model.save_changes();
          });

          regionsPlugin.on('region-clicked', (region, e) => {
            regionsPlugin.getRegions().forEach((r) => {
              r.element.style.opacity = r.id === region.id ? '0.6' : '0.3';
            });

            model.set('selected_region_id', region.id);
            model.save_changes();

            regionInfo.innerHTML = `
              <strong>Selected:</strong> ${region.content || region.id}<br>
              <strong>Time:</strong> ${region.start.toFixed(3)}s - ${region.end.toFixed(3)}s
              (duration: ${(region.end - region.start).toFixed(3)}s)
            `;

            e.stopPropagation();
          });

          model.on('change:audio_data', () => {
            const audioData = model.get('audio_data');
            if (audioData && audioData.byteLength > 0) {
              const blob = new Blob([audioData], { type: 'audio/mpeg' });
              const url = URL.createObjectURL(blob);
              wavesurfer.load(url);
            }
          });

          model.on('change:regions', () => {
            regionsPlugin.clearRegions();
            const regions = model.get('regions') || [];
            regions.forEach((region) => {
              regionsPlugin.addRegion({
                id: region.id,
                start: region.start,
                end: region.end,
                color: region.color || 'rgba(0, 123, 255, 0.3)',
                drag: region.drag !== false,
                resize: region.resize !== false,
                content: region.label || '',
              });
            });
          });

          model.on('change:current_time', () => {
            wavesurfer.setTime(model.get('current_time'));
          });

          model.on('change:playback_speed', () => {
            const speed = model.get('playback_speed');
            wavesurfer.setPlaybackRate(speed);
            speedSelect.value = speed;
          });

          return () => wavesurfer.destroy();
        }

        export default { render };
        """

        _css = """
        .wavesurfer-region {
          transition: opacity 0.2s ease;
        }
        """

    return (WavesurferWidget,)


@app.cell(hide_code=True)
def generate_sample_audio():
    """Generate 5-second synthetic audio with 3 different pitches.

    Generated by Claude Sonnet 4.5
    Edited by Claude Sonnet 4.5
    """
    import io
    import numpy as np

    # Audio parameters
    sample_rate = 22050  # Lower sample rate for smaller file
    duration = 5.0

    # Three pitches forming A major chord
    frequencies = [
        (440.0, 0.0, 1.0),    # A4 (intro)
        (523.25, 1.0, 3.5),   # C5 (main)
        (659.25, 3.5, 5.0),   # E5 (outro)
    ]

    # Generate combined waveform
    t = np.linspace(0, duration, int(sample_rate * duration))
    audio = np.zeros_like(t)

    for freq, start, end in frequencies:
        # Create segment mask
        mask = (t >= start) & (t < end)
        segment_t = t[mask] - start

        # Generate sine wave for this segment
        segment = np.sin(2 * np.pi * freq * segment_t)

        # Apply crossfade at boundaries (50ms)
        crossfade_duration = 0.05
        crossfade_samples = int(crossfade_duration * sample_rate)

        # Fade in at start
        if start > 0:
            fade_in = np.ones_like(segment)
            fade_in[:crossfade_samples] = np.linspace(0, 1, crossfade_samples)
            segment *= fade_in

        # Fade out at end
        if end < duration:
            fade_out = np.ones_like(segment)
            fade_out[-crossfade_samples:] = np.linspace(1, 0, crossfade_samples)
            segment *= fade_out

        audio[mask] = segment

    # Convert to 16-bit PCM
    audio_int16 = (audio * 32767).astype(np.int16)

    # Create WAV file in memory
    wav_buffer = io.BytesIO()

    # Write WAV header manually (simple 16-bit mono WAV)
    num_samples = len(audio_int16)
    byte_rate = sample_rate * 2  # 16-bit = 2 bytes
    data_size = num_samples * 2

    wav_buffer.write(b"RIFF")
    wav_buffer.write((36 + data_size).to_bytes(4, "little"))
    wav_buffer.write(b"WAVE")
    wav_buffer.write(b"fmt ")
    wav_buffer.write((16).to_bytes(4, "little"))  # fmt chunk size
    wav_buffer.write((1).to_bytes(2, "little"))  # PCM format
    wav_buffer.write((1).to_bytes(2, "little"))  # Mono
    wav_buffer.write(sample_rate.to_bytes(4, "little"))
    wav_buffer.write(byte_rate.to_bytes(4, "little"))
    wav_buffer.write((2).to_bytes(2, "little"))  # Block align
    wav_buffer.write((16).to_bytes(2, "little"))  # Bits per sample
    wav_buffer.write(b"data")
    wav_buffer.write(data_size.to_bytes(4, "little"))
    wav_buffer.write(audio_int16.tobytes())

    audio_bytes = wav_buffer.getvalue()
    return (audio_bytes,)


@app.cell(hide_code=True)
def load_audio_source(audio_bytes, file_picker, mo):
    """Load audio from upload or use generated sample."""
    if file_picker.value is not None and len(file_picker.value) > 0:
        # Use uploaded file
        uploaded_audio = file_picker.value[0].contents
        audio_name = file_picker.value[0].name
        source_info = mo.callout(
            f"✅ Using uploaded file: **{audio_name}**", kind="success"
        )
        final_audio = uploaded_audio
    else:
        # Use generated sample
        source_info = mo.callout(
            "🎹 Using generated sample (3 musical pitches: A4 → C5 → E5)",
            kind="info",
        )
        final_audio = audio_bytes

    source_info
    return (final_audio,)


@app.cell(hide_code=True)
def define_regions():
    """Define sample audio regions."""
    regions = [
        {
            "id": "intro",
            "start": 0.0,
            "end": 1.0,
            "label": "Intro (A4 - 440Hz)",
            "color": "rgba(59, 130, 246, 0.3)",
        },
        {
            "id": "main",
            "start": 1.0,
            "end": 3.5,
            "label": "Main (C5 - 523Hz)",
            "color": "rgba(16, 185, 129, 0.3)",
        },
        {
            "id": "outro",
            "start": 3.5,
            "end": 5.0,
            "label": "Outro (E5 - 659Hz)",
            "color": "rgba(245, 158, 11, 0.3)",
        },
    ]
    return (regions,)


@app.cell(hide_code=True)
def create_widget(WavesurferWidget, final_audio, regions):
    """Create the wavesurfer widget."""
    widget = WavesurferWidget(
        audio_data=final_audio,
        regions=regions,
        waveform_color="#4F4A85",
        progress_color="#7C3AED",
        height=150,
    )
    return (widget,)


@app.cell(hide_code=True)
def display_widget(mo, widget):
    """Create widget UI wrapper."""
    widget_ui = mo.ui.anywidget(widget)
    return (widget_ui,)


@app.cell(hide_code=True)
def show_widget_with_state(mo, widget_ui):
    """Display widget alongside live state."""
    state = widget_ui.value

    state_display = mo.md(f"""
    **State**
    - Time: `{state.get('current_time', 0):.3f}s / {state.get('duration', 0):.3f}s`
    - Status: {'▶️ Playing' if state.get('is_playing', False) else '⏸️ Paused'}
    - Selected: `{state.get('selected_region_id', '') or '(none)'}`
    - Regions: `{len(state.get('regions', []))}`
    - Speed: `{state.get('playback_speed', 1.0):.2f}x`
    """)

    mo.hstack([widget_ui, state_display], widths=[3, 1])
    return


@app.cell(hide_code=True)
def table_intro(mo):
    mo.md("""
    ## Regions Table

    Click a row to jump to that region. Drag boundaries in the waveform above to update the table!
    """)
    return


@app.cell(hide_code=True)
def regions_table(mo, widget_ui):
    """Display and interact with regions via table."""
    _regions = widget_ui.value.get("regions", [])

    table_data = [
        {
            "ID": r["id"],
            "Label": r.get("label", ""),
            "Start": f"{r['start']:.3f}s",
            "End": f"{r['end']:.3f}s",
            "Duration": f"{r['end'] - r['start']:.3f}s",
        }
        for r in _regions
    ]

    table = mo.ui.table(table_data, selection="single", label="Audio Regions")
    table
    return (table,)


@app.cell(hide_code=True)
def sync_table_to_widget(mo, table, widget):
    """Seek to selected table row."""
    if not table.value:
        mo.stop(True)

    selected = table.value[0]
    region_id = selected["ID"]

    for r in widget.regions:
        if r["id"] == region_id:
            widget.current_time = r["start"]
            widget.selected_region_id = region_id
            break

    mo.callout(f"🎯 Jumped to: **{selected['Label']}**", kind="info")
    return


@app.cell(hide_code=True)
def export_intro(mo):
    mo.md("""
    ## Export

    Save your annotated regions as JSON:
    """)
    return


@app.cell(hide_code=True)
def export_button(mo):
    """Create export button."""
    export_btn = mo.ui.run_button(label="📥 Export Regions")
    export_btn
    return (export_btn,)


@app.cell(hide_code=True)
def export_handler(export_btn, mo, widget_ui):
    """Handle export button click."""
    import json

    if not export_btn.value:
        mo.stop(True)

    json_output = json.dumps(widget_ui.value.get("regions", []), indent=2)
    mo.vstack(
        [
            mo.callout("✅ Exported successfully!", kind="success"),
            mo.ui.code_editor(value=json_output, language="json", disabled=True),
        ]
    )
    return


@app.cell(hide_code=True)
def documentation(mo):
    mo.md("""
    ---

    ## How It Works

    This widget combines:
    - **[anywidget](https://anywidget.dev/)** - Portable widget framework
    - **[wavesurfer.js](https://wavesurfer.xyz/)** - Audio visualization (loaded from CDN)
    - **[marimo](https://marimo.io/)** - Reactive Python notebooks

    ### Key Features

    - **Bidirectional sync**: Python ↔ JavaScript state automatically synchronized via traitlets
    - **Multi-pitch audio**: Generated sample uses 3 musical notes (A4, C5, E5) forming A major chord
    - **File upload support**: Upload your own audio files (MP3, WAV, OGG, M4A)
    - **Self-contained**: Works immediately - no build step, no external dependencies
    - **Interactive**: Drag regions, click table rows, play audio - everything updates reactively

    ### Use Cases

    - Audio transcription and annotation
    - Podcast chapter marking
    - Music analysis (verse/chorus/bridge)
    - Language learning with sentence-level audio

    ---

    **Resources**:
    [wavesurfer.js docs](https://wavesurfer.xyz/docs/) •
    [anywidget guide](https://anywidget.dev/en/getting-started/) •
    [marimo gallery](https://marimo.io/gallery)
    """)
    return


if __name__ == "__main__":
    app.run()
