"""Interactive Audio Waveform Visualization with WaveSurfer.js + marimo

Generated by Claude Sonnet 4.5

This marimo notebook demonstrates how to create an interactive audio waveform
widget using anywidget and wavesurfer.js. Features include:

- Audio waveform visualization
- Draggable/resizable regions for audio segments
- Two-way sync between table and waveform
- Play/pause controls with time display
- Timeline with time markers

Perfect for:
- Audio annotation and transcription
- Podcast episode segmentation
- Music analysis and beat marking
- Torah reading verse alignment (our use case!)

Launch: marimo run demos/wavesurfer_demo.py
"""

import marimo

__generated_with = "0.20.4"
app = marimo.App(width="full")


@app.cell
def imports():
    import marimo as mo

    return (mo,)


@app.cell
def title(mo):
    mo.md("""
    # 🎵 Interactive Audio Waveform Visualization

    This demo showcases a custom `anywidget` that integrates **wavesurfer.js** with marimo
    for interactive audio waveform visualization and segment annotation.

    ## Features

    - 🎨 **Visual Waveform**: See your audio as an interactive waveform
    - 🏷️ **Draggable Regions**: Mark segments with labels and colors
    - ⏯️ **Playback Controls**: Play/pause with live time tracking
    - 🔄 **Two-Way Sync**: Click table rows or waveform regions for bidirectional updates
    - 📏 **Timeline**: Time axis for precise positioning

    ---
    """)
    return


@app.cell
def widget_setup(mo):
    """Import the WavesurferWidget and dependencies."""
    import sys
    from pathlib import Path

    # Add src to path for widget import
    repo_root = Path(__file__).parent.parent
    if str(repo_root / "src") not in sys.path:
        sys.path.insert(0, str(repo_root / "src"))

    from widgets.wavesurfer_widget import WavesurferWidget

    mo.md("**Widget imported successfully!** ✅")
    return WavesurferWidget, repo_root


@app.cell
def sample_audio_note(mo):
    mo.md("""
    ## Step 1: Load Sample Audio

    For this demo, you'll need to provide an audio file. You can:

    1. **Upload an MP3/WAV file** using the file picker below, OR
    2. **Use a sample file** from your project (e.g., Torah reading audio)

    Supported formats: MP3, WAV, OGG, M4A
    """)
    return


@app.cell
def audio_file_picker(mo):
    """File picker for audio upload."""
    file_picker = mo.ui.file(
        filetypes=[".mp3", ".wav", ".ogg", ".m4a"],
        label="Upload Audio File",
    )
    file_picker
    return (file_picker,)


@app.cell
def load_audio(file_picker, mo, repo_root):
    """Load audio from uploaded file or fallback to sample."""
    audio_bytes = None
    audio_name = "No audio loaded"
    status_message = ""

    if file_picker.value is not None and len(file_picker.value) > 0:
        audio_bytes = file_picker.value[0].contents
        audio_name = file_picker.value[0].name
        status_message = f"✅ **Loaded:** {audio_name}"
    else:
        # Try to find a sample audio file in the project
        sample_paths = [
            repo_root / "demos" / "assets" / "sample.mp3",  # Demo sample file
            repo_root / "data" / "audio" / "sample.mp3",
            repo_root / "data" / "cache" / "audio_segments",
        ]

        for sample_path in sample_paths:
            if sample_path.exists():
                if sample_path.is_file():
                    # Direct file path
                    with open(sample_path, "rb") as f:
                        audio_bytes = f.read()
                    audio_name = sample_path.name
                    status_message = f"📁 **Using sample:** {audio_name}"
                    break
                else:
                    # Directory - find first MP3
                    audio_files = list(sample_path.glob("*.mp3"))
                    if audio_files:
                        sample_file = audio_files[0]
                        with open(sample_file, "rb") as f:
                            audio_bytes = f.read()
                        audio_name = sample_file.name
                        status_message = f"📁 **Using sample:** {audio_name}"
                        break

        if audio_bytes is None:
            status_message = """
⚠️ **No audio file loaded**

Please upload an audio file above or the sample file will be downloaded.
"""

    mo.md(status_message)
    return (audio_bytes,)


@app.cell
def sample_regions_setup(mo):
    mo.md("""
    ## Step 2: Define Audio Regions

    Regions represent segments of audio with start/end times and labels.
    These could be:
    - Verses in a Torah reading
    - Chapters in a podcast
    - Speakers in an interview
    - Sections in a song

    Modify the regions below or let them auto-generate based on audio duration!
    """)
    return


@app.cell
def create_sample_regions():
    """Create sample regions for demonstration."""
    # Sample regions (will be adjusted based on actual audio duration)
    sample_regions = [
        {
            "id": "intro",
            "start": 0.0,
            "end": 3.0,
            "label": "Introduction",
            "color": "rgba(59, 130, 246, 0.3)",  # Blue
            "drag": True,
            "resize": True,
        },
        {
            "id": "segment_1",
            "start": 3.0,
            "end": 8.5,
            "label": "Segment 1",
            "color": "rgba(16, 185, 129, 0.3)",  # Green
            "drag": True,
            "resize": True,
        },
        {
            "id": "segment_2",
            "start": 8.5,
            "end": 15.0,
            "label": "Segment 2",
            "color": "rgba(245, 158, 11, 0.3)",  # Orange
            "drag": True,
            "resize": True,
        },
        {
            "id": "outro",
            "start": 15.0,
            "end": 20.0,
            "label": "Conclusion",
            "color": "rgba(139, 92, 246, 0.3)",  # Purple
            "drag": True,
            "resize": True,
        },
    ]
    return (sample_regions,)


@app.cell
def create_widget(WavesurferWidget, audio_bytes, mo, sample_regions):
    """Create the wavesurfer widget if audio is loaded."""
    if audio_bytes is None:
        mo.stop(True, mo.md("⏹️ Waiting for audio file..."))

    widget = WavesurferWidget(
        audio_data=audio_bytes,
        regions=sample_regions,
        waveform_color="#4F4A85",
        progress_color="#7C3AED",
        height=150,
    )

    # Wrap in marimo's anywidget UI element
    widget_ui = mo.ui.anywidget(widget)

    mo.md("## Step 3: Interactive Waveform")
    return widget, widget_ui


@app.cell
def display_widget(widget_ui):
    """Display the wavesurfer widget."""
    widget_ui
    return


@app.cell
def regions_table_setup(mo):
    mo.md("""
    ## Step 4: Regions Table (Two-Way Sync)

    Click a row in the table to seek to that region in the waveform.
    Drag region boundaries in the waveform to update the table!
    """)
    return


@app.cell
def regions_table(mo, widget_ui):
    """Display regions as an editable table."""
    if not hasattr(widget_ui, "value"):
        mo.stop(True)

    regions = widget_ui.value.get("regions", [])

    table_data = [
        {
            "ID": r["id"],
            "Label": r.get("label", ""),
            "Start (s)": round(r["start"], 3),
            "End (s)": round(r["end"], 3),
            "Duration (s)": round(r["end"] - r["start"], 3),
        }
        for r in regions
    ]

    table = mo.ui.table(
        table_data,
        selection="single",
        label="Audio Regions",
    )

    table
    return (table,)


@app.cell
def sync_table_to_waveform(mo, table, widget):
    """When user clicks a table row, seek to that region."""
    if not table.value:
        mo.stop(True)

    selected_row = table.value[0]
    region_id = selected_row["ID"]

    # Find the region and seek to its start time
    for region in widget.regions:
        if region["id"] == region_id:
            widget.current_time = region["start"]
            widget.selected_region_id = region_id
            break

    mo.md(f"**Selected:** {selected_row['Label']} ({region_id})")
    return


@app.cell
def widget_state_display(mo, widget_ui):
    """Display current widget state for debugging/demonstration."""
    if not hasattr(widget_ui, "value"):
        mo.stop(True)

    state = widget_ui.value
    current_time = state.get("current_time", 0.0)
    duration = state.get("duration", 0.0)
    is_playing = state.get("is_playing", False)
    selected_id = state.get("selected_region_id", "")

    mo.md(
        f"""
        ### 📊 Widget State

        - **Playback**: {'▶️ Playing' if is_playing else '⏸️ Paused'}
        - **Current Time**: {current_time:.3f}s / {duration:.3f}s
        - **Selected Region**: {selected_id or '(none)'}
        - **Total Regions**: {len(state.get('regions', []))}
        """
    )
    return


@app.cell
def export_functionality(mo):
    mo.md("""
    ## Step 5: Export Annotations

    Save your annotated regions as JSON for use in other applications!
    """)
    return


@app.cell
def export_button_create(mo, widget_ui):
    """Create the export button."""
    if not hasattr(widget_ui, "value"):
        mo.stop(True)

    export_btn = mo.ui.run_button(label="📥 Export Regions as JSON")
    return export_btn


@app.cell
def export_button_handler(mo, widget_ui, export_btn):
    """Handle export button clicks and display results."""
    import json

    if export_btn.value:
        _regions = widget_ui.value.get("regions", [])
        json_output = json.dumps(_regions, indent=2)

        result = mo.vstack(
            [
                mo.callout(
                    "✅ Regions exported! Copy the JSON below:",
                    kind="success",
                ),
                mo.ui.code_editor(value=json_output, language="json", disabled=True),
            ]
        )
    else:
        result = export_btn

    result
    return


@app.cell
def documentation(mo):
    mo.md("""
    ---

    ## 🛠️ How It Works

    This widget is built with:

    - **[anywidget](https://anywidget.dev/)**: Framework for portable Jupyter/marimo widgets
    - **[wavesurfer.js](https://wavesurfer.xyz/)**: JavaScript audio waveform visualization library
    - **[marimo](https://marimo.io/)**: Reactive Python notebooks

    ### Architecture

    ```
    ┌─────────────────────────────────────┐
    │ Python: WavesurferWidget           │
    │  - audio_data (bytes)               │
    │  - regions (list of dicts)          │
    │  - current_time (float)             │
    │  - is_playing (bool)                │
    └──────────────┬──────────────────────┘
                   │ traitlets sync
    ┌──────────────▼──────────────────────┐
    │ JavaScript: wavesurfer.js ESM       │
    │  - Load audio from data URL         │
    │  - Render waveform + regions        │
    │  - Emit events → update Python      │
    └─────────────────────────────────────┘
    ```

    ### Key Features

    1. **Bidirectional State Sync**: Changes in Python update the waveform; drag events in JS update Python
    2. **CDN Loading**: No build step required - wavesurfer.js loads from CDN
    3. **Reactive**: marimo automatically updates dependent cells when widget state changes
    4. **Portable**: The same widget works in Jupyter, JupyterLab, Google Colab, and marimo

    ### Use Cases

    - **Audio Transcription**: Mark speaker turns or topics
    - **Music Analysis**: Annotate verses, choruses, bridges
    - **Torah Study**: Align Hebrew verses with audio recordings
    - **Podcast Production**: Chapter markers and segment boundaries
    - **Language Learning**: Sentence-level audio alignment

    ---

    ## 📚 Resources

    - [WavesurferWidget Source Code](https://github.com/your-repo/src/widgets/wavesurfer_widget.py)
    - [wavesurfer.js Documentation](https://wavesurfer.xyz/docs/)
    - [anywidget Getting Started](https://anywidget.dev/en/getting-started/)
    - [marimo Gallery](https://marimo.io/gallery)

    ---

    **Created by**: Torah Sync Project
    **Date**: 2026-03-16
    **License**: MIT
    """)
    return


if __name__ == "__main__":
    app.run()
