# Generated by Claude Opus 4.6
"""AlignmentRun model for forced alignment results."""

import json
from datetime import datetime

from pydantic import BaseModel, Field, field_validator

from .timestamp import VerseTimestamp


class AlignmentRun(BaseModel):
    """Result of a forced alignment run for an Alya.

    Attributes:
        id: Database primary key (None before insert)
        alya_id: FK to alyot.id
        audio_file_path: Source audio file path
        audio_duration_seconds: Total audio duration
        alignment_quality: Alignment confidence score (0.0-1.0)
        verse_count: Number of aligned verses
        timestamps_json: JSON-serialized list of VerseTimestamp
        manual_corrections: Count of manual adjustments
        manually_corrected: Whether this run has been manually corrected
        corrected_at: When last correction was applied
        backup_path: Path to backup of original alignment
        original_quality: Alignment quality before corrections
        generated_at: When alignment was performed
    """

    id: int | None = Field(default=None, description="Database PK")
    alya_id: int = Field(..., description="FK to alyot.id")
    audio_file_path: str = Field(..., min_length=1, description="Source audio file path")
    audio_duration_seconds: float = Field(..., gt=0.0, description="Total audio duration")
    alignment_quality: float = Field(
        ..., ge=0.0, le=1.0, description="Alignment confidence score"
    )
    verse_count: int = Field(..., gt=0, description="Number of aligned verses")
    timestamps_json: str = Field(..., description="JSON-serialized VerseTimestamp list")
    manual_corrections: int = Field(default=0, ge=0, description="Count of manual adjustments")
    manually_corrected: bool = Field(default=False, description="Has been manually corrected")
    corrected_at: datetime | None = Field(default=None, description="Last correction timestamp")
    backup_path: str | None = Field(default=None, description="Backup of original alignment")
    original_quality: float | None = Field(
        default=None, ge=0.0, le=1.0, description="Quality before corrections"
    )
    generated_at: datetime = Field(
        default_factory=datetime.now, description="When alignment was performed"
    )

    @field_validator("timestamps_json")
    @classmethod
    def validate_timestamps_json(cls, v: str) -> str:
        """Validate timestamps_json is parseable as a list of VerseTimestamp."""
        try:
            data = json.loads(v)
        except json.JSONDecodeError as e:
            raise ValueError(f"timestamps_json is not valid JSON: {e}") from e
        if not isinstance(data, list) or len(data) == 0:
            raise ValueError("timestamps_json must be a non-empty JSON array")
        return v

    def get_timestamps(self) -> list[VerseTimestamp]:
        """Deserialize timestamps_json into VerseTimestamp objects."""
        data = json.loads(self.timestamps_json)
        return [VerseTimestamp(**item) for item in data]

    @staticmethod
    def encode_timestamps(timestamps: list[VerseTimestamp]) -> str:
        """Serialize a list of VerseTimestamp to JSON string."""
        return json.dumps([ts.model_dump() for ts in timestamps])
