# Generated by Claude Sonnet 4.5
"""AliyahRange model for batch text fetching configuration."""

from pydantic import BaseModel, field_validator


class AliyahRange(BaseModel):
    """Verse range configuration for a Parasha/Aliyah combination.
    
    Stored in data/aliyah_ranges.toml as configuration.
    Used by ParashaTextFetcher to batch-fetch all verses for an Aliyah in a single API request.
    
    Example TOML:
        [haazinu.rishon]
        book = "Deuteronomy"
        chapter_start = 32
        verse_start = 1
        chapter_end = 32
        verse_end = 6
    """
    
    book: str
    chapter_start: int
    verse_start: int
    chapter_end: int
    verse_end: int
    
    @field_validator("book")
    @classmethod
    def validate_book(cls, v: str) -> str:
        """Validate book name is non-empty."""
        if not v or not v.strip():
            raise ValueError("book must be non-empty")
        return v.strip()
    
    @field_validator("chapter_start", "verse_start", "chapter_end", "verse_end")
    @classmethod
    def validate_positive(cls, v: int) -> int:
        """Validate chapter/verse numbers are positive."""
        if v < 1:
            raise ValueError(f"chapter/verse number must be >= 1, got {v}")
        return v
    
    def model_post_init(self, __context) -> None:
        """Validate chapter and verse ranges are valid."""
        if self.chapter_start > self.chapter_end:
            raise ValueError(
                f"chapter_start ({self.chapter_start}) must be <= chapter_end ({self.chapter_end})"
            )
        
        if self.chapter_start == self.chapter_end and self.verse_start >= self.verse_end:
            raise ValueError(
                f"When chapter_start == chapter_end, verse_start ({self.verse_start}) "
                f"must be < verse_end ({self.verse_end})"
            )
    
    def to_sefaria_reference(self) -> str:
        """Convert AliyahRange to Sefaria API reference format.
        
        Returns:
            Reference string like "Deuteronomy 32:1-6" or "Deuteronomy 32:1-33:5"
        
        Examples:
            >>> r = AliyahRange(book="Deuteronomy", chapter_start=32, verse_start=1, chapter_end=32, verse_end=6)
            >>> r.to_sefaria_reference()
            'Deuteronomy 32:1-6'
            
            >>> r = AliyahRange(book="Deuteronomy", chapter_start=32, verse_start=40, chapter_end=33, verse_end=5)
            >>> r.to_sefaria_reference()
            'Deuteronomy 32:40-33:5'
        """
        if self.chapter_start == self.chapter_end:
            return f"{self.book} {self.chapter_start}:{self.verse_start}-{self.verse_end}"
        else:
            return f"{self.book} {self.chapter_start}:{self.verse_start}-{self.chapter_end}:{self.verse_end}"
