# Generated by Claude Code
"""Aliyah data model for Torah portion subdivisions."""

from enum import Enum
from pathlib import Path

from pydantic import BaseModel, Field, field_validator

from .pasuk import Pasuk


class AliyahState(str, Enum):
    """State transitions for Aliyah processing."""

    PENDING = "pending"  # Audio file identified, not yet processed
    ALIGNING = "aligning"  # Forced alignment in progress
    ALIGNED = "aligned"  # Timestamps generated successfully
    RENDERING = "rendering"  # Video generation in progress
    COMPLETED = "completed"  # Video output ready
    FAILED = "failed"  # Processing error occurred


# Valid Aliyah names in Hebrew
VALID_ALIYAH_NAMES = {
    "ראשון",  # Rishon (First)
    "שני",  # Sheni (Second)
    "שלישי",  # Shlishi (Third)
    "רביעי",  # Revi'i (Fourth)
    "חמישי",  # Chamishi (Fifth)
    "שישי",  # Shishi (Sixth)
    "שביעי",  # Shevi'i (Seventh)
    "מפטיר",  # Maftir
    "הפטרה",  # Haftara
}


class Aliyah(BaseModel):
    """Represents a subdivision of a Parasha (Torah portion).

    Attributes:
        name: Aliyah name in Hebrew (e.g., "ראשון", "שני")
        parasha_name: Parent Parasha name
        order: Sequence number within Parasha (1-7 typically, 8 for Maftir)
        verses: List of verses in this Aliyah
        audio_file_path: Path to audio recording file
        duration_seconds: Total audio duration
        state: Current processing state
    """

    name: str = Field(..., min_length=1, description="Aliyah name in Hebrew")
    parasha_name: str = Field(..., min_length=1, description="Parent Parasha name")
    order: int = Field(..., ge=1, le=8, description="Sequence number within Parasha")
    verses: list[Pasuk] = Field(default_factory=list, description="List of verses")
    audio_file_path: Path = Field(..., description="Path to audio recording file")
    duration_seconds: float = Field(..., gt=0.0, description="Total audio duration")
    state: AliyahState = Field(
        default=AliyahState.PENDING, description="Current processing state"
    )

    @field_validator("name")
    @classmethod
    def validate_aliyah_name(cls, v: str) -> str:
        """Validate Aliyah name is one of canonical names."""
        if v not in VALID_ALIYAH_NAMES:
            raise ValueError(
                f"Invalid Aliyah name: {v}. Must be one of: {', '.join(sorted(VALID_ALIYAH_NAMES))}"
            )
        return v

    @property
    def verse_count(self) -> int:
        """Return number of verses in this Aliyah."""
        return len(self.verses)

    @property
    def is_processing(self) -> bool:
        """Check if Aliyah is currently being processed."""
        return self.state in {AliyahState.ALIGNING, AliyahState.RENDERING}

    @property
    def is_complete(self) -> bool:
        """Check if Aliyah processing is complete."""
        return self.state == AliyahState.COMPLETED

    @property
    def has_failed(self) -> bool:
        """Check if Aliyah processing has failed."""
        return self.state == AliyahState.FAILED

    def transition_to(self, new_state: AliyahState) -> None:
        """Transition to a new state.

        Args:
            new_state: Target state to transition to
        """
        self.state = new_state

    def __str__(self) -> str:
        """Return string representation of the Aliyah."""
        return f"{self.parasha_name} - {self.name} ({self.state.value}): {self.verse_count} verses"
