# Generated by Claude Opus 4.6
"""AlyaVideo model for rendered video file metadata."""

from datetime import datetime

from pydantic import BaseModel, Field, field_validator


class AlyaVideo(BaseModel):
    """Rendered video file for an Alya.

    Attributes:
        id: Database primary key (None before insert)
        alya_id: FK to alyot.id
        file_path: Output video file path
        format: Video container format
        resolution_w: Video width in pixels
        resolution_h: Video height in pixels
        frame_rate: Frames per second
        codec: Video codec
        duration_seconds: Total video duration
        youtube_video_id: YouTube video ID (set after upload)
        created_at: Record creation timestamp
    """

    id: int | None = Field(default=None, description="Database PK")
    alya_id: int = Field(..., description="FK to alyot.id")
    file_path: str = Field(..., min_length=1, description="Output video file path")
    format: str = Field(default="mp4", description="Video container format")
    resolution_w: int = Field(..., gt=0, description="Video width in pixels")
    resolution_h: int = Field(..., gt=0, description="Video height in pixels")
    frame_rate: int = Field(default=30, gt=0, description="Frames per second")
    codec: str = Field(default="h264", description="Video codec")
    duration_seconds: float = Field(..., gt=0.0, description="Total video duration")
    youtube_video_id: str | None = Field(default=None, description="YouTube video ID")
    created_at: datetime = Field(default_factory=datetime.now, description="Record creation timestamp")

    @field_validator("format")
    @classmethod
    def validate_format(cls, v: str) -> str:
        """Validate video format is MP4."""
        if v.lower() != "mp4":
            raise ValueError(f"Invalid video format: {v}. Must be 'mp4'")
        return v.lower()

    @field_validator("codec")
    @classmethod
    def validate_codec(cls, v: str) -> str:
        """Validate codec is h264."""
        if v.lower() not in {"h264", "libx264"}:
            raise ValueError(f"Invalid codec: {v}. Must be 'h264' or 'libx264'")
        return v.lower()
