# Generated by Claude Opus 4.6
# Edited by Claude Opus 4.6
"""AlyaRange model for verse ranges per alya."""

from datetime import datetime

from pydantic import BaseModel, Field


class AlyaRange(BaseModel):
    """A verse range within an Alya, supporting compound Haftarot.

    Attributes:
        id: Database primary key (None before insert)
        alya_id: FK to alyot.id
        range_order: 1-based position for ordering ranges
        book: Book name (e.g. "Deuteronomy")
        chapter_start: Starting chapter number
        verse_start: Starting verse number
        chapter_end: Ending chapter number
        verse_end: Ending verse number
        created_at: Record creation timestamp
    """

    id: int | None = Field(default=None, description="Database PK")
    alya_id: int | None = Field(default=None, description="FK to alyot.id")
    range_order: int = Field(default=1, ge=1, description="1-based range position")
    book: str = Field(..., min_length=1, description="Book name")
    chapter_start: int = Field(..., gt=0, description="Starting chapter")
    verse_start: int = Field(..., gt=0, description="Starting verse")
    chapter_end: int = Field(..., gt=0, description="Ending chapter")
    verse_end: int = Field(..., gt=0, description="Ending verse")
    created_at: datetime = Field(default_factory=datetime.now, description="Record creation timestamp")

    def to_sefaria_reference(self) -> str:
        """Convert to Sefaria API reference format.

        Returns:
            Reference string like "Deuteronomy 32:1-6" or "Deuteronomy 32:1-33:5"
        """
        if self.chapter_start == self.chapter_end:
            return f"{self.book} {self.chapter_start}:{self.verse_start}-{self.verse_end}"
        return f"{self.book} {self.chapter_start}:{self.verse_start}-{self.chapter_end}:{self.verse_end}"
