# Generated by Claude Code
"""Parasha data model for weekly Torah portions."""

from pydantic import BaseModel, Field, field_validator

from .aliyah import Aliyah


class Parasha(BaseModel):
    """Represents a weekly Torah portion from the Hebrew Bible.

    Attributes:
        name: Name of the Parasha (e.g., "האזינו", "בראשית")
        book: Torah book name (e.g., "Deuteronomy", "Genesis")
        chapter_start: Starting chapter number
        verse_start: Starting verse number
        chapter_end: Ending chapter number
        verse_end: Ending verse number
        aliyot: List of Aliyot for this Parasha (typically 7)
    """

    name: str = Field(..., min_length=1, description="Parasha name in Hebrew")
    book: str = Field(..., min_length=1, description="Torah book name")
    chapter_start: int = Field(..., gt=0, description="Starting chapter number")
    verse_start: int = Field(..., gt=0, description="Starting verse number")
    chapter_end: int = Field(..., gt=0, description="Ending chapter number")
    verse_end: int = Field(..., gt=0, description="Ending verse number")
    aliyot: list[Aliyah] = Field(default_factory=list, description="List of Aliyot")

    @field_validator("chapter_end")
    @classmethod
    def validate_chapter_order(cls, v: int, info) -> int:
        """Validate chapter_start <= chapter_end."""
        if "chapter_start" in info.data and v < info.data["chapter_start"]:
            raise ValueError(
                f"chapter_end ({v}) must be >= chapter_start ({info.data['chapter_start']})"
            )
        return v

    @field_validator("verse_end")
    @classmethod
    def validate_verse_order(cls, v: int, info) -> int:
        """Validate verse_start < verse_end when in same chapter."""
        if "chapter_start" in info.data and "chapter_end" in info.data:
            if info.data["chapter_start"] == info.data["chapter_end"]:
                if "verse_start" in info.data and v <= info.data["verse_start"]:
                    raise ValueError(
                        f"When in same chapter, verse_end ({v}) must be > verse_start ({info.data['verse_start']})"
                    )
        return v

    @property
    def aliyah_count(self) -> int:
        """Return number of Aliyot in this Parasha."""
        return len(self.aliyot)

    @property
    def total_verses(self) -> int:
        """Return total number of verses across all Aliyot."""
        return sum(aliyah.verse_count for aliyah in self.aliyot)

    def __str__(self) -> str:
        """Return string representation of the Parasha."""
        return f"{self.name} ({self.book} {self.chapter_start}:{self.verse_start}-{self.chapter_end}:{self.verse_end}): {self.aliyah_count} aliyot"
