# Generated by Claude Opus 4.6
"""PasukAlignment model for per-verse alignment rows."""

from pydantic import BaseModel, Field, model_validator


class PasukAlignment(BaseModel):
    """A single verse alignment within an AlignmentRun.

    Attributes:
        id: Database primary key (None before insert)
        alignment_run_id: FK to alignment_runs.id
        reference: Verse reference (e.g. "Deuteronomy 32:1")
        hebrew_text: Verse text with nikkud
        verse_order: Position within alya (1-based)
        start_time: Start time in seconds
        end_time: End time in seconds (must be > start_time)
        confidence: Alignment confidence score (0.0-1.0)
        original_start_time: Pre-correction start time
        original_end_time: Pre-correction end time
        manually_corrected: Whether this verse was manually corrected
    """

    id: int | None = Field(default=None, description="Database PK")
    alignment_run_id: int = Field(..., description="FK to alignment_runs.id")
    reference: str = Field(..., min_length=1, description="Verse reference")
    hebrew_text: str = Field(..., min_length=1, description="Verse text with nikkud")
    verse_order: int = Field(..., ge=1, description="Position within alya")
    start_time: float = Field(..., ge=0.0, description="Start time in seconds")
    end_time: float = Field(..., gt=0.0, description="End time in seconds")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Alignment confidence score")
    original_start_time: float | None = Field(default=None, ge=0.0, description="Pre-correction start")
    original_end_time: float | None = Field(default=None, gt=0.0, description="Pre-correction end")
    manually_corrected: bool = Field(default=False, description="Was manually corrected")

    @model_validator(mode="after")
    def validate_end_after_start(self) -> "PasukAlignment":
        """Ensure end_time > start_time."""
        if self.end_time <= self.start_time:
            raise ValueError(f"end_time ({self.end_time}) must be greater than start_time ({self.start_time})")
        return self
