# Generated by Claude Code
"""Pasuk (Verse) data model for Torah synchronization."""

from pydantic import BaseModel, Field, field_validator


class Pasuk(BaseModel):
    """Represents a single verse of Hebrew text with vowels and cantillation marks.

    Attributes:
        reference: Canonical verse reference (e.g., "Deuteronomy 32:1")
        book: Book name (e.g., "Deuteronomy")
        chapter: Chapter number (must be > 0)
        verse: Verse number within chapter (must be > 0)
        hebrew_text: Hebrew text with Nikkud (vowels) and T'amim (cantillation marks)
        start_timestamp: Start time in audio (seconds, must be >= 0)
        end_timestamp: End time in audio (seconds, must be > start_timestamp)
        aliyah_name: Parent Aliyah name (foreign key)
    """

    reference: str = Field(..., min_length=1, description="Canonical verse reference")
    book: str = Field(..., min_length=1, description="Book name")
    chapter: int = Field(..., gt=0, description="Chapter number")
    verse: int = Field(..., gt=0, description="Verse number within chapter")
    hebrew_text: str = Field(..., min_length=1, description="Hebrew text with diacritics")
    start_timestamp: float = Field(..., ge=0.0, description="Start time in audio (seconds)")
    end_timestamp: float = Field(..., gt=0.0, description="End time in audio (seconds)")
    aliyah_name: str = Field(..., min_length=1, description="Parent Aliyah name")

    @field_validator("reference")
    @classmethod
    def validate_reference_format(cls, v: str) -> str:
        """Validate reference format: {Book} {chapter}:{verse}."""
        if ":" not in v or " " not in v:
            raise ValueError(
                f"Invalid reference format: {v}. Expected format: '{{Book}} {{chapter}}:{{verse}}'"
            )
        return v

    @field_validator("hebrew_text")
    @classmethod
    def validate_hebrew_unicode(cls, v: str) -> str:
        """Validate Hebrew text contains Hebrew Unicode characters (U+0590 to U+05FF)."""
        has_hebrew = any("\u0590" <= char <= "\u05FF" for char in v)
        if not has_hebrew:
            raise ValueError(
                f"Hebrew text must contain Hebrew Unicode characters (U+0590-U+05FF): {v}"
            )
        return v

    @field_validator("end_timestamp")
    @classmethod
    def validate_timestamp_order(cls, v: float, info) -> float:
        """Validate end_timestamp > start_timestamp."""
        if "start_timestamp" in info.data and v <= info.data["start_timestamp"]:
            raise ValueError(
                f"end_timestamp ({v}) must be greater than start_timestamp ({info.data['start_timestamp']})"
            )
        return v

    @property
    def duration(self) -> float:
        """Calculate verse duration in seconds."""
        return self.end_timestamp - self.start_timestamp

    def __str__(self) -> str:
        """Return string representation of the Pasuk."""
        return f"{self.reference}: {self.hebrew_text[:30]}..."
