# Generated by Claude Code
"""TimestampMap model for verse-to-audio alignment mappings."""

from datetime import datetime
from pathlib import Path

from pydantic import BaseModel, Field, field_validator

from .timestamp import VerseTimestamp


class TimestampMap(BaseModel):
    """Represents the mapping of each verse to its precise audio timestamps.

    Attributes:
        parasha_name: Parasha name
        aliyah_name: Aliyah name
        audio_file_path: Source audio file path
        audio_duration_seconds: Total audio duration
        verse_timestamps: List of verse-to-timestamp mappings (must be sorted)
        alignment_quality: Alignment confidence score (0.0-1.0)
        generated_at: When alignment was performed
        manual_corrections: Count of manually adjusted timestamps
    """

    parasha_name: str = Field(..., min_length=1, description="Parasha name")
    aliyah_name: str = Field(..., min_length=1, description="Aliyah name")
    audio_file_path: Path = Field(..., description="Source audio file path")
    audio_duration_seconds: float = Field(..., gt=0.0, description="Total audio duration")
    verse_timestamps: list[VerseTimestamp] = Field(
        ..., min_length=1, description="List of verse-to-timestamp mappings"
    )
    alignment_quality: float = Field(
        ..., ge=0.0, le=1.0, description="Alignment confidence score (0.0-1.0)"
    )
    generated_at: datetime = Field(
        default_factory=datetime.now, description="When alignment was performed"
    )
    manual_corrections: int = Field(default=0, ge=0, description="Count of manual adjustments")

    @field_validator("verse_timestamps")
    @classmethod
    def validate_monotonic_timestamps(cls, v: list[VerseTimestamp]) -> list[VerseTimestamp]:
        """Validate timestamps are monotonically increasing and have no overlaps."""
        if not v:
            raise ValueError("verse_timestamps cannot be empty")

        for i in range(len(v) - 1):
            current = v[i]
            next_verse = v[i + 1]

            # Check monotonic increase
            if current.start_time >= next_verse.start_time:
                raise ValueError(
                    f"Timestamps must be monotonically increasing: "
                    f"{current.reference} start_time ({current.start_time}) >= "
                    f"{next_verse.reference} start_time ({next_verse.start_time})"
                )

            # Check no overlaps
            if current.end_time > next_verse.start_time:
                raise ValueError(
                    f"Timestamp overlap detected: "
                    f"{current.reference} end_time ({current.end_time}) > "
                    f"{next_verse.reference} start_time ({next_verse.start_time})"
                )

            # Check no gaps > 5 seconds
            gap = next_verse.start_time - current.end_time
            if gap > 5.0:
                raise ValueError(
                    f"Gap too large ({gap:.2f}s) between {current.reference} and {next_verse.reference}"
                )

        # Check first verse starts near 0.0 (within 5 seconds)
        if v[0].start_time > 5.0:
            raise ValueError(
                f"First verse {v[0].reference} starts too late ({v[0].start_time:.2f}s > 5.0s)"
            )

        return v

    @field_validator("alignment_quality")
    @classmethod
    def validate_quality_threshold(cls, v: float) -> float:
        """Validate alignment quality meets minimum threshold."""
        if v < 0.85:
            raise ValueError(
                f"Alignment quality ({v:.2f}) below acceptable threshold (0.85). "
                "Consider manual correction or re-alignment."
            )
        return v

    @property
    def verse_count(self) -> int:
        """Return number of verses in this Aliyah."""
        return len(self.verse_timestamps)

    @property
    def average_confidence(self) -> float:
        """Calculate average confidence across all verse timestamps."""
        if not self.verse_timestamps:
            return 0.0
        return sum(vt.confidence for vt in self.verse_timestamps) / len(self.verse_timestamps)

    def __str__(self) -> str:
        """Return string representation of the TimestampMap."""
        return (
            f"TimestampMap({self.parasha_name}/{self.aliyah_name}): "
            f"{self.verse_count} verses, quality={self.alignment_quality:.2f}"
        )
