# Generated by Claude Code
"""Timestamp models for verse-to-audio alignment."""

from pydantic import BaseModel, Field, field_validator


class VerseTimestamp(BaseModel):
    """Embedded model representing timestamp mapping for a single verse.

    Attributes:
        reference: Canonical verse reference (e.g., "Deuteronomy 32:1")
        start_time: Start time in audio (seconds, must be >= 0)
        end_time: End time in audio (seconds, must be > start_time)
        confidence: Alignment confidence score (0.0-1.0)
    """

    reference: str = Field(..., min_length=1, description="Canonical verse reference")
    start_time: float = Field(..., ge=0.0, description="Start time in audio (seconds)")
    end_time: float = Field(..., gt=0.0, description="End time in audio (seconds)")
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Alignment confidence score (0.0-1.0)"
    )

    @field_validator("end_time")
    @classmethod
    def validate_time_order(cls, v: float, info) -> float:
        """Validate end_time > start_time."""
        if "start_time" in info.data and v <= info.data["start_time"]:
            raise ValueError(
                f"end_time ({v}) must be greater than start_time ({info.data['start_time']})"
            )
        return v

    @property
    def duration(self) -> float:
        """Calculate timestamp duration in seconds."""
        return self.end_time - self.start_time

    def __str__(self) -> str:
        """Return string representation of the VerseTimestamp."""
        return f"{self.reference}: {self.start_time:.2f}s - {self.end_time:.2f}s (conf: {self.confidence:.2f})"
