# Generated by Claude Code
"""SynchronizedVideo data model for output video files."""

from datetime import datetime
from pathlib import Path

from pydantic import BaseModel, Field, field_validator


class SynchronizedVideo(BaseModel):
    """Represents the output video file with highlighted text overlay.

    Attributes:
        file_path: Output video file path
        format: Video container format (must be "mp4")
        resolution: Video resolution (width, height) - must be (640, 360) for 360p
        frame_rate: Frames per second (should be 30)
        codec: Video codec (must be "h264")
        duration_seconds: Total video duration (must match audio)
        parasha_name: Associated Parasha
        aliyah_name: Associated Aliyah
        created_at: Timestamp of video generation
    """

    file_path: Path = Field(..., description="Output video file path")
    format: str = Field(..., description="Video container format")
    resolution: tuple[int, int] = Field(..., description="Video resolution (width, height)")
    frame_rate: int = Field(..., description="Frames per second")
    codec: str = Field(..., description="Video codec")
    duration_seconds: float = Field(..., gt=0.0, description="Total video duration")
    parasha_name: str = Field(..., min_length=1, description="Associated Parasha")
    aliyah_name: str = Field(..., min_length=1, description="Associated Aliyah")
    created_at: datetime = Field(
        default_factory=datetime.now, description="Timestamp of video generation"
    )

    @field_validator("format")
    @classmethod
    def validate_format(cls, v: str) -> str:
        """Validate video format is MP4."""
        if v.lower() != "mp4":
            raise ValueError(f"Invalid video format: {v}. Must be 'mp4'")
        return v.lower()

    @field_validator("resolution")
    @classmethod
    def validate_resolution(cls, v: tuple[int, int]) -> tuple[int, int]:
        """Validate resolution is 360p (640x360)."""
        if v != (640, 360):
            raise ValueError(f"Invalid resolution: {v}. Must be (640, 360) for 360p")
        return v

    @field_validator("frame_rate")
    @classmethod
    def validate_frame_rate(cls, v: int) -> int:
        """Validate frame rate is 30 fps."""
        if v != 30:
            raise ValueError(f"Invalid frame rate: {v}. Should be 30 fps")
        return v

    @field_validator("codec")
    @classmethod
    def validate_codec(cls, v: str) -> str:
        """Validate codec is h264."""
        if v.lower() not in {"h264", "libx264"}:
            raise ValueError(f"Invalid codec: {v}. Must be 'h264' or 'libx264'")
        return v.lower()

    @property
    def file_size_mb(self) -> float | None:
        """Get file size in megabytes if file exists."""
        if self.file_path.exists():
            return self.file_path.stat().st_size / (1024 * 1024)
        return None

    @property
    def exists(self) -> bool:
        """Check if video file exists."""
        return self.file_path.exists()

    def __str__(self) -> str:
        """Return string representation of the SynchronizedVideo."""
        size_str = f"{self.file_size_mb:.1f}MB" if self.file_size_mb else "not created"
        return (
            f"{self.parasha_name}/{self.aliyah_name}: "
            f"{self.resolution[0]}x{self.resolution[1]} @ {self.frame_rate}fps, "
            f"{self.duration_seconds:.1f}s ({size_str})"
        )
