# Generated by Claude Sonnet 4.5
"""YouTube playlist model for organizing videos by parasha."""

from datetime import datetime

from pydantic import BaseModel, Field


class YouTubePlaylist(BaseModel):
    """YouTube playlist representing a parasha with its aliyot.

    Attributes:
        playlist_id: Foreign key to playlists table
        youtube_playlist_id: YouTube playlist ID (actual YouTube ID)
        title: Playlist title
        description: Playlist description
        privacy_status: Privacy level ("private", "unlisted", "public")
        video_ids: List of video IDs in the playlist (ordered by aliyah)
        aliyah_count: Expected number of aliyot (default: 7)
        created_at: When playlist was created
        updated_at: Last update time
    """

    playlist_id: int = Field(..., description="FK to playlists.id")
    youtube_playlist_id: str = Field(..., description="YouTube playlist ID")
    title: str = Field(..., max_length=150, description="Playlist title")
    description: str = Field("", max_length=5000, description="Playlist description")
    privacy_status: str = Field("unlisted", description="Privacy status")
    video_ids: list[str] = Field(
        default_factory=list, description="Video IDs in order (by aliyah)"
    )
    aliyah_count: int = Field(7, description="Expected number of aliyot")
    created_at: datetime | None = Field(None, description="Creation timestamp")
    updated_at: datetime | None = Field(None, description="Last update timestamp")

    def is_complete(self) -> bool:
        """Check if playlist has all expected aliyot.

        Returns:
            True if video count matches expected aliyah count
        """
        return len(self.video_ids) == self.aliyah_count

    def get_aliyah_position(self, aliyah_name: str) -> int:
        """Get position for an aliyah in the playlist.

        Maps Hebrew aliyah names to zero-based playlist positions:
        - ראשון → 0
        - שני → 1
        - שלישי → 2
        - רביעי → 3
        - חמישי → 4
        - ששי → 5
        - שביעי → 6

        Args:
            aliyah_name: Aliyah name (Hebrew)

        Returns:
            Zero-based position in playlist (0-6)
        """
        aliyah_order = {
            "ראשון": 0,
            "שני": 1,
            "שלישי": 2,
            "רביעי": 3,
            "חמישי": 4,
            "ששי": 5,
            "שביעי": 6,
        }
        return aliyah_order.get(aliyah_name, 0)
