# Generated by Claude Sonnet 4.5
"""YouTube thumbnail model for cached thumbnail metadata."""

from datetime import datetime
from pathlib import Path

from pydantic import BaseModel, Field


class YouTubeThumbnail(BaseModel):
    """Cached YouTube thumbnail metadata.

    Attributes:
        id: DuckDB primary key
        video_id: YouTube video ID
        original_url: Original thumbnail URL from YouTube
        cached_path: Local file path (data/thumbnails/VIDEO_ID.jpg)
        title: Original video title
        downloaded_at: When thumbnail was cached
    """

    id: int = Field(..., description="DuckDB PK")
    video_id: str = Field(..., description="YouTube video ID")
    original_url: str = Field(..., description="Original thumbnail URL")
    cached_path: Path = Field(..., description="Local cached file path")
    title: str | None = Field(None, description="Original video title")
    downloaded_at: datetime = Field(..., description="Download timestamp")

    def exists(self) -> bool:
        """Check if cached thumbnail file exists on disk.

        Returns:
            True if file exists, False otherwise
        """
        return self.cached_path.exists()
