# Generated by Claude Sonnet 4.5
"""YouTube video model with metadata and thumbnail tracking."""

from datetime import datetime
from pathlib import Path

from pydantic import BaseModel, Field


class YouTubeVideo(BaseModel):
    """YouTube video with metadata and thumbnail information.

    Attributes:
        video_id: YouTube video ID
        title: Current video title
        description: Current video description
        thumbnail_url: URL of current thumbnail (maxres > high > default)
        thumbnail_local_path: Local cached thumbnail path
        published_at: Video publication date
        duration: Video duration in ISO 8601 format
        view_count: Current view count
        privacy_status: Privacy level (private, unlisted, public)
        alya_video_id: Foreign key to alya_videos table (optional)
    """

    video_id: str = Field(..., description="YouTube video ID")
    title: str = Field(..., description="Video title")
    description: str = Field("", description="Video description")
    thumbnail_url: str = Field(..., description="Thumbnail URL")
    thumbnail_local_path: Path | None = Field(
        None, description="Local cached thumbnail"
    )
    published_at: datetime | None = Field(None, description="Publication date")
    duration: str | None = Field(None, description="Video duration (ISO 8601)")
    view_count: int = Field(0, description="View count")
    privacy_status: str = Field("unlisted", description="Privacy status")
    alya_video_id: int | None = Field(None, description="FK to alya_videos.id")

    def has_cached_thumbnail(self) -> bool:
        """Check if thumbnail is cached locally.

        Returns:
            True if thumbnail exists on disk, False otherwise
        """
        return (
            self.thumbnail_local_path is not None
            and self.thumbnail_local_path.exists()
        )
