# Generated by Claude Sonnet 4.5
"""YouTube metadata model with CIFRIA attribution."""

from pydantic import BaseModel, Field, field_validator


class YouTubeMetadata(BaseModel):
    """YouTube video metadata with CIFRIA attribution.

    Attributes:
        video_id: YouTube video ID (if already uploaded)
        title: Video title (max 100 chars)
        description: Video description (max 5000 chars)
        tags: List of tags (max 500 chars total)
        category_id: YouTube category ID (default: 27 = Education)
        default_language: Video language (default: "he" for Hebrew)
        default_audio_language: Audio language (default: "he")
        privacy_status: Privacy level ("private", "unlisted", "public")
        cifria_attribution: CIFRIA attribution text
    """

    video_id: str | None = Field(None, description="YouTube video ID")
    title: str = Field(..., max_length=100, description="Video title")
    description: str = Field(..., max_length=5000, description="Video description")
    tags: list[str] = Field(default_factory=list, description="Video tags")
    category_id: str = Field("27", description="YouTube category (27=Education)")
    default_language: str = Field("he", description="Video language")
    default_audio_language: str = Field("he", description="Audio language")
    privacy_status: str = Field("unlisted", description="Privacy status")
    cifria_attribution: str = Field(
        default="Source materials courtesy of CIFRIA",
        description="CIFRIA attribution text",
    )

    @field_validator("tags")
    @classmethod
    def validate_tags(cls, v: list[str]) -> list[str]:
        """Validate total tag length doesn't exceed 500 characters.

        Args:
            v: List of tags

        Returns:
            Validated tags list

        Raises:
            ValueError: If total tag length exceeds 500 chars
        """
        total_length = sum(len(tag) for tag in v)
        if total_length > 500:
            raise ValueError(f"Total tags length {total_length} exceeds 500 chars")
        return v

    @field_validator("privacy_status")
    @classmethod
    def validate_privacy(cls, v: str) -> str:
        """Validate privacy status.

        Args:
            v: Privacy status string

        Returns:
            Validated privacy status

        Raises:
            ValueError: If invalid privacy status
        """
        if v not in {"private", "unlisted", "public"}:
            raise ValueError(f"Invalid privacy status: {v}")
        return v
