"""Wavesurfer AnyWidget for marimo - Interactive Audio Waveform Visualization.

Generated by Claude Sonnet 4.5

This widget wraps wavesurfer.js v7 to provide interactive audio waveform display
with region support for audio segment annotation and editing.

Usage:
    import marimo as mo
    from src.widgets.wavesurfer_widget import WavesurferWidget

    # Load audio file
    with open("audio.mp3", "rb") as f:
        audio_bytes = f.read()

    # Create widget with regions
    widget = WavesurferWidget(
        audio_data=audio_bytes,
        regions=[
            {"id": "verse1", "start": 0.0, "end": 5.3, "label": "Verse 1", "color": "rgba(0, 123, 255, 0.3)"},
            {"id": "verse2", "start": 5.3, "end": 10.8, "label": "Verse 2", "color": "rgba(0, 200, 100, 0.3)"},
        ],
    )

    # Display in marimo
    mo.ui.anywidget(widget)

    # Access state
    widget.current_time  # Current playback position
    widget.is_playing    # Play/pause state
    widget.selected_region_id  # Selected region ID
    widget.regions       # Updated regions after dragging
"""

import anywidget
import traitlets


class WavesurferWidget(anywidget.AnyWidget):
    """Interactive audio waveform widget using wavesurfer.js.

    Attributes:
        audio_data: Audio file as bytes (automatically converted to data URL in JS)
        regions: List of region dictionaries with {id, start, end, label, color, drag, resize}
        current_time: Current playback position in seconds
        is_playing: Whether audio is currently playing
        selected_region_id: ID of currently selected region (or empty string)
        duration: Total audio duration in seconds (set by JS after loading)
        waveform_color: Color of the waveform
        progress_color: Color of the played portion
        height: Height of waveform in pixels
    """

    # Audio data (Python → JavaScript)
    audio_data = traitlets.Bytes(default_value=b"").tag(sync=True)

    # Regions (bidirectional)
    regions = traitlets.List(trait=traitlets.Dict()).tag(sync=True)

    # Playback state (bidirectional)
    current_time = traitlets.Float(default_value=0.0).tag(sync=True)
    is_playing = traitlets.Bool(default_value=False).tag(sync=True)

    # Selection state (bidirectional)
    selected_region_id = traitlets.Unicode(default_value="").tag(sync=True)

    # Audio metadata (JavaScript → Python)
    duration = traitlets.Float(default_value=0.0).tag(sync=True)

    # Appearance (Python → JavaScript)
    waveform_color = traitlets.Unicode(default_value="#4F4A85").tag(sync=True)
    progress_color = traitlets.Unicode(default_value="#383351").tag(sync=True)
    height = traitlets.Int(default_value=128).tag(sync=True)

    # ESM module with wavesurfer.js integration
    _esm = """
    // Import wavesurfer.js and plugins from CDN
    import WaveSurfer from 'https://cdn.jsdelivr.net/npm/wavesurfer.js@7/dist/wavesurfer.esm.js';
    import RegionsPlugin from 'https://cdn.jsdelivr.net/npm/wavesurfer.js@7/dist/plugins/regions.esm.js';
    import TimelinePlugin from 'https://cdn.jsdelivr.net/npm/wavesurfer.js@7/dist/plugins/timeline.esm.js';

    function render({ model, el }) {
      // Create container structure
      const container = document.createElement('div');
      container.style.width = '100%';
      container.style.fontFamily = 'sans-serif';

      const waveformDiv = document.createElement('div');
      waveformDiv.id = 'waveform-' + Math.random().toString(36).substr(2, 9);

      const controls = document.createElement('div');
      controls.style.marginTop = '10px';
      controls.style.display = 'flex';
      controls.style.gap = '10px';
      controls.style.alignItems = 'center';

      const playPauseBtn = document.createElement('button');
      playPauseBtn.textContent = '▶ Play';
      playPauseBtn.style.padding = '8px 16px';
      playPauseBtn.style.cursor = 'pointer';
      playPauseBtn.style.fontSize = '14px';

      const timeDisplay = document.createElement('span');
      timeDisplay.style.fontFamily = 'monospace';
      timeDisplay.style.fontSize = '14px';
      timeDisplay.textContent = '0.000 / 0.000';

      const regionInfo = document.createElement('div');
      regionInfo.style.marginTop = '10px';
      regionInfo.style.padding = '8px';
      regionInfo.style.backgroundColor = '#f0f0f0';
      regionInfo.style.borderRadius = '4px';
      regionInfo.style.fontSize = '13px';
      regionInfo.textContent = 'Click a region to select it';

      controls.appendChild(playPauseBtn);
      controls.appendChild(timeDisplay);
      container.appendChild(waveformDiv);
      container.appendChild(controls);
      container.appendChild(regionInfo);
      el.appendChild(container);

      // Initialize plugins
      const regionsPlugin = RegionsPlugin.create();
      const timelinePlugin = TimelinePlugin.create({
        height: 20,
        timeInterval: 0.5,
        primaryLabelInterval: 5,
        style: {
          fontSize: '10px',
          color: '#6B7280',
        },
      });

      // Create WaveSurfer instance
      const wavesurfer = WaveSurfer.create({
        container: waveformDiv,
        waveColor: model.get('waveform_color'),
        progressColor: model.get('progress_color'),
        height: model.get('height'),
        normalize: true,
        plugins: [regionsPlugin, timelinePlugin],
      });

      // Convert audio bytes to data URL
      const audioData = model.get('audio_data');
      if (audioData && audioData.byteLength > 0) {
        const blob = new Blob([audioData], { type: 'audio/mpeg' });
        const url = URL.createObjectURL(blob);
        wavesurfer.load(url);
      }

      // Update duration when audio is loaded
      wavesurfer.on('ready', () => {
        const dur = wavesurfer.getDuration();
        model.set('duration', dur);
        model.save_changes();
        timeDisplay.textContent = `0.000 / ${dur.toFixed(3)}`;

        // Initialize regions from model
        const regions = model.get('regions') || [];
        regions.forEach((region) => {
          regionsPlugin.addRegion({
            id: region.id,
            start: region.start,
            end: region.end,
            color: region.color || 'rgba(0, 123, 255, 0.3)',
            drag: region.drag !== false,
            resize: region.resize !== false,
            content: region.label || '',
          });
        });
      });

      // Update time display during playback
      // Note: Don't sync current_time to Python during playback to avoid stuttering
      wavesurfer.on('timeupdate', (currentTime) => {
        const dur = wavesurfer.getDuration();
        timeDisplay.textContent = `${currentTime.toFixed(3)} / ${dur.toFixed(3)}`;
      });

      // Sync play/pause state
      wavesurfer.on('play', () => {
        model.set('is_playing', true);
        model.save_changes();
        playPauseBtn.textContent = '⏸ Pause';
      });

      wavesurfer.on('pause', () => {
        model.set('is_playing', false);
        model.set('current_time', wavesurfer.getCurrentTime());
        model.save_changes();
        playPauseBtn.textContent = '▶ Play';
      });

      // Play/Pause button
      playPauseBtn.addEventListener('click', () => {
        wavesurfer.playPause();
      });

      // Region events
      regionsPlugin.on('region-updated', (region) => {
        // Update regions list in model
        const regions = model.get('regions').map((r) => {
          if (r.id === region.id) {
            return {
              ...r,
              start: region.start,
              end: region.end,
            };
          }
          return r;
        });
        model.set('regions', regions);
        model.save_changes();
      });

      regionsPlugin.on('region-clicked', (region, e) => {
        // Highlight clicked region
        regionsPlugin.getRegions().forEach((r) => {
          r.element.style.opacity = r.id === region.id ? '0.6' : '0.3';
        });

        model.set('selected_region_id', region.id);
        model.save_changes();

        // Update region info display
        regionInfo.innerHTML = `
          <strong>Selected:</strong> ${region.content || region.id}<br>
          <strong>Time:</strong> ${region.start.toFixed(3)}s - ${region.end.toFixed(3)}s
          (duration: ${(region.end - region.start).toFixed(3)}s)
        `;

        e.stopPropagation();
      });

      // Listen to model changes from Python
      model.on('change:audio_data', () => {
        const audioData = model.get('audio_data');
        if (audioData && audioData.byteLength > 0) {
          const blob = new Blob([audioData], { type: 'audio/mpeg' });
          const url = URL.createObjectURL(blob);
          wavesurfer.load(url);
        }
      });

      model.on('change:regions', () => {
        // Clear existing regions and recreate
        regionsPlugin.clearRegions();
        const regions = model.get('regions') || [];
        regions.forEach((region) => {
          regionsPlugin.addRegion({
            id: region.id,
            start: region.start,
            end: region.end,
            color: region.color || 'rgba(0, 123, 255, 0.3)',
            drag: region.drag !== false,
            resize: region.resize !== false,
            content: region.label || '',
          });
        });
      });

      model.on('change:current_time', () => {
        const time = model.get('current_time');
        wavesurfer.setTime(time);
      });

      model.on('change:waveform_color', () => {
        wavesurfer.setOptions({ waveColor: model.get('waveform_color') });
      });

      model.on('change:progress_color', () => {
        wavesurfer.setOptions({ progressColor: model.get('progress_color') });
      });

      // Cleanup on destroy
      return () => {
        wavesurfer.destroy();
      };
    }

    export default { render };
    """

    _css = """
    .wavesurfer-region {
      transition: opacity 0.2s ease;
    }
    """
